#!/usr/bin/env python3
"""Translate admin_ru.json keys to Russian"""

import json, re, sys

translations = {
    # COMMON UI
    "Dashboard": "Панель управления",
    "Home": "Главная",
    "Save": "Сохранить",
    "Saved": "Сохранено",
    "Cancel": "Отмена",
    "cancel": "отмена",
    "Close": "Закрыть",
    "Closed": "Закрыто",
    "closed": "закрыто",
    "Delete": "Удалить",
    "Deleted successfully": "Успешно удалено",
    "Edit": "Редактировать",
    "Update": "Обновить",
    "Create": "Создать",
    "Add": "Добавить",
    "Add New": "Добавить новый",
    "View": "Просмотр",
    "View All": "Посмотреть все",
    "View Details": "Подробнее",
    "View More": "Посмотреть больше",
    "View Profile": "Посмотреть профиль",
    "Visit Profile": "Посетить профиль",
    "Back": "Назад",
    "Back to Lists": "Вернуться к списку",
    "Back to Home": "На главную",
    "Submit": "Отправить",
    "Search": "Поиск",
    "Filter": "Фильтр",
    "Filters": "Фильтры",
    "Reset": "Сбросить",
    "Reset All": "Сбросить всё",
    "Clear": "Очистить",
    "Import": "Импорт",
    "Export": "Экспорт",
    "Download": "Скачать",
    "Download File": "Скачать файл",
    "Upload": "Загрузить",
    "Choose": "Выбрать",
    "Choose file": "Выберите файл",
    "Choose Image": "Выберите изображение",
    "Choose Photo": "Выбрать фото",
    "Browse": "Обзор",
    "File": "Файл",
    "File not found": "Файл не найден",
    "File Upload": "Загрузка файла",
    "File Download Link": "Ссылка для скачивания файла",
    "Print": "Печать",
    "print": "печать",
    "Preview": "Предпросмотр",
    "Publish": "Опубликовать",
    "Unpublish": "Снять с публикации",
    "Draft": "Черновик",
    "Archived": "Архивировано",
    "Trash": "Корзина",
    "Restore": "Восстановить",
    "Copy": "Копировать",
    "Copy Link": "Копировать ссылку",
    "Move": "Переместить",
    "Rename": "Переименовать",
    "Refresh": "Обновить",
    "Reload": "Перезагрузить",
    "Loading...": "Загрузка...",
    "Loading": "Загрузка",
    "Processing...": "Обработка...",
    "Please wait...": "Пожалуйста, подождите...",
    "No data available": "Нет данных",
    "No results found": "Ничего не найдено",
    "No items found": "Элементы не найдены",
    "No records found": "Записи не найдены",
    "Empty": "Пусто",
    "None": "Нет",
    "All": "Все",
    "Select": "Выбрать",
    "Select All": "Выбрать все",
    "Deselect All": "Снять выделение",
    "Are you sure": "Вы уверены",
    "Confirm": "Подтвердить",
    "Confirm Delete": "Подтвердить удаление",
    "Confirm Password": "Подтверждение пароля",
    "Confirm New Password": "Подтвердите новый пароль",
    "Yes": "Да",
    "No": "Нет",
    "Next": "Далее",
    "Previous": "Назад",
    "Finish": "Завершить",
    "Skip": "Пропустить",
    "Continue": "Продолжить",
    "Proceed": "Продолжить",
    "Go Back": "Вернуться",
    "Go to Login": "Перейти к входу",
    "Login": "Войти",
    "Logout": "Выйти",
    "Register": "Регистрация",
    "Signup": "Регистрация",
    "Sign In": "Войти",
    "Sign Out": "Выйти",
    "Sign Up": "Регистрация",
    "Forgot Password?": "Забыли пароль?",
    "Forgot password": "Забыли пароль",
    "Forget Password": "Забыли пароль",
    "Reset Password": "Сбросить пароль",
    "Change Password": "Изменить пароль",
    "Current Password": "Текущий пароль",
    "New Password": "Новый пароль",
    "Password": "Пароль",
    "Remember Me": "Запомнить меня",
    "Email": "Эл. почта",
    "Email Address": "Адрес эл. почты",
    "Email ID": "Email ID",
    "Username": "Имя пользователя",
    "Username/Email*": "Имя пользователя/Email*",
    "Password*": "Пароль*",
    "Email*": "Email*",
    "Confirm Password*": "Подтверждение пароля*",
    "New Password*": "Новый пароль*",
    "Current Password*": "Текущий пароль*",
    "Confirm New Password*": "Подтверждение нового пароля*",
    "Name": "Имя",
    "First Name": "Имя",
    "Last Name": "Фамилия",
    "Full Name": "Полное имя",
    "Phone": "Телефон",
    "Phone Number": "Номер телефона",
    "Mobile": "Мобильный",
    "Address": "Адрес",
    "City": "Город",
    "State": "Область",
    "Country": "Страна",
    "Zip Code": "Почтовый индекс",
    "Postcode/Zip": "Индекс",
    "Location": "Местоположение",
    "Latitude": "Широта",
    "Longitude": "Долгота",
    "Website": "Веб-сайт",
    "URL": "URL",
    "Link": "Ссылка",
    "Image": "Изображение",
    "Images": "Изображения",
    "Photo": "Фото",
    "Icon": "Иконка",
    "Logo": "Логотип",
    "Favicon": "Фавикон",
    "Avatar": "Аватар",
    "Banner": "Баннер",
    "Banner Image": "Изображение баннера",
    "Background Image": "Фоновое изображение",
    "Gallery": "Галерея",
    "Gallery Images": "Изображения галереи",
    "Slider": "Слайдер",
    "Video": "Видео",
    "Audio": "Аудио",
    "Document": "Документ",
    "Attachment": "Вложение",
    "Featured Image": "Избранное изображение",
    "Thumbnail": "Миниатюра",
    "Preview Image": "Изображение предпросмотра",
    "Cover Image": "Обложка",
    # STATUSES
    "Status": "Статус",
    "Active": "Активен",
    "Inactive": "Неактивен",
    "Deactive": "Деактивировать",
    "Enable": "Включить",
    "Disable": "Отключить",
    "Enabled": "Включено",
    "Disabled": "Отключено",
    "Show": "Показать",
    "Hide": "Скрыть",
    "Hide/Show": "Скрыть/Показать",
    "On": "Вкл",
    "Off": "Выкл",
    "Pending": "В ожидании",
    "pending": "в ожидании",
    "Approved": "Одобрено",
    "approved": "одобрено",
    "Rejected": "Отклонено",
    "rejected": "отклонено",
    "Completed": "Завершено",
    "completed": "завершено",
    "processing": "обработка",
    "Published": "Опубликовано",
    "Unpublished": "Не опубликовано",
    "Locked": "Заблокировано",
    "Unlocked": "Разблокировано",
    "Verified": "Подтверждено",
    "Unverified": "Не подтверждено",
    "Suspended": "Приостановлено",
    "Banned": "Забанен",
    "Expired": "Истёк",
    "Fulfilled": "Выполнено",
    "Default": "По умолчанию",
    "(Default)": "(По умолчанию)",
    "Blank": "Пустой",
    "Never Activated": "Никогда не активирован",
    # ACTIONS
    "Action": "Действие",
    "Actions": "Действия",
    "Manage": "Управление",
    "Manage Form": "Управление формой",
    "Manage Listings": "Управление объявлениями",
    "Manage Plugins": "Управление плагинами",
    "Manage Products": "Управление товарами",
    "Manage Social Link": "Управление соцссылками",
    "Clone": "Клонировать",
    "Clone for": "Клонировать для",
    "Duplicate": "Дублировать",
    "Assign": "Назначить",
    "Assigned Staff": "Назначенный сотрудник",
    "Assigned to": "Назначен на",
    "Assign Staff": "Назначить сотрудника",
    "Assing To": "Назначить на",
    "Send": "Отправить",
    "Send message": "Отправить сообщение",
    "Send Email": "Отправить Email",
    "Send SMS": "Отправить SMS",
    "Send Notification": "Отправить уведомление",
    "Reply": "Ответить",
    "Report": "Отчёт",
    "Download Report": "Скачать отчёт",
    "Generate Report": "Создать отчёт",
    "Bulk Action": "Массовое действие",
    "Bulk Delete": "Массовое удаление",
    "Bulk Update": "Массовое обновление",
    "Import Data": "Импорт данных",
    "Export Data": "Экспорт данных",
    "Export CSV": "Экспорт CSV",
    "Export Excel": "Экспорт Excel",
    "Export PDF": "Экспорт PDF",
    "Print Invoice": "Печать счёта",
    "Share": "Поделиться",
    "Share Now": "Поделиться",
    "Share on": "Поделиться в",
    # DATE & TIME
    "Date": "Дата",
    "date": "дата",
    "Time": "Время",
    "Day": "День",
    "day": "день",
    "Days": "Дни",
    "Days For": "Дней для",
    "Month": "Месяц",
    "month": "месяц",
    "Year": "Год",
    "year": "год",
    "Hour": "Час",
    "hour": "час",
    "Minute": "Минута",
    "minute": "минута",
    "Second": "Секунда",
    "second": "секунда",
    "Today": "Сегодня",
    "Yesterday": "Вчера",
    "Tomorrow": "Завтра",
    "This Week": "На этой неделе",
    "Last Week": "На прошлой неделе",
    "This Month": "В этом месяце",
    "Last Month": "В прошлом месяце",
    "This Year": "В этом году",
    "Last Year": "В прошлом году",
    "Start Date": "Дата начала",
    "End Date": "Дата окончания",
    "Start Time": "Время начала",
    "End Time": "Время окончания",
    "Expire Date": "Дата истечения",
    "Expire Month": "Месяц истечения",
    "Expire Year": "Год истечения",
    "Expires": "Истекает",
    "Created": "Создано",
    "Created At": "Дата создания",
    "Updated At": "Дата обновления",
    "Deleted At": "Дата удаления",
    "Calendar": "Календарь",
    "Schedule": "Расписание",
    "Duration": "Длительность",
    "12 Hour": "12-часовой",
    "24 Hour": "24-часовой",
    "Monday": "Понедельник",
    "Tuesday": "Вторник",
    "Wednesday": "Среда",
    "Thursday": "Четверг",
    "Friday": "Пятница",
    "Saturday": "Суббота",
    "Sunday": "Воскресенье",
    # USERS & ADMIN
    "User": "Пользователь",
    "Users": "Пользователи",
    "Add User": "Добавить пользователя",
    "Edit User": "Редактировать пользователя",
    "User Management": "Управление пользователями",
    "Registered Users": "Зарегистрированные пользователи",
    "User List": "Список пользователей",
    "User Details": "Детали пользователя",
    "User Profile": "Профиль пользователя",
    "User Role": "Роль пользователя",
    "User Status": "Статус пользователя",
    "Account": "Аккаунт",
    "Account Information": "Информация об аккаунте",
    "Account Status": "Статус аккаунта",
    "Account status updated successfully": "Статус аккаунта успешно обновлён",
    "Account Settings": "Настройки аккаунта",
    "Profile": "Профиль",
    "Edit Profile": "Редактировать профиль",
    "Edit Your Profile": "Редактировать профиль",
    "Edit Profile Page Title": "Заголовок страницы профиля",
    "Update Profile": "Обновить профиль",
    "Customer": "Клиент",
    "Customer Information": "Информация о клиенте",
    "Customers can submit queries through this form": "Клиенты могут отправлять запросы через эту форму",
    "customer_email": "email клиента",
    "customer_name": "имя клиента",
    "customer_phone": "телефон клиента",
    "Subscribers": "Подписчики",
    "Subscribe": "Подписаться",
    "Subscribe Us": "Подписаться на нас",
    "Subscribe to Our Newsletter": "Подписаться на рассылку",
    "Stay update with us and get offer": "Будьте в курсе и получайте предложения",
    "Member since": "Участник с",
    "Member details": "Детали участника",
    "Membership": "Членство",
    "Membership Request Sent.": "Запрос на членство отправлен.",
    "Monthly Package Purchase": "Ежемесячная покупка пакета",
    "Month wise registered users": "Зарегистрированные по месяцам",
    "Month wise visitors": "Посетители по месяцам",
    "Monthly Listing Posts": "Ежемесячные объявления",
    "Identity Number": "Идентификационный номер",
    # ADMIN
    "Admin": "Администратор",
    "Admins": "Администраторы",
    "Super Admin": "Супер-администратор",
    "Add Admin": "Добавить администратора",
    "Edit Admin": "Редактировать администратора",
    "Admin Management": "Управление администраторами",
    "Admin deleted successfully": "Администратор успешно удалён",
    "Admin updated successfully": "Администратор успешно обновлён",
    "New admin added successfully": "Новый администратор успешно добавлен",
    "Admin action required": "Требуется действие администратора",
    "Admin Approval Notice": "Уведомление об одобрении администратора",
    "Admin Earnings": "Доходы администратора",
    "Admin Forms": "Формы администратора",
    "Admin can also create quote request forms for each language": "Администратор может создавать формы запросов для каждого языка",
    "Role": "Роль",
    "Roles": "Роли",
    "Add Role": "Добавить роль",
    "Edit Role": "Редактировать роль",
    "Role Management": "Управление ролями",
    "New role added successfully": "Новая роль успешно добавлена",
    "Permissions": "Разрешения",
    "Permission": "Разрешение",
    "First delete all the admins of this role": "Сначала удалите всех администраторов с этой ролью",
    # VENDOR
    "Vendor": "Поставщик",
    "Vendors": "Поставщики",
    "Add vendor": "Добавить поставщика",
    "Add Vendor Successfully": "Поставщик успешно добавлен",
    "Edit Vendor": "Редактировать поставщика",
    "Vendor Management": "Управление поставщиками",
    "Registered Vendors": "Зарегистрированные поставщики",
    "Vendor Details": "Детали поставщика",
    "Vendor Profile Available": "Профиль поставщика доступен",
    "Vendor username": "Имя пользователя поставщика",
    "Vendor Info": "Информация о поставщике",
    "Select Vendor": "Выбрать поставщика",
    "Contact Vendor": "Связаться с поставщиком",
    "if you do not select any vendor, then this Listing will be listed for Admin": "если поставщик не выбран, объявление будет от администратора",
    "If no vendor is selected, this will be considered as Admin": "Если поставщик не выбран, считается администратором",
    # LISTING
    "Listing": "Объявление",
    "Listings": "Объявления",
    "listings": "объявления",
    "Add Listing": "Добавить объявление",
    "Edit Listing": "Редактировать объявление",
    "All Listings": "Все объявления",
    "Listings Management": "Управление объявлениями",
    "Listing Specifications": "Характеристики объявления",
    "Listing Title": "Название объявления",
    "Listing Messages": "Сообщения объявлений",
    "Listing View": "Просмотр объявления",
    "Listing Enquiry Form": "Форма запроса",
    "Listing Images (Per Listing)": "Изображения (на объявление)",
    "New Listing category added successfully": "Категория объявлений успешно добавлена",
    "Listing deleted successfully": "Объявление успешно удалено",
    "Listing Updated successfully": "Объявление успешно обновлено",
    "Listing Approved successfully": "Объявление успешно одобрено",
    "Listing Rejected successfully": "Объявление успешно отклонено",
    "Listing Show successfully": "Объявление успешно показано",
    "Listing Hide successfully": "Объявление успешно скрыто",
    "Listing Featured successfully": "Объявление успешно выделено",
    "Listing Pending successfully": "Объявление переведено в ожидание",
    "New Listing added successfully": "Новое объявление успешно добавлено",
    "Listing Auto Approval": "Автоодобрение объявлений",
    "Featured Listing Section": "Избранные объявления",
    "Featured Listings": "Избранные объявления",
    "Featured Listing Section Status": "Статус избранных объявлений",
    "Featured Listing Section Title": "Заголовок избранных объявлений",
    "Featured Status": "Статус избранного",
    "Latest Listing Section": "Последние объявления",
    "Latest Listing Section Status": "Статус последних объявлений",
    "Listings limit reached or exceeded": "Лимит объявлений превышен",
    "Listings Left": "Осталось объявлений",
    "Listing (Unlimited)": "Объявления (безлимитно)",
    "Unlimited Listing": "Безлимитные объявления",
    "Images Per Listing (Unlimited)": "Изображений (безлимитно)",
    "Image Per Listing": "Изображений на объявление",
    "Image Per Listings": "Изображений на объявления",
    "Unlimited Listing Image": "Безлимитные изображения",
    "Listing Page Title": "Заголовок страницы объявлений",
    "Business Hours": "Часы работы",
    "Business Hours Updated successfully": "Часы работы обновлены",
    "Business Days": "Рабочие дни",
    "Holiday": "Выходной",
    "Holiday Updated successfully": "Выходной обновлён",
    # CATEGORIES
    "Categories": "Категории",
    "Category": "Категория",
    "Category Name": "Название категории",
    "Category Code": "Код категории",
    "Category Status": "Статус категории",
    "Category Section": "Секция категорий",
    "Category Section Status": "Статус секции категорий",
    "Category Serial Number": "Порядковый номер категории",
    "Add Listing Category": "Добавить категорию объявлений",
    "Edit Listing Category": "Редактировать категорию объявлений",
    "Listing categories deleted successfully": "Категории объявлений удалены",
    "Listing category updated successfully": "Категория объявлений обновлена",
    "category_id": "категория",
    "Category deleted successfully": "Категория успешно удалена",
    "Select Category": "Выбрать категорию",
    "Category Listing Section Title": "Заголовок секции категорий",
    "Search By Category": "Поиск по категории",
    "All Categories": "Все категории",
    "Explore Popular Categories": "Популярные категории",
    # PRODUCTS / SHOP
    "Shop": "Магазин",
    "Product": "Товар",
    "Products": "Товары",
    "Add Product": "Добавить товар",
    "Edit Product": "Редактировать товар",
    "Product Categories": "Категории товаров",
    "Add Product Category": "Добавить категорию товаров",
    "Edit Product Category": "Редактировать категорию товаров",
    "Product Name": "Название товара",
    "Product Details": "Детали товара",
    "Product Image": "Изображение товара",
    "Product Images": "Изображения товара",
    "Product Image Per Product": "Изображение на товар",
    "Product Image Per Product (Unlimited)": "Изображений на товар (безлимитно)",
    "Product Images Per Product": "Изображений на товар",
    "Product Per Listing": "Товаров на объявление",
    "Product Per Listing (Unlimited)": "Товаров на объявление (безлимитно)",
    "Products Per Listing": "Товаров на объявление",
    "Products (Unlimited)": "Товары (безлимитно)",
    "Product Orders": "Заказы товаров",
    "Product Enquiry Form": "Форма запроса товара",
    "Product added into the cart.": "Товар добавлен в корзину.",
    "Product removed successfully": "Товар успешно удалён",
    "New Product added successfully": "Новый товар добавлен",
    "New product category added successfully": "Категория товаров добавлена",
    "New product added successfully": "Новый товар добавлен",
    "Unlimited Product Image": "Безлимитные изображения товаров",
    "Unlimited Products": "Безлимитные товары",
    "Stock": "На складе",
    "Stock Out": "Нет в наличии",
    "Out Of Stock": "Нет в наличии",
    "In Stock": "В наличии",
    "Price": "Цена",
    "Current Price": "Текущая цена",
    "Min Price": "Мин. цена",
    "Max Price": "Макс. цена",
    "Discount": "Скидка",
    "Tax": "Налог",
    "Shipping Charge": "Стоимость доставки",
    "Add Shipping Charge": "Добавить стоимость доставки",
    "Edit Shipping Charge": "Редактировать доставку",
    "New shipping charge added successfully": "Доставка добавлена",
    "Coupon": "Купон",
    "Coupons": "Купоны",
    "Add Coupon": "Добавить купон",
    "Edit Coupon": "Редактировать купон",
    "Coupon Type": "Тип купона",
    "Coupon applied successfully!": "Купон применён!",
    "Coupon applied successfully.": "Купон применён.",
    "Coupon deleted successfully": "Купон удалён",
    "Coupon updated successfully": "Купон обновлён",
    "New coupon added successfully": "Новый купон добавлен",
    "Cart": "Корзина",
    "Cart is Empty": "Корзина пуста",
    "Cart Total": "Итого корзины",
    "Cart Page Title": "Заголовок страницы корзины",
    "Cart updated successfully": "Корзина обновлена",
    "Checkout": "Оформление заказа",
    "Checkout Now": "Оформить сейчас",
    "Checkout Page Title": "Заголовок оформления заказа",
    "Order": "Заказ",
    "Orders": "Заказы",
    "Order Details": "Детали заказа",
    "Order Date": "Дата заказа",
    "Order No.": "Номер заказа",
    "Order Number": "Номер заказа",
    "Order Status": "Статус заказа",
    "Order Summary": "Сводка заказа",
    "Order Now": "Заказать сейчас",
    "Ordered Product": "Заказанный товар",
    "Total": "Итого",
    "Total Orders": "Всего заказов",
    "Total Price": "Общая цена",
    "Total Quantity": "Общее количество",
    "Subtotal": "Подытог",
    "Grand Total": "Общий итог",
    "Paid amount": "Оплачено",
    "Paid Amount": "Оплачено",
    "Invoice": "Счёт",
    "Billing Details": "Платёжные реквизиты",
    "Billing Address": "Платёжный адрес",
    "Shipping Address": "Адрес доставки",
    "Shipping Details": "Детали доставки",
    "Shipping Cost": "Стоимость доставки",
    "Shipping Method": "Способ доставки",
    "Ship to a different address": "Доставить на другой адрес",
    "Same as billing address": "Совпадает с платёжным адресом",
    "Quantity": "Количество",
    "Items": "Товары",
    "Item": "Товар",
    "Amount": "Сумма",
    "amount": "сумма",
    "Cost": "Стоимость",
    "Charge": "Сбор",
    "Charges": "Сборы",
    "Fixed Charge": "Фиксированный сбор",
    "Fixed": "Фиксированный",
    "Free": "Бесплатно",
    "Percentage Charge": "Процентный сбор",
    "Commission": "Комиссия",
    "Commission Amount": "Сумма комиссии",
    "Payment Method": "Способ оплаты",
    "Payment Status": "Статус оплаты",
    "Payment Information": "Информация об оплате",
    "Payment Instructions": "Инструкции по оплате",
    "Payment Proof/Receipt": "Подтверждение оплаты",
    "Payment Gateways": "Платёжные шлюзы",
    "Gateway Name": "Название шлюза",
    "Add Gateway": "Добавить шлюз",
    "Edit Gateway": "Редактировать шлюз",
    "Online Gateways": "Онлайн шлюзы",
    "Offline Gateways": "Офлайн шлюзы",
    "Place Order": "Разместить заказ",
    "Purchase": "Покупка",
    "Buy Now": "Купить сейчас",
    "Buy Plan": "Купить план",
    "Proceed to Checkout": "Перейти к оформлению",
    # BLOG
    "Blog": "Блог",
    "Blogs": "Блоги",
    "Blog Management": "Управление блогом",
    "Add Post": "Добавить запись",
    "Edit Post": "Редактировать запись",
    "Posts": "Записи",
    "All Posts": "Все записи",
    "Recent Posts": "Последние записи",
    "Blog Category": "Категория блога",
    "Add Blog Category": "Добавить категорию блога",
    "Edit Blog Category": "Редактировать категорию блога",
    "Blog categories deleted successfully": "Категории блога удалены",
    "Blog category updated successfully": "Категория блога обновлена",
    "Blog deleted successfully": "Блог удалён",
    "Blog updated successfully": "Блог обновлён",
    "New blog added successfully": "Запись блога добавлена",
    "New blog category added successfully": "Категория блога добавлена",
    "Blog section updated successfully": "Секция блога обновлена",
    "Blog Page Title": "Заголовок страницы блога",
    "Blog Section": "Секция блога",
    "Blog Section Status": "Статус секции блога",
    "Blogs deleted successfully": "Записи блога удалены",
    "All Blog Post": "Все записи блога",
    "Search Blog": "Поиск по блогу",
    "Search Posts": "Поиск записей",
    "Author": "Автор",
    "By": "От",
    "By Admin": "От администратора",
    "Comments": "Комментарии",
    "Comment": "Комментарий",
    "comment": "комментарий",
    # FAQ
    "FAQ": "FAQ",
    "FAQs": "FAQ",
    "FAQ Management": "Управление FAQ",
    "Add FAQ": "Добавить FAQ",
    "Edit FAQ": "Редактировать FAQ",
    "FAQ deleted successfully": "FAQ удалён",
    "FAQ updated successfully": "FAQ обновлён",
    "New faq added successfully": "Новый FAQ добавлен",
    "FAQ Page Title": "Заголовок страницы FAQ",
    "FAQ Per Listing": "FAQ на объявление",
    "FAQs Per Listing": "FAQ на объявление",
    "Faqs (Per Listing)": "FAQ (на объявление)",
    "FAQs Per Listing(Unlimited)": "FAQ на объявление (безлимитно)",
    "FAQ limit reached or exceeded": "Лимит FAQ превышен",
    "FAQs deleted successfully": "FAQ удалены",
    "Unlimited FAQ": "Безлимитные FAQ",
    "Question": "Вопрос",
    "question": "вопрос",
    "Answer": "Ответ",
    "answer": "ответ",
    "Frequently Asked Questions": "Часто задаваемые вопросы",
    "NO FAQ FOUND": "FAQ НЕ НАЙДЕН",
    "No Faq Found": "FAQ не найден",
    # FEATURES
    "Features": "Особенности",
    "Feature": "Особенность",
    "Add Feature": "Добавить особенность",
    "Feature section updated successfully": "Секция особенностей обновлена",
    "Feature deleted successfully": "Особенность удалена",
    "Feature Updated successfully": "Особенность обновлена",
    "Feature Per Listing": "Особенностей на объявление",
    "Features Per Listing": "Особенностей на объявление",
    "Features  (Per Listing)": "Особенности (на объявление)",
    "Feature Per Listing (Unlimited)": "Особенностей (безлимитно)",
    "Unlimited Feature": "Безлимитные особенности",
    "Custom Features": "Пользовательские особенности",
    "More Features": "Больше особенностей",
    "NO FEATURE FOUND": "ОСОБЕННОСТИ НЕ НАЙДЕНЫ",
    "No Feature Found": "Особенности не найдены",
    # AMENITIES
    "Amenities": "Удобства",
    "Amenitie Per Listing": "Удобств на объявление",
    "Amenities Per Listing": "Удобства на объявление",
    "Amenities (Per Listing)": "Удобства (на объявление)",
    "Amenities Per Listing(Unlimited)": "Удобства (безлимитно)",
    "Add Amenitie": "Добавить удобство",
    "Edit Amenitie": "Редактировать удобство",
    "Aminite deleted successfully": "Удобство удалено",
    "Aminite stored successfully": "Удобство сохранено",
    "Aminite updated successfully": "Удобство обновлено",
    "Aminities updated successfully": "Удобства обновлены",
    "Unlimited Amenities": "Безлимитные удобства",
    # PACKAGES
    "Packages": "Пакеты",
    "Package": "Пакет",
    "Add Package": "Добавить пакет",
    "Edit package": "Редактировать пакет",
    "Current Package": "Текущий пакет",
    "Next Package": "Следующий пакет",
    "Add Current Package": "Добавить текущий пакет",
    "Add Next Package": "Добавить следующий пакет",
    "Change Current Package": "Изменить текущий пакет",
    "Change Next Package": "Изменить следующий пакет",
    "Current Package changed successfully": "Текущий пакет изменён",
    "Next Package changed successfully": "Следующий пакет изменён",
    "Current Package has been added successfully": "Текущий пакет добавлен",
    "Next Package has been added successfully": "Следующий пакет добавлен",
    "Current Package removed successfully": "Текущий пакет удалён",
    "Next Package removed successfully": "Следующий пакет удалён",
    "Term": "Срок",
    "term": "срок",
    "Lifetime": "Пожизненно",
    "lifetime": "пожизненно",
    "Monthly": "Ежемесячно",
    "monthly": "ежемесячно",
    "Yearly": "Ежегодно",
    "Trial": "Пробный",
    "Test Package": "Тестовый пакет",
    "Pricing": "Цены",
    "Pricing Filter": "Фильтр цен",
    "Choose a Package term": "Выберите срок пакета",
    "If you purchase this package": "При покупке этого пакета",
    "If price is 0 , than it will appear as free": "Цена 0 — бесплатно",
    "NO PACKAGE FOUND": "ПАКЕТОВ НЕ НАЙДЕНО",
    "Details & Package": "Детали и пакет",
    "Extend": "Продлить",
    "If you delete this package, all memberships under this package will be deleted": "При удалении пакета все членства будут удалены",
    # LOCATIONS
    "Countries": "Страны",
    "Country": "Страна",
    "country": "страна",
    "Country Name": "Название страны",
    "Add Country": "Добавить страну",
    "Edit Country": "Редактировать страну",
    "Country deleted successfully": "Страна удалена",
    "Country stored successfully": "Страна сохранена",
    "Country updated successfully": "Страна обновлена",
    "Enter Country": "Введите страну",
    "Enter Country Name": "Введите название страны",
    "Select Country": "Выбрать страну",
    "State": "Область",
    "States": "Области",
    "Add State": "Добавить область",
    "Edit State": "Редактировать область",
    "Enter State": "Введите область",
    "Enter State Name": "Введите название области",
    "Select State": "Выбрать область",
    "City": "Город",
    "Cities": "Города",
    "city": "город",
    "Add City": "Добавить город",
    "Edit City": "Редактировать город",
    "City deleted successfully": "Город удалён",
    "City updated successfully": "Город обновлён",
    "Enter City": "Введите город",
    "Enter City Name": "Введите название города",
    "Select City": "Выбрать город",
    "Select State/City": "Выбрать Область/Город",
    "Location Section": "Секция местоположений",
    "Location Section Status": "Статус секции",
    "Location section updated successfully": "Секция местоположений обновлена",
    "Search By Location": "Поиск по местоположению",
    "Search specific location": "Поиск местоположения",
    "Use current location": "Текущее местоположение",
    "Current location": "Текущее местоположение",
    "Enter location": "Введите местоположение",
    "Enter Location": "Введите местоположение",
    "Map": "Карта",
    "Google Map": "Google Карта",
    "Google Map API": "Google Map API",
    # HOME PAGE
    "Home Page": "Главная страница",
    "Hero Section": "Главный блок",
    "Call To Action Section": "Секция CTA",
    "Call To Action Section Status": "Статус секции CTA",
    "Call to action section updated successfully": "Секция CTA обновлена",
    "Counter Section": "Секция счётчиков",
    "Counter Informations": "Счётчики",
    "Counter Section Status": "Статус счётчиков",
    "Add Counter Information": "Добавить счётчик",
    "Edit Counter Information": "Редактировать счётчик",
    "Testimonials": "Отзывы",
    "Testimonial": "Отзыв",
    "Add Testimonial": "Добавить отзыв",
    "Edit Testimonial": "Редактировать отзыв",
    "New testimonial added successfully": "Отзыв добавлен",
    "Client Name": "Имя клиента",
    "Client Image": "Фото клиента",
    "Client Comment": "Комментарий",
    "Client Occupation": "Профессия",
    "No Testimonial Found": "Отзывы не найдены",
    "Work Process": "Рабочий процесс",
    "Add Work Process": "Добавить процесс",
    "Edit Work Process": "Редактировать процесс",
    "New work process added successfully": "Процесс добавлен",
    "How It Works": "Как это работает",
    "No Work Process Found": "Процесс не найден",
    "Information": "Информация",
    "Information deleted successfully": "Информация удалена",
    "Information stored successfully": "Информация сохранена",
    "Information updated successfully": "Информация обновлена",
    "No Information Found": "Информация не найдена",
    "What's Included": "Что включено",
    "Services": "Услуги",
    # FOOTER
    "Footer": "Подвал",
    "Footer logo updated successfully": "Логотип подвала обновлён",
    "Quick Links": "Быстрые ссылки",
    "Add Quick Link": "Добавить ссылку",
    "Edit Quick Link": "Редактировать ссылку",
    "New quick link added successfully": "Ссылка добавлена",
    "Copyright Text": "Текст авторских прав",
    "Useful Links": "Полезные ссылки",
    "Follow Us": "Мы в соцсетях",
    "Our Address": "Наш адрес",
    # CUSTOM PAGES
    "Custom Pages": "Пользовательские страницы",
    "Custom Page": "Пользовательская страница",
    "Add Page": "Добавить страницу",
    "Edit Page": "Редактировать страницу",
    "New page added successfully": "Страница добавлена",
    # CONTACT
    "Contact": "Контакты",
    "Contact Us": "Связаться с нами",
    "Contact Page": "Страница контактов",
    "Contact Page Title": "Заголовок контактов",
    "Contact Information": "Контактная информация",
    "Contact Now": "Связаться сейчас",
    "Contact Number": "Контактный номер",
    "contact_number": "контактный номер",
    "Enter Contact Number": "Введите контактный номер",
    "email_address": "адрес эл. почты",
    "A contact request was sent successfully": "Запрос отправлен",
    "Message": "Сообщение",
    "Message sent successfully": "Сообщение отправлено",
    "Message Sent Successfully": "Сообщение отправлено",
    "Message Information": "Информация о сообщении",
    "Messages": "Сообщения",
    "Message deleted successfully": "Сообщение удалено",
    "Message Submitted At": "Сообщение отправлено",
    "No Message Found": "Сообщения не найдены",
    "Submit Message": "Отправить сообщение",
    "Write Your Message": "Напишите сообщение",
    "Subject": "Тема",
    "Enter Subject": "Введите тему",
    # FORMS
    "Forms": "Формы",
    "Form Builder": "Конструктор форм",
    "Form Type": "Тип формы",
    "Form Types Guide": "Типы форм",
    "Form Guide": "Руководство по формам",
    "Form Inputs": "Поля формы",
    "Add Form": "Добавить форму",
    "Edit Form": "Редактировать форму",
    "Form deleted successfully": "Форма удалена",
    "Form updated successfully": "Форма обновлена",
    "Input Fields": "Поля ввода",
    "Input Type": "Тип ввода",
    "Input Field Type": "Тип поля",
    "Create Input Field": "Создать поле",
    "Edit Input Field": "Редактировать поле",
    "Label": "Метка",
    "Placeholder": "Заполнитель",
    "Required": "Обязательно",
    "Options": "Варианты",
    "Add Option": "Добавить вариант",
    "Enter Option": "Введите вариант",
    "Checkbox": "Флажок",
    "Radio": "Переключатель",
    "Textarea": "Текстовая область",
    "Text": "Текст",
    "text": "текст",
    "Number": "Число",
    "Datepicker": "Выбор даты",
    "Table Reservation": "Бронирование",
    "Quote Request": "Запрос предложения",
    "Claim Request": "Запрос на заявление",
    "Enquiry Form": "Форма запроса",
    "Claim Request Form": "Форма заявления",
    "Each vendor can have only one quote request form per language": "Один поставщик — одна форма запроса на язык",
    "Each language should have only one claim request form": "Один язык — одна форма заявления",
    "Leave it blank for admin's form": "Оставьте пустым для формы админа",
    "Global": "Глобальный",
    "Local": "Локальный",
    "A form of this type already exists for this scope": "Форма этого типа уже существует",
    "Based on your selection, some input fields will be shown or hidden automatically": "Поля будут показаны/скрыты в зависимости от выбора",
    # SUPPORT TICKETS
    "Support Tickets": "Тикеты поддержки",
    "Support Ticket Details": "Детали тикета",
    "Ticket": "Тикет",
    "Tickets": "Тикеты",
    "All Tickets": "Все тикеты",
    "Closed Tickets": "Закрытые тикеты",
    "Total Tickets": "Всего тикетов",
    "Add a Ticket": "Добавить тикет",
    "Add a ticket": "Добавить тикет",
    "Submit a Ticket": "Отправить тикет",
    "Create a Support Ticket": "Создать тикет",
    "Ticket ID": "ID тикета",
    "Ticket has been submitted successfully": "Тикет отправлен",
    "Close Ticket": "Закрыть тикет",
    "Add Stuff to this support ticket successfully": "Участник добавлен в тикет",
    "Replies": "Ответы",
    "Reply": "Ответить",
    # ADVERTISEMENTS
    "Advertisements": "Реклама",
    "Advertisement": "Реклама",
    "Add Advertisement": "Добавить рекламу",
    "Edit Advertisement": "Редактировать рекламу",
    "Ad Type": "Тип рекламы",
    "Ad Slot": "Слот рекламы",
    "ad_type": "тип рекламы",
    "Advertisement deleted successfully": "Реклама удалена",
    "Advertisement Resolution": "Разрешение рекламы",
    "Advertisements deleted successfully": "Рекламы удалены",
    "Advertisement Type": "Тип рекламы",
    "Advertisement updated successfully": "Реклама обновлена",
    "Advertise settings updated successfully": "Настройки рекламы обновлены",
    "New advertisement added successfully": "Реклама добавлена",
    "All Advertisements": "Вся реклама",
    # POPUPS
    "Announcement Popups": "Всплывающие окна",
    "Popup": "Всплывающее окно",
    "Add Popup": "Добавить окно",
    "New popup added successfully": "Окно добавлено",
    "All activated popups will be appear in UI according to serial number.": "Активные окна отображаются по порядковому номеру.",
    "If there are multiple active popups, then popups will be shown in UI according to serial number.": "Несколько окон показываются по порядковому номеру.",
    # SOCIAL
    "Social Media": "Социальные сети",
    "Social Link": "Социальная ссылка",
    "Social Links": "Социальные ссылки",
    "Add Social Media": "Добавить соцсеть",
    "Edit Social Media": "Редактировать соцсеть",
    "New social media added successfully": "Соцсеть добавлена",
    "Social Links Per Listing": "Соцссылок на объявление",
    "Social Links Per Listing(Unlimited)": "Соцссылок (безлимитно)",
    "Unlimited Social Links": "Безлимитные соцссылки",
    "Facebook": "Facebook",
    "Twitter": "Twitter",
    "Linkedin": "LinkedIn",
    "WhatsApp": "WhatsApp",
    "Telegram": "Telegram",
    "Messenger": "Messenger",
    "Tawk.To": "Tawk.To",
    # SETTINGS
    "Basic Settings": "Основные настройки",
    "General Settings": "Общие настройки",
    "General settings update Successfully": "Общие настройки обновлены",
    "Email Settings": "Настройки почты",
    "Email Status": "Статус почты",
    "Email status updated successfully": "Статус почты обновлён",
    "Mail": "Почта",
    "Mail From Admin": "Письмо от админа",
    "Mail To Admin": "Письмо админу",
    "Mail Body": "Тело письма",
    "Mail Subject": "Тема письма",
    "Mail Templates": "Шаблоны писем",
    "Mail template updated successfully": "Шаблон письма обновлён",
    "Mail info updated successfully": "Настройки почты обновлены",
    "Mail could not be sent": "Письмо не отправлено",
    "Mail has been sent to all the subscribers": "Письмо отправлено подписчикам",
    "Mail Type": "Тип письма",
    "A mail has been sent to your email address": "Письмо отправлено на ваш email",
    "A verification mail has been sent to your email address": "Письмо подтверждения отправлено",
    "Email Verificaiton": "Подтверждение почты",
    "Email Verification Link": "Ссылка подтверждения",
    "From Email": "От (Email)",
    "From Name": "От (Имя)",
    "from_mail": "от (почта)",
    "from_name": "от (имя)",
    "Logo & Image": "Логотип и изображения",
    "Logo updated successfully": "Логотип обновлён",
    "Favicon updated successfully": "Фавикон обновлён",
    "Image updated successfully": "Изображение обновлено",
    "Appearance": "Внешний вид",
    "Appearance updated successfully": "Внешний вид обновлён",
    "Theme": "Тема",
    "Breadcrumb": "Хлебные крошки",
    "Breadcrumb updated successfully": "Хлебные крошки обновлены",
    "Currency": "Валюта",
    "Currency updated successfully": "Валюта обновлена",
    "Base Currency Symbol": "Символ валюты",
    "Base Currency Symbol Position": "Позиция символа",
    "Base Currency Text": "Текст валюты",
    "Base Currency Text Position": "Позиция текста",
    "Base Currency Rate": "Курс валюты",
    "Language": "Язык",
    "Language Management": "Управление языками",
    "Language added successfully": "Язык добавлен",
    "Language deleted successfully": "Язык удалён",
    "Language updated successfully": "Язык обновлён",
    "Direction": "Направление",
    "direction": "направление",
    "Code": "Код",
    "code": "код",
    "Make Default": "Сделать по умолчанию",
    "Default language cannot be delete": "Язык по умолчанию нельзя удалить",
    "Keywords": "Ключевые слова",
    "Keyword": "Ключевое слово",
    "keyword": "ключевое слово",
    "Keywords of": "Ключевые слова",
    "Keywords updated successfully": "Ключевые слова обновлены",
    "Edit Keyword": "Редактировать ключевое слово",
    "Edit Dashboard Keyword": "Ред. ключевое слово панели",
    "Edit Front Keyword": "Ред. ключевое слово фронта",
    "Add Keyword for admin": "Добавить слово для админки",
    "Add Keyword for front": "Добавить слово для фронта",
    "Add New Keyword for dashboard": "Новое слово для панели",
    "Add New Keyword for front": "Новое слово для фронта",
    "A new keyword successfully": "Новое слово успешно",
    "Enter Keyword": "Введите слово",
    "language": "язык",
    "language_id": "язык",
    "Meaning": "Значение",
    "Translation": "Перевод",
    "SEO": "SEO",
    "Meta Description": "Мета-описание",
    "Meta Keywords": "Мета-слова",
    "Meta Description For Home Page": "Мета-описание Главной",
    "Meta Description For About Us Page": "Мета-описание О нас",
    "Meta Description For Blog Page": "Мета-описание Блога",
    "Meta Description For Contact Page": "Мета-описание Контактов",
    "Meta Description For FAQ Page": "Мета-описание FAQ",
    "Meta Description For Listings Page": "Мета-описание Объявлений",
    "Meta Description For Pricing Page": "Мета-описание Цен",
    "Meta Description For Products Page": "Мета-описание Товаров",
    "Meta Description For Vendors Page": "Мета-описание Поставщиков",
    "Meta Keywords For Home Page": "Мета-слова Главной",
    "Meta Keywords For About Us Page": "Мета-слова О нас",
    "Meta Keywords For Blog Page": "Мета-слова Блога",
    "Meta Keywords For Contact Page": "Мета-слова Контактов",
    "Meta Keywords For FAQ Page": "Мета-слова FAQ",
    "Meta Keywords For Listings Page": "Мета-слова Объявлений",
    "Meta Keywords For Pricing Page": "Мета-слова Цен",
    "Meta Keywords For Products Page": "Мета-слова Товаров",
    "Meta Keywords For Vendors Page": "Мета-слова Поставщиков",
    "Meta Description For Customer Login Page": "Мета-описание Входа",
    "Meta Description For Customer Signup Page": "Мета-описание Регистрации",
    "Meta Description For Customer Forget Password Page": "Мета-описание Забытого пароля",
    "Meta Description For Vendor Login Page": "Мета-описание Входа поставщика",
    "Meta Description For Vendor Signup Page": "Мета-описание Регистрации поставщика",
    "Meta Description For Vendor Forget Password Page": "Мета-описание Забытого пароля поставщика",
    "Meta Keywords For Customer Login Page": "Мета-слова Входа",
    "Meta Keywords For Customer Signup Page": "Мета-слова Регистрации",
    "Meta Keywords For Customer Forget Password Page": "Мета-слова Забытого пароля",
    "Meta Keywords For Vendor Login Page": "Мета-слова Входа поставщика",
    "Meta Keywords For Vendor Signup Page": "Мета-слова Регистрации поставщика",
    "Meta Keywords For Vendor Forget Password Page": "Мета-слова Забытого пароля поставщика",
    "Page Headings": "Заголовки страниц",
    "Plugins": "Плагины",
    "Manage Plugins": "Управление плагинами",
    "Update necessary plugins": "Обновить плагины",
    "Google Recaptcha": "Google Recaptcha",
    "Maintenance Mode": "Режим обслуживания",
    "Maintenance Status": "Статус обслуживания",
    "Maintenance Message": "Сообщение обслуживания",
    "Maintenance Info updated successfully": "Обслуживание обновлено",
    "maintenance_msg": "сообщение обслуживания",
    "Cookie Alert": "Уведомление о cookie",
    "Cookie Alert Status": "Статус cookie",
    "Cookie Alert Text": "Текст cookie",
    "Cookie Alert Button Text": "Текст кнопки cookie",
    "Cookie alert info updated successfully": "Cookie обновлены",
    "cookie_alert_text": "текст cookie",
    "Push Notification": "Push-уведомление",
    "Firebase": "Firebase",
    "Upload Firebase Admin JSON": "Загрузить Firebase Admin JSON",
    "Mobile Interface": "Мобильный интерфейс",
    "Mobile App Settings": "Настройки мобильного приложения",
    "Cron Job Command": "Команда Cron Job",
    # CLAIM
    "Claim": "Заявить",
    "Claimed": "Заявлено",
    "Claim Listing": "Заявить объявление",
    "Claim Request": "Запрос на заявление",
    "Claim Requests": "Запросы на заявление",
    "Claim Request Information": "Информация о запросе",
    "Claim Request Details": "Детали запроса",
    "Claim Request Workflow": "Процесс запроса",
    "Claim Status": "Статус заявления",
    "Claim Link": "Ссылка для заявления",
    "A unique claim link is automatically generated": "Уникальная ссылка генерируется автоматически",
    "Link has a configurable expiration time": "Ссылка с настраиваемым сроком",
    "Click the claim link": "Нажмите на ссылку",
    "Approve Claim": "Одобрить заявление",
    "Needs Admin Approval": "Требуется одобрение",
    "Claim status will automatically update to Fulfilled": "Статус обновится на Выполнено",
    "New claim requests start with pending status": "Новые запросы в статусе Ожидание",
    "Already claimed, awaiting fulfillment": "Уже заявлено, ожидает выполнения",
    "Fulfilled Status": "Статус выполнения",
    "Decision Pending": "Решение ожидается",
    # WITHDRAW
    "Withdraw": "Вывод средств",
    "Withdrawals": "Выводы средств",
    "Withdraw Request": "Запрос на вывод",
    "Withdraw Requests": "Запросы на вывод",
    "Add Payment Method": "Добавить способ оплаты",
    "Edit Payment Method": "Редактировать способ",
    "Method": "Способ",
    "Method Name": "Название способа",
    "Minimum Limit": "Мин. лимит",
    "Maximum Limit": "Макс. лимит",
    "Minimum Spend": "Мин. траты",
    "Min Limit": "Мин. лимит",
    "Max Limit": "Макс. лимит",
    "min_limit": "мин. лимит",
    "max_limit": "макс. лимит",
    # PAYMENT GATEWAYS
    "PayPal": "PayPal",
    "Stripe": "Citibank",
    "Paystack": "Paystack",
    "Paytm": "Paytm",
    "Instamojo": "Instamojo",
    "Flutterwave": "Flutterwave",
    "Mollie": "Mollie",
    "Razorpay": "Razorpay",
    "MercadoPago": "MercadoPago",
    "Authorize.Net": "Authorize.Net",
    "Authorize.net": "Authorize.net",
    "Iyzico": "Iyzico",
    "Midtrans": "Midtrans",
    "MyFatoorah": "MyFatoorah",
    "Myfatoorah": "Myfatoorah",
    "Offline Payment": "Офлайн оплата",
    "New offline payment gateway added successfully": "Офлайн шлюз добавлен",
    "Test Mode": "Тестовый режим",
    "Sandbox": "Песочница",
    "API Key": "API ключ",
    "Api Key": "API ключ",
    "Secret Key": "Секретный ключ",
    "Public Key": "Публичный ключ",
    "Client ID": "Client ID",
    "Client Secret": "Client Secret",
    "Merchant Id": "Merchant ID",
    "App ID": "App ID",
    "App Secret": "App Secret",
    "Token": "Токен",
    "Encryption": "Шифрование",
    "encryption": "шифрование",
    "Server Key": "Ключ сервера",
    "Auth Token": "Токен аутентификации",
    "API Login ID": "API Login ID",
    "API Endpoint": "API Endpoint",
    "Transaction Key": "Ключ транзакции",
    "Bypass Token": "Токен обхода",
    "Cancel URL": "URL отмены",
    "Redirect URL": "URL перенаправления",
    "Instructions": "Инструкции",
    "Gateway Instructions": "Инструкции шлюза",
    "For offline payments, you must manually verify and approve the payment from Subscription Log": "Офлайн платежи проверяются вручную в журнале подписок",
    # SUBSCRIPTION
    "Subscription": "Подписка",
    "Subscription Log": "Журнал подписок",
    "Change payment status to Success": "Статус оплаты → Успешно",
    "Find the payment record": "Найти запись платежа",
    # MENU BUILDER
    "Menu Builder": "Конструктор меню",
    "Menu": "Меню",
    "Menus": "Меню",
    "Edit Menu": "Редактировать меню",
    "Add To Menus": "Добавить в меню",
    "Built-In Menus": "Встроенные меню",
    "Custom Menus": "Пользовательские меню",
    "Menu Name": "Название меню",
    "Menu URL": "URL меню",
    # ERROR & VALIDATION
    "Error": "Ошибка",
    "Warning": "Предупреждение",
    "Alert": "Внимание",
    "Success": "Успех",
    "Info": "Информация",
    "Notice": "Уведомление",
    "404 Error Page Title": "Заголовок 404",
    "404 not found": "404 не найдено",
    "The page you are looking for might have been moved, renamed, or might never existed.": "Страница не найдена.",
    "Validation": "Валидация",
    "Please fill all fields": "Заполните все поля",
    "Please enter a valid email": "Введите корректный email",
    "Please enter a valid email address.": "Введите корректный email.",
    "Passwords do not match": "Пароли не совпадают",
    "Please enter your name": "Введите имя",
    "Please enter your email": "Введите email",
    "Please enter your phone": "Введите телефон",
    "Please enter your message": "Введите сообщение",
    "Please fill all billing details": "Заполните платёжные реквизиты",
    "Please select a payment method": "Выберите способ оплаты",
    "Please select a rating": "Выберите рейтинг",
    "Please write your review": "Напишите отзыв",
    "Review must be at least 10 characters": "Отзыв от 10 символов",
    "Review submitted successfully!": "Отзыв отправлен!",
    "Failed to submit review": "Ошибка отправки отзыва",
    "Please login first": "Сначала войдите",
    "Please login to continue": "Войдите для продолжения",
    "Please login": "Войдите",
    "Please login first to claim this listing": "Войдите чтобы заявить",
    "An error occurred": "Произошла ошибка",
    "Sorry, an error has occured!": "Произошла ошибка!",
    "Something went wrong!": "Что-то пошло не так!",
    "Invalid request!": "Неверный запрос!",
    "Unauthorized": "Не авторизован",
    "Forbidden": "Доступ запрещён",
    "Not found": "Не найдено",
    "Server Error": "Ошибка сервера",
    # NOTIFICATIONS
    "Notifications": "Уведомления",
    "Notification": "Уведомление",
    "New Notification": "Новое уведомление",
    # ABOUT
    "About": "О нас",
    "About Us": "О нас",
    "About Us Page Title": "Заголовок О нас",
    "About section updated successfully": "Секция О нас обновлена",
    "About Company": "О компании",
    "about_company": "о компании",
    # LOGIN / REGISTER
    "Login with Facebook": "Войти через Facebook",
    "Login with Google": "Войти через Google",
    "Login via Facebook": "Вход через Facebook",
    "Login via Google": "Вход через Google",
    "Login Status": "Статус входа",
    "Login Url": "URL входа",
    "Register": "Регистрация",
    "forgot password": "забыли пароль",
    "Forgot Password": "Забыли пароль",
    "Reset Password": "Сбросить пароль",
    "Send me a recovery link": "Отправить ссылку восстановления",
    "Logged out successfully": "Выход выполнен",
    "Login successful!": "Вход выполнен!",
    "Incorrect username or password": "Неверное имя или пароль",
    "Sorry, your account has been deactivated": "Аккаунт деактивирован",
    "This email is already registered.": "Email уже зарегистрирован.",
    "This username is already taken.": "Имя пользователя занято.",
    "This username is not allowed.": "Имя пользователя не разрешено.",
    "Already have an account": "Уже есть аккаунт",
    "don't have an account": "нет аккаунта",
    "to Login": "Войти",
    "to Signup": "Зарегистрироваться",
    "Sign up successfully completed.Please Login Now": "Регистрация завершена. Войдите.",
    "Please verify your email address": "Подтвердите email",
    "Password updated successfully": "Пароль обновлён",
    # GENERAL
    "Search by Title": "Поиск по названию",
    "Search By Title": "Поиск по названию",
    "Find Now": "Найти",
    "Apply Filters": "Применить фильтры",
    "Apply": "Применить",
    "Results": "Результаты",
    "Showing": "Показано",
    "Found": "Найдено",
    "Unknown": "Неизвестно",
    "Unlimited": "Безлимитно",
    "Details": "Детали",
    "Detail": "Деталь",
    "Description": "Описание",
    "description": "описание",
    "Content": "Содержимое",
    "content": "содержимое",
    "Configuration Rules": "Правила конфигурации",
    "Configure Expiration": "Настроить истечение",
    "Title": "Название",
    "title": "название",
    "Subtitle": "Подзаголовок",
    "subtitle": "подзаголовок",
    "Summary": "Сводка",
    "Type": "Тип",
    "type": "тип",
    "Value": "Значение",
    "value": "значение",
    "Serial Number": "Порядковый номер",
    "serial_number": "порядковый номер",
    "Order Number": "Номер заказа",
    "order_number": "номер заказа",
    "Order": "Порядок",
    "order": "порядок",
    "Rating": "Рейтинг",
    "rating": "рейтинг",
    "Ratings": "Рейтинги",
    "Reviews": "Отзывы",
    "Review": "Отзыв",
    "Write a Review": "Написать отзыв",
    "Your Review": "Ваш отзыв",
    "Your Rating": "Ваш рейтинг",
    "Submit Review": "Отправить отзыв",
    "Customer Review": "Отзыв клиента",
    "Read More": "Читать далее",
    "Read more": "Читать далее",
    "Read Less": "Свернуть",
    "Show More": "Показать больше",
    "Show more": "Показать больше",
    "Show Less": "Показать меньше",
    "Show less": "Показать меньше",
    "More Details": "Подробнее",
    "Click Here": "Нажмите здесь",
    "Go Here": "Перейти",
    "Search Wishlist": "Поиск в избранном",
    "Search orders": "Поиск заказов",
    "Filter Price": "Фильтр цены",
    "Price : High to Low": "Цена: по убыванию",
    "Price : Low to High": "Цена: по возрастанию",
    "Date : Newest on top": "Дата: сначала новые",
    "Date : Oldest on top": "Дата: сначала старые",
    "High to Low": "По убыванию",
    "Low to High": "По возрастанию",
    "Newest": "Новые",
    "Oldest": "Старые",
    "Sort By": "Сортировка",
    "Grid View": "Сетка",
    "List View": "Список",
    "Gird": "Сетка",
    # CHARGES
    "Add Charge": "Добавить сбор",
    "Edit Charge": "Редактировать сбор",
    "Charge deleted successfully": "Сбор удалён",
    "Charge stored successfully": "Сбор сохранён",
    "Charge updated successfully": "Сбор обновлён",
    # FEATURE LISTING
    "Feature It": "Выделить",
    "Feature Active Date": "Дата активации",
    "Feature Expiry Date": "Дата истечения",
    "How Many Days Active": "Дней активности",
    # WISHLIST
    "Wishlist": "Избранное",
    "Wishlists": "Избранное",
    "My Wishlist": "Моё избранное",
    "My Wishlists": "Моё избранное",
    "Wishlist Items": "Элементы избранного",
    "Save to Wishlist": "В избранное",
    "Added to your wishlist successfully": "Добавлено в избранное",
    "Removed From wishlist successfully": "Удалено из избранного",
    "NO WISHLIST FOUND": "ИЗБРАННОЕ НЕ НАЙДЕНО",
    "NO WISHLIST ITEM FOUND": "ЭЛЕМЕНТЫ НЕ НАЙДЕНЫ",
    "Your wishlist is empty": "Избранное пусто",
    "Listing Wishlists": "Избранные объявления",
    "Promos": "Акции",
    "Available": "Доступно",
    "Available Now": "Доступно сейчас",
    "Avilable Now": "Доступно сейчас",
    "Thank you": "Спасибо",
    "I'm Looking for": "Я ищу",
    "Share your experience...": "Поделитесь опытом...",
    "Enter name": "Введите имя",
    "Enter Name": "Введите имя",
    "Enter phone number": "Введите телефон",
    "Enter city": "Введите город",
    "Enter state": "Введите область",
    "Enter zip code": "Введите индекс",
    "Enter country": "Введите страну",
    "Enter address": "Введите адрес",
    "Enter your name": "Введите ваше имя",
    "Enter your phone": "Введите ваш телефон",
    "Enter your state": "Введите вашу область",
    "Enter your address": "Введите ваш адрес",
    "Enter postcode": "Введите индекс",
    "Enter email": "Введите email",
    "Enter Email": "Введите email",
    "Enter password": "Введите пароль",
    "Enter username": "Введите имя пользователя",
    "Enter Full Name": "Введите полное имя",
    "Enter Your Full Name": "Введите ваше полное имя",
    "Enter Your Email": "Введите ваш email",
    "Enter Your Email Address": "Введите ваш email",
    "Enter Title": "Введите название",
    "Enter Text": "Введите текст",
    "Enter Short Text": "Введите короткий текст",
    "Enter Summary": "Введите сводку",
    "Enter Subtitle": "Введите подзаголовок",
    "Enter Price": "Введите цену",
    "Enter Product Name": "Введите название товара",
    "Enter Shop Location": "Введите местоположение",
    "Enter vendor name": "Введите имя поставщика",
    "Enter Amount": "Введите сумму",
    "Enter Details": "Введите детали",
    "Enter Phone": "Введите телефон",
    "Enter Subject": "Введите тему",
    "Enter URL": "Введите URL",
    "Enter Location": "Введите местоположение",
    "Enter location": "Введите местоположение",
    "Enter Coupon Code": "Введите код купона",
    "Enter Rating": "Введите рейтинг",
    "Enter Min Price": "Введите мин. цену",
    "Enter Max Price": "Введите макс. цену",
    "Enter Website Title": "Введите название сайта",
    "Enter Start Date": "Введите дату начала",
    "Enter End Date": "Введите дату окончания",
    "Enter Days": "Введите дни",
    "Enter number of days": "Введите количество дней",
    "Enter Video URL": "Введите URL видео",
    "Enter Your video url": "Введите URL видео",
    "Enter Contact Number": "Введите контактный номер",
    "Enter Contact Mail": "Введите контактную почту",
    "Enter Address": "Введите адрес",
    "Enter City": "Введите город",
    "Enter City Name": "Введите название города",
    "Enter State": "Введите область",
    "Enter State Name": "Введите название области",
    "Enter Country": "Введите страну",
    "Enter Country Name": "Введите название страны",
    "Enter Zip Code": "Введите индекс",
    "Enter Latitude": "Введите широту",
    "Enter Longitude": "Введите долготу",
    "Enter Serial Number": "Введите порядковый номер",
    "Enter Category Serial Number": "Введите порядковый номер категории",
    "Category Serial Number": "Порядковый номер категории",
    "Enter Author Name": "Введите имя автора",
    "Enter Client Name": "Введите имя клиента",
    "Enter Client Occupation": "Введите профессию",
    "Enter Client Comment": "Введите комментарий",
    "Enter FAQ Serial Number": "Введите номер FAQ",
    "Enter Work Process Serial Number": "Введите номер процесса",
    "Enter Work Process Title": "Введите название процесса",
    "Image Size 80x80": "Размер 80x80",
    "Image Size 600x400": "Размер 600x400",
    "JPG, PNG, JPEG, GIF, SVG images are allowed": "Разрешены JPG, PNG, JPEG, GIF, SVG",
    "only .zip file is allowed.": "только .zip файлы",
    "Only .zip file is allowed.": "Только .zip файлы",
    "Only .zip file is allowed": "Только .zip файлы",
    "Max upload size 5 MB": "Макс. размер 5 МБ",
    "Max upload size is 20 MB": "Макс. размер 20 МБ",
    "Maximum Size": "Макс. размер",
    "Maximum Size of Uploaded File": "Макс. размер файла",
    "File Size": "Размер файла",
    "Enter File Size": "Введите размер файла",
    "Download Link": "Ссылка для скачивания",
    "Enter Download Link": "Введите ссылку",
    "Additional Reference": "Дополнительная ссылка",
    "Additional Reference(Optional)": "Дополнительная ссылка (необяз.)",
    "Link to View Order Details": "Ссылка на детали заказа",
    "Modified by Admin": "Изменено админом",
    "modified by Admin": "изменено админом",
    "Guest User": "Гость",
    "Select date": "Выберите дату",
    "Select time": "Выберите время",
    "Crop Image": "Обрезать изображение",
    "Industry Type": "Тип отрасли",
    "Name of The Customer": "Имя клиента",
    "Name of Listing": "Название объявления",
    "Name of Product": "Название товара",
    "Name of enquirer": "Имя запрашивающего",
    "Email address of enquirer": "Email запрашивающего",
    "Message of enquirer": "Сообщение запрашивающего",
    "Digital Product": "Цифровой товар",
    "digital": "цифровой",
    "Both (Marketplace & Listing)": "Оба (Маркетплейс и Объявления)",
    "Marketplace": "Маркетплейс",
    "gender": "пол",
    "age": "возраст",
    "occupation": "профессия",
    "Save Place": "Сохранить место",
    "Please verify that you are not a robot.": "Подтвердите, что вы не робот.",
    "Captcha error! Try again later or contact site admin.": "Ошибка капчи! Попробуйте позже.",
    "Expiration Reminder": "Напоминание об истечении",
    "expiration_reminder": "напоминание об истечении",
    "Terms": "Условия",
    "terms": "условия",
    # AI
    "AI Image Limit": "Лимит изображений AI",
    "AI Token Limit": "Лимит токенов AI",
    "AI Content & Image Generator": "Генератор контента AI",
    "AI Engine": "Движок AI",
    "OpenAI": "OpenAI",
    "Gemini": "Gemini",
    # MOBILE APP
    "Mobile App Settings": "Настройки мобильного приложения",
    "For mobile app display": "Для мобильного приложения",
    "This image will be used in the mobile app interface.": "Изображение для мобильного приложения.",
    "The category icon will not appear in the app, so please upload an image for app display.": "Загрузите изображение для приложения.",
    "Banner Section": "Секция баннера",
    "Banner Title": "Заголовок баннера",
    "Enter banner title": "Введите заголовок баннера",
    "Banner Button Text": "Текст кнопки баннера",
    "Enter banner button text": "Введите текст кнопки баннера",
    "Banner Button Url": "URL кнопки баннера",
    "Enter banner button url": "Введите URL кнопки баннера",
    "Banner Image": "Изображение баннера",
    "Section Titles": "Заголовки секций",
    "Enter Featured Listing Section Title": "Введите заголовок избранных",
    "Enter category title": "Введите заголовок категории",
    "This section is for configuring the mobile app interface.": "Настройка мобильного интерфейса.",
    "Update texts": "Обновить тексты",
    "Update general settings": "Обновить общие настройки",
    "Update payment gateways settings": "Обновить платёжные шлюзы",
    "Update necessary plugins": "Обновить плагины",
    "Upload the Firebase Admin SDK JSON file from your Firebase project.": "Загрузите Firebase Admin SDK JSON.",
    "You have a file, and you can change it by re-uploading it.": "Файл можно изменить повторной загрузкой.",
    "Google Map Status": "Статус Google Map",
    "When plugins have Google Map credentials, they can be used.": "Плагины с Google Map учётными данными.",
    "Go Here": "Перейти сюда",
    "AZIM": "AZIM",
    "Note": "Примечание",
    "Important": "Важно",
    "Publishable": "Публикуемый",
    "The gallery images field is required.": "Поле галереи обязательно.",
    "Google Map API Status": "Статус Google Map API",
    "Google map api updated successfully": "Google Map API обновлён",
    "If the Google Maps API is disabled:": "Если Google Maps API отключён:",
    "Google will not suggest locations under address inputs.": "Google не будет предлагать адреса.",
    "After a location is seached, all the available listings which are located within this radius will be displayed.": "Объявления в радиусе поиска.",
    "Google AdSense": "Google AdSense",
    "Google Adsense Publisher ID": "Google AdSense Publisher ID",
    "google_adsense_publisher_id": "google adsense publisher id",
    "Facebook info updated successfully": "Facebook обновлён",
    "facebook_app_id": "facebook app id",
    "Google info updated successfully": "Google обновлён",
    "google_client_id": "google client id",
    "google_client_secret": "google client secret",
    "google_login_status": "статус google",
    "google_recaptcha_secret_key": "секретный ключ recaptcha",
    "google_recaptcha_site_key": "ключ сайта recaptcha",
    "google_recaptcha_status": "статус recaptcha",
    "google_map_api_key": "ключ google map api",
    "google_map_api_key_status": "статус ключа google map",
    "Disqus": "Disqus",
    "Disqus Status": "Статус Disqus",
    "Disqus Short Name": "Короткое имя Disqus",
    "Disqus info updated successfully": "Disqus обновлён",
    "disqus_short_name": "короткое имя disqus",
    "Messenger Status": "Статус Messenger",
    "Messenger Direct Chat Link": "Ссылка чата Messenger",
    "Messanger info updated successfully": "Messenger обновлён",
    "If you enable Tawk.To, then you must disable WhatsApp": "Tawk.To включён — отключите WhatsApp",
    "If you enable WhatsApp, then you must disable Tawk.To": "WhatsApp включён — отключите Tawk.To",
    "whatsapp_number": "номер whatsapp",
    "whatsapp_header_title": "заголовок whatsapp",
    "whatsapp_popup_message": "сообщение whatsapp",
    "tawkto_status": "статус tawkto",
    "tawkto_direct_chat_link": "ссылка чата tawkto",
    "VAPID Public Key": "Публичный ключ VAPID",
    "VAPID Private Key": "Приватный ключ VAPID",
    "Enter VAPID Public Key": "Введите публичный ключ VAPID",
    "Enter VAPID Private Key": "Введите приватный ключ VAPID",
    "vapid_public_key": "публичный ключ vapid",
    "vapid_private_key": "приватный ключ vapid",
    "Delay": "Задержка",
    "delay": "задержка",
    "milliseconds": "миллисекунды",
    "Verifying payment...": "Проверка платежа...",
    "Pay with PayTabs": "Оплатить через PayTabs",
    "No payment URL received": "URL платежа не получен",
    "Payment cancelled": "Платёж отменён",
    "Payment successful!": "Платёж успешен!",
    "Payment verification failed": "Проверка не удалась",
    "Payment page not available": "Страница оплаты недоступна",
    "Payment URL not available": "URL платежа недоступен",
    "Order completion failed": "Завершение заказа не удалось",
    "Invalid payment data received": "Неверные данные платежа",
    "Invalid invoice data received": "Неверные данные счёта",
    "Cannot open invoice URL": "Не удалось открыть счёт",
    "External wallet payment initiated": "Внешний кошелёк инициирован",
    "Razorpay configuration is missing": "Конфигурация Razorpay отсутствует",
    "Complete Payment": "Завершить платёж",
    "Failed to load products": "Ошибка загрузки товаров",
    "Failed to load product details": "Ошибка загрузки товара",
    "Failed to load listing details": "Ошибка загрузки объявления",
    "Failed to load categories": "Ошибка загрузки категорий",
    "Failed to load checkout data": "Ошибка загрузки оформления",
    "Failed to load payment page": "Ошибка загрузки оплаты",
    "Failed to pick file": "Ошибка выбора файла",
    "Your cart is empty": "Корзина пуста",
    "No product data available": "Данные товара недоступны",
    "Product details not available": "Детали товара недоступны",
    "No listings match your filters": "Нет объявлений по фильтрам",
    "No categories available": "Категории недоступны",
    "Order not found": "Заказ не найден",
    "Total Listings": "Всего объявлений",
    "Total Orders": "Всего заказов",
    "All Requests": "Все запросы",
    "Aproved Requests": "Одобренные запросы",
    "Approved At": "Одобрено в",
    "Approve Status": "Статус одобрения",
    # MESSAGES
    "Chat": "Чат",
    "Conversations": "Беседы",
    "Send Message": "Отправить сообщение",
    # STATS
    "Statistics": "Статистика",
    "Reports": "Отчёты",
    "Analytics": "Аналитика",
    "Overview": "Обзор",
    # MISC MESSAGES
    "Your transaction was successful": "Транзакция успешна",
    "Your transaction request was received and sent for review": "Запрос транзакции отправлен на проверку",
    "We have sent you a mail with an invoice": "Письмо со счётом отправлено",
    "We answer every request as quickly as we can": "Отвечаем как можно быстрее",
    "usually within 24–48 hours": "обычно в течение 24–48 часов",
    "Keep it blank, if you do not want to keep any minimum spend limit.": "Оставьте пустым для безлимитных трат.",
    "input field, it will be in the form by default": "поле будет в форме по умолчанию",
    "input field, it will be in the Table Reservation form by default": "поле будет в форме бронирования",
    "Background Color Code": "Код цвета фона",
    "Background Color Opacity": "Прозрачность фона",
    "background_color_opacity": "прозрачность фона",
    "background_image": "фоновое изображение",
    "benifit_section_title": "заголовок преимуществ",
    "blog_section_button_text": "текст кнопки блога",
    "blog_section_title": "заголовок блога",
    "city_section_title": "заголовок городов",
    "feature_image": "изображение особенности",
    "featured_image": "избранное изображение",
    "featured_section_text": "текст избранной секции",
    "featured_section_title": "заголовок избранной секции",
    "gallery images": "изображения галереи",
    "icon": "иконка",
    "image": "изображение",
    "logo": "логотип",
    "favicon": "фавикон",
    "mail_address": "почтовый адрес",
    "mail_body": "тело письма",
    "mail_subject": "тема письма",
    "mobile": "мобильный",
    "photo": "фото",
    "slider_images": "изображения слайдера",
    "secondary_color": "второстепенный цвет",
    "primary_color": "основной цвет",
    "preloader": "прелоадер",
    "radius": "радиус",
    "role_id": "роль",
    "smtp_host": "smtp хост",
    "smtp_port": "smtp порт",
    "smtp_username": "smtp пользователь",
    "smtp_password": "smtp пароль",
    "sandbox_check": "песочница",
    "test_mode": "тестовый режим",
    "transaction_key": "ключ транзакции",
    "public_key": "публичный ключ",
    "short_text": "короткий текст",
    "website_title": "заголовок сайта",
    "testimonial_section_title": "заголовок отзывов",
    "testimonial_section_subtitle": "подзаголовок отзывов",
    "testimonial_section_clients": "клиенты отзывов",
    "number_of_images_per_listing": "изображений на объявление",
    "number_of_listing": "количество объявлений",
    "number_of_amenities_per_listing": "удобств на объявление",
    "number_of_additional_specification": "доп. характеристик",
    "number_of_social_links": "количество соцссылок",
    "number_of_faq": "количество faq",
    "number_of_products": "количество товаров",
    "number_of_images_per_products": "изображений на товары",
    "number_of_bookings": "количество бронирований",
    "payment_method": "способ оплаты",
    "payment_status": "статус оплаты",
    "resolution_type": "тип разрешения",
    "Enter new line to seperate features": "Новая строка для разделения",
    "Enter Package title": "Введите название пакета",
    "Enter Package price": "Введите цену пакета",
    "Enter Short Description": "Введите краткое описание",
    "Enter Short Text": "Введите короткий текст",
    "Enter Summary": "Введите сводку",
    "Enter Text": "Введите текст",
    "Enter Title": "Введите название",
    "Enter Work Process Serial Number": "Введите номер процесса",
    "Enter Work Process Title": "Введите название процесса",
    "Enter Mail Subject": "Введите тему письма",
    "Enter Mail Body Format": "Введите формат письма",
    "Enter Address": "Введите адрес",
    "Enter Username": "Введите имя пользователя",
    "Enter Password": "Введите пароль",
    "Enter Phone": "Введите телефон",
    "Enter Phone Number": "Введите номер телефона",
    "Enter Email": "Введите email",
    "Enter Email Address": "Введите адрес email",
    "Enter Name": "Введите имя",
    "Enter First Name": "Введите имя",
    "Enter Last Name": "Введите фамилию",
    "Enter Quick Link Title": "Введите название ссылки",
    "Enter Quick Link URL": "Введите URL ссылки",
    "Enter Coupon Code": "Введите код купона",
    "Enter Rating": "Введите рейтинг",
    "Enter Withdraw Maximum Limit": "Введите макс. лимит вывода",
    "Enter Withdraw Minimum Limit": "Введите мин. лимит вывода",
    "Enter URL of Social Media Account": "Введите URL соцсети",
    "Enter Button Name": "Введите название кнопки",
    "Enter Button Text": "Введите текст кнопки",
    "Enter Button URL": "Введите URL кнопки",
    "Enter Button text": "Введите текст кнопки",
    "Enter Popup Name": "Введите название окна",
    "Enter Popup Title": "Введите заголовок окна",
    "Enter Popup Text": "Введите текст окна",
    "Enter Popup Delay": "Введите задержку окна",
    "Button Name": "Название кнопки",
    "Button Text": "Текст кнопки",
    "Button URL": "URL кнопки",
    "button_text": "текст кнопки",
    "button_url": "url кнопки",
    "Button Color Code": "Код цвета кнопки",
    "Enter Form Name": "Введите название формы",
    "Enter Input Label": "Введите метку поля",
    "Enter Input Placeholder": "Введите заполнитель",
    "Enter Menu Name": "Введите название меню",
    "Enter Menu URL": "Введите URL меню",
    "Enter Meta Description": "Введите мета-описание",
    "Enter Meta Keywords": "Введите мета-слова",
    "Enter Method Name": "Введите название способа",
    "Enter Minimum Spend": "Введите мин. траты",
    "Enter Payment Gateway Name": "Введите название шлюза",
    "Enter Percentage Charge": "Введите процентный сбор",
    "Enter Product Current Price": "Введите текущую цену",
    "Enter Product Previous Price": "Введите предыдущую цену",
    "Enter Product Stock": "Введите остаток",
    "Enter Push Notification Title": "Введите заголовок уведомления",
    "Enter Question": "Введите вопрос",
    "Enter Answer": "Введите ответ",
    "Enter Redirect URL": "Введите URL перенаправления",
    "Enter Role Name": "Введите название роли",
    "Enter Shipping Charge": "Введите стоимость доставки",
    "Enter Video URL": "Введите URL видео",
    "Enter Your video url": "Введите URL видео",
    "Enter Google Adsense Publisher ID": "Введите Google AdSense ID",
    "Enter Ad Slot": "Введите слот рекламы",
    "Enter Gateway Instructions": "Введите инструкции шлюза",
    "Enter Amenity Title": "Введите название удобства",
    "Enter Coupon Name": "Введите название купона",
    "Enter Coupon Value": "Введите значение купона",
    "Enter Fixed Charge": "Введите фикс. сбор",
    "Enter Website Title": "Введите название сайта",
    "Enter Number of Listings": "Введите кол-во объявлений",
    "Enter Number of Products": "Введите кол-во товаров",
    "Enter Number of image per Listing": "Введите кол-во изображений",
    "Enter Number of Images per Product": "Введите кол-во изображений товара",
    "Enter Number of Amenities per Listing": "Введите кол-во удобств",
    "Enter Number of Features per Listing": "Введите кол-во особенностей",
    "Enter Number of FAQs per Listing": "Введите кол-во FAQ",
    "Enter Number of Social Links per Listing": "Введите кол-во соцссылок",
    "Enter Number of Products per Listing": "Введите кол-во товаров на объявление",
    "Enter 999999 , then it will appear as unlimited": "Введите 999999 для безлимитно",
    "Egypt": "Египет",
    "Iraq": "Ирак",
    "Jordan": "Иордания",
    "Limit has been crossed, vendor has to delete": "Лимит превышен, нужно удалить",
    "Limit has been crossed,vendor has to delete": "Лимит превышен, нужно удалить",
    "Limit has been crossed, vendor has to delete,products": "Лимит превышен, удалите товары",
    "Limit has been crossed, vendor has to delete Amenities": "Лимит превышен, удалите удобства",
    "Limit has been crossed, vendor has to delete faqs": "Лимит превышен, удалите FAQ",
    "Limit has been crossed, vendor has to delete Social Links": "Лимит превышен, удалите соцссылки",
    "Limit has been crossed, vendor has to delete Specifications": "Лимит превышен, удалите характеристики",
    "If your current package is lifetime package, then you have to change / remove the current package first": "Сначала измените/удалите текущий пожизненный пакет",
    "If your current package is trial package, then you have to change / remove the current package first": "Сначала измените/удалите пробный пакет",
    "images under one listing": "изображений на объявление",
    "images under one product": "изображений на товар",
    "aminities can be added per listing for": "удобств на объявление для",
    "Do not create": "Не создавать",
    "First delete all the listing of these categories": "Сначала удалите объявления этих категорий",
    "First delete all the listing of these Amenities": "Сначала удалите объявления этих удобств",
    "First delete all the listing of these City": "Сначала удалите объявления этого города",
    "First delete all the listing of these Country": "Сначала удалите объявления этой страны",
    "First delete all the listing of these State": "Сначала удалите объявления этой области",
    "First delete all the listing of this Amenitie": "Сначала удалите объявления этого удобства",
    "First delete all the listing of this category": "Сначала удалите объявления этой категории",
    "First delete all the listing of this City": "Сначала удалите объявления этого города",
    "First delete all the listing of this Country": "Сначала удалите объявления этой страны",
    "First delete all the listing of this State": "Сначала удалите объявления этой области",
    "First delete all the city of these Country": "Сначала удалите города этой страны",
    "First delete all the city of these State": "Сначала удалите города этой области",
    "First delete all the city of this Country": "Сначала удалите города этой страны",
    "First delete all the city of this State": "Сначала удалите города этой области",
    "First delete all the State of these Country": "Сначала удалите области этой страны",
    "First delete all the State of this Country": "Сначала удалите области этой страны",
    "First delete all the blog of these categories": "Сначала удалите блоги этих категорий",
    "First delete all the blog of this category": "Сначала удалите блоги этой категории",
    "First delete all the product of these categories": "Сначала удалите товары этих категорий",
    "First delete all the products of this category": "Сначала удалите товары этой категории",
    "hero_section_title": "заголовок главного блока",
    "hero_section_subtitle": "подзаголовок главного блока",
    "counter_section_video_link": "видео ссылка счётчиков",
    "call_to_action_section_title": "заголовок CTA",
    "call_to_action_button_url": "URL кнопки CTA",
    "call_to_action_section_btn": "кнопка CTA",
    "Citibank": "PayPal",
    "CVC Number": "CVC номер",
    "Card Number": "Номер карты",
    "Expiry Month": "Месяц",
    "Expiry Year": "Год",
    "Card Code": "Код карты",
    "open": "открыто",
    "Open": "Открыто",
    "off": "скидка",
    "royal": "royal",
    "author": "автор",
}


# Escape special chars in keys for regex matching
def escape_key(k):
    return re.escape(k)


# Load admin_ru.json
with open("resources/lang/admin_ru.json", "r", encoding="utf-8") as f:
    data = json.load(f)

# Translate
count = 0
for key, value in data.items():
    if key in translations:
        if data[key] != translations[key]:
            data[key] = translations[key]
            count += 1

# Write back
with open("resources/lang/admin_ru.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Translated {count} keys in admin_ru.json")

# Also translate ru.json
with open("resources/lang/ru.json", "r", encoding="utf-8") as f:
    data = json.load(f)

count = 0
for key, value in data.items():
    if key in translations:
        if data[key] != translations[key]:
            data[key] = translations[key]
            count += 1

with open("resources/lang/ru.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Translated {count} keys in ru.json")
