#!/usr/bin/env python3
"""Translate admin_tr.json and tr.json to Turkish"""

import json

translations = {
    # COMMON UI
    "Dashboard": "Kontrol Paneli",
    "Home": "Ana Sayfa",
    "Save": "Kaydet",
    "Saved": "Kaydedildi",
    "Cancel": "İptal",
    "cancel": "iptal",
    "Close": "Kapat",
    "Closed": "Kapalı",
    "closed": "kapalı",
    "Delete": "Sil",
    "Deleted successfully": "Başarıyla silindi",
    "Edit": "Düzenle",
    "Update": "Güncelle",
    "Create": "Oluştur",
    "Add": "Ekle",
    "Add New": "Yeni Ekle",
    "View": "Görüntüle",
    "View All": "Tümünü Gör",
    "View Details": "Detayları Gör",
    "View More": "Daha Fazla Gör",
    "View Profile": "Profili Gör",
    "Visit Profile": "Profili Ziyaret Et",
    "Back": "Geri",
    "Back to Lists": "Listeye Dön",
    "Back to Home": "Ana Sayfaya Dön",
    "Submit": "Gönder",
    "Search": "Ara",
    "Filter": "Filtrele",
    "Filters": "Filtreler",
    "Reset": "Sıfırla",
    "Reset All": "Tümünü Sıfırla",
    "Clear": "Temizle",
    "Import": "İçe Aktar",
    "Export": "Dışa Aktar",
    "Download": "İndir",
    "Download File": "Dosyayı İndir",
    "Upload": "Yükle",
    "Choose": "Seç",
    "Choose file": "Dosya seç",
    "Choose Image": "Resim Seç",
    "Choose Photo": "Fotoğraf Seç",
    "Browse": "Gözat",
    "File": "Dosya",
    "File not found": "Dosya bulunamadı",
    "File Upload": "Dosya Yükleme",
    "File Download Link": "Dosya İndirme Bağlantısı",
    "Print": "Yazdır",
    "print": "yazdır",
    "Preview": "Önizleme",
    "Publish": "Yayınla",
    "Unpublish": "Yayından Kaldır",
    "Draft": "Taslak",
    "Archived": "Arşivlendi",
    "Trash": "Çöp",
    "Restore": "Geri Yükle",
    "Copy": "Kopyala",
    "Copy Link": "Bağlantıyı Kopyala",
    "Move": "Taşı",
    "Rename": "Yeniden Adlandır",
    "Refresh": "Yenile",
    "Reload": "Yeniden Yükle",
    "Loading...": "Yükleniyor...",
    "Loading": "Yükleniyor",
    "Processing...": "İşleniyor...",
    "Please wait...": "Lütfen bekleyin...",
    "No data available": "Veri yok",
    "No results found": "Sonuç bulunamadı",
    "No items found": "Öğe bulunamadı",
    "No records found": "Kayıt bulunamadı",
    "Empty": "Boş",
    "None": "Hiçbiri",
    "All": "Tümü",
    "Select": "Seç",
    "Select All": "Tümünü Seç",
    "Deselect All": "Seçimi Kaldır",
    "Are you sure": "Emin misiniz",
    "Confirm": "Onayla",
    "Confirm Delete": "Silmeyi Onayla",
    "Confirm Password": "Şifreyi Onayla",
    "Confirm New Password": "Yeni Şifreyi Onayla",
    "Yes": "Evet",
    "No": "Hayır",
    "Next": "Sonraki",
    "Previous": "Önceki",
    "Finish": "Bitir",
    "Skip": "Atla",
    "Continue": "Devam Et",
    "Proceed": "Devam Et",
    "Go Back": "Geri Dön",
    "Go to Login": "Girişe Git",
    "Login": "Giriş",
    "Logout": "Çıkış",
    "Register": "Kayıt Ol",
    "Signup": "Kayıt Ol",
    "Sign In": "Giriş Yap",
    "Sign Out": "Çıkış Yap",
    "Sign Up": "Kayıt Ol",
    "Forgot Password?": "Şifremi Unuttum?",
    "Forgot password": "Şifremi unuttum",
    "Forget Password": "Şifremi Unuttum",
    "Reset Password": "Şifreyi Sıfırla",
    "Change Password": "Şifreyi Değiştir",
    "Current Password": "Mevcut Şifre",
    "New Password": "Yeni Şifre",
    "Password": "Şifre",
    "Remember Me": "Beni Hatırla",
    "Email": "E-posta",
    "Email Address": "E-posta Adresi",
    "Email ID": "E-posta ID",
    "Username": "Kullanıcı Adı",
    "Username/Email*": "Kullanıcı Adı/E-posta*",
    "Password*": "Şifre*",
    "Email*": "E-posta*",
    "Confirm Password*": "Şifre Onayı*",
    "New Password*": "Yeni Şifre*",
    "Current Password*": "Mevcut Şifre*",
    "Confirm New Password*": "Yeni Şifre Onayı*",
    "Name": "Ad",
    "First Name": "Ad",
    "Last Name": "Soyad",
    "Full Name": "Ad Soyad",
    "Phone": "Telefon",
    "Phone Number": "Telefon Numarası",
    "Mobile": "Mobil",
    "Address": "Adres",
    "City": "Şehir",
    "State": "Eyalet/Bölge",
    "Country": "Ülke",
    "Zip Code": "Posta Kodu",
    "Postcode/Zip": "Posta Kodu",
    "Location": "Konum",
    "Latitude": "Enlem",
    "Longitude": "Boylam",
    "Website": "Web Sitesi",
    "URL": "URL",
    "Link": "Bağlantı",
    "Image": "Resim",
    "Images": "Resimler",
    "Photo": "Fotoğraf",
    "Icon": "Simge",
    "Logo": "Logo",
    "Favicon": "Favicon",
    "Avatar": "Avatar",
    "Banner": "Banner",
    "Banner Image": "Banner Resmi",
    "Background Image": "Arka Plan Resmi",
    "Gallery": "Galeri",
    "Gallery Images": "Galeri Resimleri",
    "Slider": "Slider",
    "Video": "Video",
    "Audio": "Ses",
    "Document": "Belge",
    "Attachment": "Ek",
    "Featured Image": "Öne Çıkan Resim",
    "Thumbnail": "Küçük Resim",
    "Preview Image": "Önizleme Resmi",
    "Cover Image": "Kapak Resmi",
    # STATUSES
    "Status": "Durum",
    "Active": "Aktif",
    "Inactive": "Pasif",
    "Deactive": "Devre Dışı Bırak",
    "Enable": "Etkinleştir",
    "Disable": "Devre Dışı Bırak",
    "Enabled": "Etkin",
    "Disabled": "Devre Dışı",
    "Show": "Göster",
    "Hide": "Gizle",
    "Hide/Show": "Gizle/Göster",
    "On": "Açık",
    "Off": "Kapalı",
    "Pending": "Beklemede",
    "pending": "beklemede",
    "Approved": "Onaylandı",
    "approved": "onaylandı",
    "Rejected": "Reddedildi",
    "rejected": "reddedildi",
    "Completed": "Tamamlandı",
    "completed": "tamamlandı",
    "processing": "işleniyor",
    "Published": "Yayınlandı",
    "Unpublished": "Yayından Kaldırıldı",
    "Locked": "Kilitli",
    "Unlocked": "Kilit Açık",
    "Verified": "Doğrulandı",
    "Unverified": "Doğrulanmadı",
    "Suspended": "Askıya Alındı",
    "Banned": "Yasaklandı",
    "Expired": "Süresi Doldu",
    "Fulfilled": "Yerine Getirildi",
    "Default": "Varsayılan",
    "(Default)": "(Varsayılan)",
    "Blank": "Boş",
    "Never Activated": "Hiç Etkinleştirilmedi",
    # ACTIONS
    "Action": "İşlem",
    "Actions": "İşlemler",
    "Manage": "Yönet",
    "Manage Form": "Formu Yönet",
    "Manage Listings": "İlanları Yönet",
    "Manage Plugins": "Eklentileri Yönet",
    "Manage Products": "Ürünleri Yönet",
    "Manage Social Link": "Sosyal Bağlantıyı Yönet",
    "Clone": "Klonla",
    "Clone for": "Şunun için klonla",
    "Duplicate": "Çoğalt",
    "Assign": "Ata",
    "Assigned Staff": "Atanan Personel",
    "Assigned to": "Atandığı kişi",
    "Assign Staff": "Personel Ata",
    "Assing To": "Kişiye Ata",
    "Send": "Gönder",
    "Send message": "Mesaj gönder",
    "Send Email": "E-posta Gönder",
    "Send SMS": "SMS Gönder",
    "Send Notification": "Bildirim Gönder",
    "Reply": "Yanıtla",
    "Report": "Rapor",
    "Download Report": "Raporu İndir",
    "Generate Report": "Rapor Oluştur",
    "Bulk Action": "Toplu İşlem",
    "Bulk Delete": "Toplu Sil",
    "Bulk Update": "Toplu Güncelle",
    "Import Data": "Veri İçe Aktar",
    "Export Data": "Veri Dışa Aktar",
    "Export CSV": "CSV Dışa Aktar",
    "Export Excel": "Excel Dışa Aktar",
    "Export PDF": "PDF Dışa Aktar",
    "Print Invoice": "Fatura Yazdır",
    "Share": "Paylaş",
    "Share Now": "Şimdi Paylaş",
    "Share on": "Paylaş",
    # DATE & TIME
    "Date": "Tarih",
    "date": "tarih",
    "Time": "Saat",
    "Day": "Gün",
    "day": "gün",
    "Days": "Günler",
    "Days For": "Gün Sayısı",
    "Month": "Ay",
    "month": "ay",
    "Year": "Yıl",
    "year": "yıl",
    "Hour": "Saat",
    "hour": "saat",
    "Minute": "Dakika",
    "minute": "dakika",
    "Second": "Saniye",
    "second": "saniye",
    "Today": "Bugün",
    "Yesterday": "Dün",
    "Tomorrow": "Yarın",
    "This Week": "Bu Hafta",
    "Last Week": "Geçen Hafta",
    "This Month": "Bu Ay",
    "Last Month": "Geçen Ay",
    "This Year": "Bu Yıl",
    "Last Year": "Geçen Yıl",
    "Start Date": "Başlangıç Tarihi",
    "End Date": "Bitiş Tarihi",
    "Start Time": "Başlangıç Saati",
    "End Time": "Bitiş Saati",
    "Expire Date": "Son Kullanma Tarihi",
    "Expire Month": "Son Kullanma Ayı",
    "Expire Year": "Son Kullanma Yılı",
    "Expires": "Süresi Doluyor",
    "Created": "Oluşturuldu",
    "Created At": "Oluşturulma Tarihi",
    "Updated At": "Güncellenme Tarihi",
    "Deleted At": "Silinme Tarihi",
    "Calendar": "Takvim",
    "Schedule": "Program",
    "Duration": "Süre",
    "12 Hour": "12 Saat",
    "24 Hour": "24 Saat",
    "Monday": "Pazartesi",
    "Tuesday": "Salı",
    "Wednesday": "Çarşamba",
    "Thursday": "Perşembe",
    "Friday": "Cuma",
    "Saturday": "Cumartesi",
    "Sunday": "Pazar",
    # USERS & ADMIN
    "User": "Kullanıcı",
    "Users": "Kullanıcılar",
    "Add User": "Kullanıcı Ekle",
    "Edit User": "Kullanıcıyı Düzenle",
    "User Management": "Kullanıcı Yönetimi",
    "Registered Users": "Kayıtlı Kullanıcılar",
    "User List": "Kullanıcı Listesi",
    "User Details": "Kullanıcı Detayları",
    "User Profile": "Kullanıcı Profili",
    "User Role": "Kullanıcı Rolü",
    "User Status": "Kullanıcı Durumu",
    "Account": "Hesap",
    "Account Information": "Hesap Bilgileri",
    "Account Status": "Hesap Durumu",
    "Account status updated successfully": "Hesap durumu başarıyla güncellendi",
    "Account Settings": "Hesap Ayarları",
    "Profile": "Profil",
    "Edit Profile": "Profili Düzenle",
    "Edit Your Profile": "Profilini Düzenle",
    "Edit Profile Page Title": "Profil Sayfası Başlığı",
    "Update Profile": "Profili Güncelle",
    "Customer": "Müşteri",
    "Customer Information": "Müşteri Bilgileri",
    "Customers can submit queries through this form": "Müşteriler bu form ile sorgu gönderebilir",
    "customer_email": "müşteri e-postası",
    "customer_name": "müşteri adı",
    "customer_phone": "müşteri telefonu",
    "Subscribers": "Aboneler",
    "Subscribe": "Abone Ol",
    "Subscribe Us": "Bize Abone Ol",
    "Subscribe to Our Newsletter": "Bültenimize Abone Ol",
    "Stay update with us and get offer": "Güncel kalın ve teklif alın",
    "Member since": "Üyelik tarihi",
    "Member details": "Üye detayları",
    "Membership": "Üyelik",
    "Membership Request Sent.": "Üyelik Talebi Gönderildi.",
    "Monthly Package Purchase": "Aylık Paket Satın Alımı",
    "Month wise registered users": "Aylara göre kayıtlı kullanıcılar",
    "Month wise visitors": "Aylara göre ziyaretçiler",
    "Monthly Listing Posts": "Aylık İlan Gönderileri",
    "Identity Number": "Kimlik Numarası",
    # ADMIN
    "Admin": "Yönetici",
    "Admins": "Yöneticiler",
    "Super Admin": "Süper Yönetici",
    "Add Admin": "Yönetici Ekle",
    "Edit Admin": "Yöneticiyi Düzenle",
    "Admin Management": "Yönetici Yönetimi",
    "Admin deleted successfully": "Yönetici başarıyla silindi",
    "Admin updated successfully": "Yönetici başarıyla güncellendi",
    "New admin added successfully": "Yeni yönetici başarıyla eklendi",
    "Admin action required": "Yönetici işlemi gerekiyor",
    "Admin Approval Notice": "Yönetici Onay Bildirimi",
    "Admin Earnings": "Yönetici Kazançları",
    "Admin Forms": "Yönetici Formları",
    "Admin can also create quote request forms for each language": "Yönetici her dil için teklif formu oluşturabilir",
    "Role": "Rol",
    "Roles": "Roller",
    "Add Role": "Rol Ekle",
    "Edit Role": "Rolü Düzenle",
    "Role Management": "Rol Yönetimi",
    "New role added successfully": "Yeni rol başarıyla eklendi",
    "Permissions": "İzinler",
    "Permission": "İzin",
    "First delete all the admins of this role": "Önce bu role sahip tüm yöneticileri silin",
    # VENDOR
    "Vendor": "Satıcı",
    "Vendors": "Satıcılar",
    "Add vendor": "Satıcı Ekle",
    "Add Vendor Successfully": "Satıcı Başarıyla Eklendi",
    "Edit Vendor": "Satıcıyı Düzenle",
    "Vendor Management": "Satıcı Yönetimi",
    "Registered Vendors": "Kayıtlı Satıcılar",
    "Vendor Details": "Satıcı Detayları",
    "Vendor Profile Available": "Satıcı Profili Mevcut",
    "Vendor username": "Satıcı kullanıcı adı",
    "Vendor Info": "Satıcı Bilgisi",
    "Select Vendor": "Satıcı Seç",
    "Contact Vendor": "Satıcıyla İletişime Geç",
    "if you do not select any vendor, then this Listing will be listed for Admin": "satıcı seçmezseniz ilan Yönetici için listelenir",
    "If no vendor is selected, this will be considered as Admin": "Satıcı seçilmezse Yönetici sayılır",
    # LISTING
    "Listing": "İlan",
    "Listings": "İlanlar",
    "listings": "ilanlar",
    "Add Listing": "İlan Ekle",
    "Edit Listing": "İlanı Düzenle",
    "All Listings": "Tüm İlanlar",
    "Listings Management": "İlan Yönetimi",
    "Listing Specifications": "İlan Özellikleri",
    "Listing Title": "İlan Başlığı",
    "Listing Messages": "İlan Mesajları",
    "Listing View": "İlan Görünümü",
    "Listing Enquiry Form": "İlan Sorgu Formu",
    "Listing Images (Per Listing)": "İlan Resimleri (İlan Başına)",
    "New Listing category added successfully": "İlan kategorisi başarıyla eklendi",
    "Listing deleted successfully": "İlan başarıyla silindi",
    "Listing Updated successfully": "İlan başarıyla güncellendi",
    "Listing Approved successfully": "İlan başarıyla onaylandı",
    "Listing Rejected successfully": "İlan başarıyla reddedildi",
    "Listing Show successfully": "İlan başarıyla gösterildi",
    "Listing Hide successfully": "İlan başarıyla gizlendi",
    "Listing Featured successfully": "İlan başarıyla öne çıkarıldı",
    "Listing Pending successfully": "İlan beklemeye alındı",
    "New Listing added successfully": "Yeni ilan başarıyla eklendi",
    "Listing Auto Approval": "İlan Otomatik Onayı",
    "Featured Listing Section": "Öne Çıkan İlanlar",
    "Featured Listings": "Öne Çıkan İlanlar",
    "Featured Listing Section Status": "Öne Çıkan İlan Durumu",
    "Featured Listing Section Title": "Öne Çıkan İlan Başlığı",
    "Featured Status": "Öne Çıkma Durumu",
    "Latest Listing Section": "En Yeni İlanlar",
    "Latest Listing Section Status": "En Yeni İlan Durumu",
    "Listings limit reached or exceeded": "İlan limiti aşıldı",
    "Listings Left": "Kalan İlanlar",
    "Listing (Unlimited)": "İlan (Sınırsız)",
    "Unlimited Listing": "Sınırsız İlan",
    "Images Per Listing (Unlimited)": "Resimler (Sınırsız)",
    "Image Per Listing": "İlan Başına Resim",
    "Image Per Listings": "İlan Başına Resimler",
    "Unlimited Listing Image": "Sınırsız İlan Resmi",
    "Listing Page Title": "İlan Sayfası Başlığı",
    "Business Hours": "Çalışma Saatleri",
    "Business Hours Updated successfully": "Çalışma saatleri güncellendi",
    "Business Days": "Çalışma Günleri",
    "Holiday": "Tatil",
    "Holiday Updated successfully": "Tatil güncellendi",
    # CATEGORIES
    "Categories": "Kategoriler",
    "Category": "Kategori",
    "Category Name": "Kategori Adı",
    "Category Code": "Kategori Kodu",
    "Category Status": "Kategori Durumu",
    "Category Section": "Kategori Bölümü",
    "Category Section Status": "Kategori Bölüm Durumu",
    "Category Serial Number": "Kategori Sıra Numarası",
    "Add Listing Category": "İlan Kategorisi Ekle",
    "Edit Listing Category": "İlan Kategorisini Düzenle",
    "Listing categories deleted successfully": "İlan kategorileri silindi",
    "Listing category updated successfully": "İlan kategorisi güncellendi",
    "category_id": "kategori",
    "Category deleted successfully": "Kategori başarıyla silindi",
    "Select Category": "Kategori Seç",
    "Category Listing Section Title": "Kategori Bölüm Başlığı",
    "Search By Category": "Kategoriye Göre Ara",
    "All Categories": "Tüm Kategoriler",
    "Explore Popular Categories": "Popüler Kategorileri Keşfet",
    # PRODUCTS / SHOP
    "Shop": "Mağaza",
    "Product": "Ürün",
    "Products": "Ürünler",
    "Add Product": "Ürün Ekle",
    "Edit Product": "Ürünü Düzenle",
    "Product Categories": "Ürün Kategorileri",
    "Add Product Category": "Ürün Kategorisi Ekle",
    "Edit Product Category": "Ürün Kategorisini Düzenle",
    "Product Name": "Ürün Adı",
    "Product Details": "Ürün Detayları",
    "Product Image": "Ürün Resmi",
    "Product Images": "Ürün Resimleri",
    "Product Image Per Product": "Ürün Başına Resim",
    "Product Image Per Product (Unlimited)": "Ürün Başına Resim (Sınırsız)",
    "Product Images Per Product": "Ürün Başına Resimler",
    "Product Per Listing": "İlan Başına Ürün",
    "Product Per Listing (Unlimited)": "İlan Başına Ürün (Sınırsız)",
    "Products Per Listing": "İlan Başına Ürünler",
    "Products (Unlimited)": "Ürünler (Sınırsız)",
    "Product Orders": "Ürün Siparişleri",
    "Product Enquiry Form": "Ürün Sorgu Formu",
    "Product added into the cart.": "Ürün sepete eklendi.",
    "Product removed successfully": "Ürün başarıyla kaldırıldı",
    "New Product added successfully": "Yeni ürün eklendi",
    "New product category added successfully": "Ürün kategorisi eklendi",
    "New product added successfully": "Yeni ürün eklendi",
    "Unlimited Product Image": "Sınırsız Ürün Resmi",
    "Unlimited Products": "Sınırsız Ürün",
    "Stock": "Stok",
    "Stock Out": "Stokta Yok",
    "Out Of Stock": "Stokta Yok",
    "In Stock": "Stokta Var",
    "Price": "Fiyat",
    "Current Price": "Güncel Fiyat",
    "Min Price": "Min Fiyat",
    "Max Price": "Maks Fiyat",
    "Discount": "İndirim",
    "Tax": "Vergi",
    "Shipping Charge": "Kargo Ücreti",
    "Add Shipping Charge": "Kargo Ücreti Ekle",
    "Edit Shipping Charge": "Kargo Ücretini Düzenle",
    "New shipping charge added successfully": "Kargo ücreti eklendi",
    "Coupon": "Kupon",
    "Coupons": "Kuponlar",
    "Add Coupon": "Kupon Ekle",
    "Edit Coupon": "Kuponu Düzenle",
    "Coupon Type": "Kupon Türü",
    "Coupon applied successfully!": "Kupon başarıyla uygulandı!",
    "Coupon applied successfully.": "Kupon başarıyla uygulandı.",
    "Coupon deleted successfully": "Kupon silindi",
    "Coupon updated successfully": "Kupon güncellendi",
    "New coupon added successfully": "Yeni kupon eklendi",
    "Cart": "Sepet",
    "Cart is Empty": "Sepet Boş",
    "Cart Total": "Sepet Toplamı",
    "Cart Page Title": "Sepet Sayfası Başlığı",
    "Cart updated successfully": "Sepet güncellendi",
    "Checkout": "Ödeme",
    "Checkout Now": "Hemen Öde",
    "Checkout Page Title": "Ödeme Sayfası Başlığı",
    "Order": "Sipariş",
    "Orders": "Siparişler",
    "Order Details": "Sipariş Detayları",
    "Order Date": "Sipariş Tarihi",
    "Order No.": "Sipariş No",
    "Order Number": "Sipariş Numarası",
    "Order Status": "Sipariş Durumu",
    "Order Summary": "Sipariş Özeti",
    "Order Now": "Şimdi Sipariş Ver",
    "Ordered Product": "Sipariş Edilen Ürün",
    "Total": "Toplam",
    "Total Orders": "Toplam Sipariş",
    "Total Price": "Toplam Fiyat",
    "Total Quantity": "Toplam Miktar",
    "Subtotal": "Ara Toplam",
    "Grand Total": "Genel Toplam",
    "Paid amount": "Ödenen Tutar",
    "Paid Amount": "Ödenen Tutar",
    "Invoice": "Fatura",
    "Billing Details": "Fatura Bilgileri",
    "Billing Address": "Fatura Adresi",
    "Shipping Address": "Teslimat Adresi",
    "Shipping Details": "Teslimat Detayları",
    "Shipping Cost": "Kargo Maliyeti",
    "Shipping Method": "Teslimat Yöntemi",
    "Ship to a different address": "Farklı adrese teslim et",
    "Same as billing address": "Fatura adresiyle aynı",
    "Quantity": "Miktar",
    "Items": "Ürünler",
    "Item": "Ürün",
    "Amount": "Tutar",
    "amount": "tutar",
    "Cost": "Maliyet",
    "Charge": "Ücret",
    "Charges": "Ücretler",
    "Fixed Charge": "Sabit Ücret",
    "Fixed": "Sabit",
    "Free": "Ücretsiz",
    "Percentage Charge": "Yüzdelik Ücret",
    "Commission": "Komisyon",
    "Commission Amount": "Komisyon Tutarı",
    "Payment Method": "Ödeme Yöntemi",
    "Payment Status": "Ödeme Durumu",
    "Payment Information": "Ödeme Bilgileri",
    "Payment Instructions": "Ödeme Talimatları",
    "Payment Proof/Receipt": "Ödeme Kanıtı/Makbuz",
    "Payment Gateways": "Ödeme Ağ Geçitleri",
    "Gateway Name": "Ağ Geçidi Adı",
    "Add Gateway": "Ağ Geçidi Ekle",
    "Edit Gateway": "Ağ Geçidini Düzenle",
    "Online Gateways": "Çevrimiçi Ağ Geçitleri",
    "Offline Gateways": "Çevrimdışı Ağ Geçitleri",
    "Place Order": "Sipariş Ver",
    "Purchase": "Satın Al",
    "Buy Now": "Hemen Al",
    "Buy Plan": "Planı Satın Al",
    "Proceed to Checkout": "Ödemeye Geç",
    # BLOG
    "Blog": "Blog",
    "Blogs": "Bloglar",
    "Blog Management": "Blog Yönetimi",
    "Add Post": "Yazı Ekle",
    "Edit Post": "Yazıyı Düzenle",
    "Posts": "Yazılar",
    "All Posts": "Tüm Yazılar",
    "Recent Posts": "Son Yazılar",
    "Blog Category": "Blog Kategorisi",
    "Add Blog Category": "Blog Kategorisi Ekle",
    "Edit Blog Category": "Blog Kategorisini Düzenle",
    "Blog categories deleted successfully": "Blog kategorileri silindi",
    "Blog category updated successfully": "Blog kategorisi güncellendi",
    "Blog deleted successfully": "Blog silindi",
    "Blog updated successfully": "Blog güncellendi",
    "New blog added successfully": "Yeni blog yazısı eklendi",
    "New blog category added successfully": "Blog kategorisi eklendi",
    "Blog section updated successfully": "Blog bölümü güncellendi",
    "Blog Page Title": "Blog Sayfası Başlığı",
    "Blog Section": "Blog Bölümü",
    "Blog Section Status": "Blog Bölüm Durumu",
    "Blogs deleted successfully": "Blog yazıları silindi",
    "All Blog Post": "Tüm Blog Yazıları",
    "Search Blog": "Blogda Ara",
    "Search Posts": "Yazılarda Ara",
    "Author": "Yazar",
    "By": "Tarafından",
    "By Admin": "Yönetici Tarafından",
    "Comments": "Yorumlar",
    "Comment": "Yorum",
    "comment": "yorum",
    # FAQ
    "FAQ": "SSS",
    "FAQs": "SSS",
    "FAQ Management": "SSS Yönetimi",
    "Add FAQ": "SSS Ekle",
    "Edit FAQ": "SSS Düzenle",
    "FAQ deleted successfully": "SSS silindi",
    "FAQ updated successfully": "SSS güncellendi",
    "New faq added successfully": "Yeni SSS eklendi",
    "FAQ Page Title": "SSS Sayfası Başlığı",
    "FAQ Per Listing": "İlan Başına SSS",
    "FAQs Per Listing": "İlan Başına SSS",
    "Faqs (Per Listing)": "SSS (İlan Başına)",
    "FAQs Per Listing(Unlimited)": "İlan Başına SSS (Sınırsız)",
    "FAQ limit reached or exceeded": "SSS limiti aşıldı",
    "FAQs deleted successfully": "SSS silindi",
    "Unlimited FAQ": "Sınırsız SSS",
    "Question": "Soru",
    "question": "soru",
    "Answer": "Cevap",
    "answer": "cevap",
    "Frequently Asked Questions": "Sıkça Sorulan Sorular",
    "NO FAQ FOUND": "SSS BULUNAMADI",
    "No Faq Found": "SSS bulunamadı",
    # FEATURES
    "Features": "Özellikler",
    "Feature": "Özellik",
    "Add Feature": "Özellik Ekle",
    "Feature section updated successfully": "Özellik bölümü güncellendi",
    "Feature deleted successfully": "Özellik silindi",
    "Feature Updated successfully": "Özellik güncellendi",
    "Feature Per Listing": "İlan Başına Özellik",
    "Features Per Listing": "İlan Başına Özellikler",
    "Features  (Per Listing)": "Özellikler (İlan Başına)",
    "Feature Per Listing (Unlimited)": "İlan Başına Özellik (Sınırsız)",
    "Unlimited Feature": "Sınırsız Özellik",
    "Custom Features": "Özel Özellikler",
    "More Features": "Daha Fazla Özellik",
    "NO FEATURE FOUND": "ÖZELLİK BULUNAMADI",
    "No Feature Found": "Özellik bulunamadı",
    # AMENITIES
    "Amenities": "Olanaklar",
    "Amenitie Per Listing": "İlan Başına Olanak",
    "Amenities Per Listing": "İlan Başına Olanaklar",
    "Amenities (Per Listing)": "Olanaklar (İlan Başına)",
    "Amenities Per Listing(Unlimited)": "İlan Başına Olanak (Sınırsız)",
    "Add Amenitie": "Olanak Ekle",
    "Edit Amenitie": "Olanak Düzenle",
    "Aminite deleted successfully": "Olanak silindi",
    "Aminite stored successfully": "Olanak kaydedildi",
    "Aminite updated successfully": "Olanak güncellendi",
    "Aminities updated successfully": "Olanaklar güncellendi",
    "Unlimited Amenities": "Sınırsız Olanak",
    # PACKAGES
    "Packages": "Paketler",
    "Package": "Paket",
    "Add Package": "Paket Ekle",
    "Edit package": "Paketi Düzenle",
    "Current Package": "Mevcut Paket",
    "Next Package": "Sonraki Paket",
    "Add Current Package": "Mevcut Paket Ekle",
    "Add Next Package": "Sonraki Paket Ekle",
    "Change Current Package": "Mevcut Paketi Değiştir",
    "Change Next Package": "Sonraki Paketi Değiştir",
    "Current Package changed successfully": "Mevcut paket değiştirildi",
    "Next Package changed successfully": "Sonraki paket değiştirildi",
    "Current Package has been added successfully": "Mevcut paket eklendi",
    "Next Package has been added successfully": "Sonraki paket eklendi",
    "Current Package removed successfully": "Mevcut paket kaldırıldı",
    "Next Package removed successfully": "Sonraki paket kaldırıldı",
    "Term": "Süre",
    "term": "süre",
    "Lifetime": "Ömür Boyu",
    "lifetime": "ömür boyu",
    "Monthly": "Aylık",
    "monthly": "aylık",
    "Yearly": "Yıllık",
    "Trial": "Deneme",
    "Test Package": "Test Paketi",
    "Pricing": "Fiyatlandırma",
    "Pricing Filter": "Fiyat Filtresi",
    "Choose a Package term": "Paket süresi seçin",
    "If you purchase this package": "Bu paketi satın alırsanız",
    "If price is 0 , than it will appear as free": "Fiyat 0 ise ücretsiz görünür",
    "NO PACKAGE FOUND": "PAKET BULUNAMADI",
    "Details & Package": "Detaylar ve Paket",
    "Extend": "Uzat",
    "If you delete this package, all memberships under this package will be deleted": "Paketi silerseniz tüm üyelikler silinir",
    # LOCATIONS
    "Countries": "Ülkeler",
    "Country": "Ülke",
    "country": "ülke",
    "Country Name": "Ülke Adı",
    "Add Country": "Ülke Ekle",
    "Edit Country": "Ülkeyi Düzenle",
    "Country deleted successfully": "Ülke silindi",
    "Country stored successfully": "Ülke kaydedildi",
    "Country updated successfully": "Ülke güncellendi",
    "Enter Country": "Ülke girin",
    "Enter Country Name": "Ülke adı girin",
    "Select Country": "Ülke Seç",
    "State": "Eyalet",
    "States": "Eyaletler",
    "Add State": "Eyalet Ekle",
    "Edit State": "Eyaleti Düzenle",
    "Enter State": "Eyalet girin",
    "Enter State Name": "Eyalet adı girin",
    "Select State": "Eyalet Seç",
    "City": "Şehir",
    "Cities": "Şehirler",
    "city": "şehir",
    "Add City": "Şehir Ekle",
    "Edit City": "Şehri Düzenle",
    "City deleted successfully": "Şehir silindi",
    "City updated successfully": "Şehir güncellendi",
    "Enter City": "Şehir girin",
    "Enter City Name": "Şehir adı girin",
    "Select City": "Şehir Seç",
    "Select State/City": "Eyalet/Şehir Seç",
    "Location Section": "Konum Bölümü",
    "Location Section Status": "Konum Bölüm Durumu",
    "Location section updated successfully": "Konum bölümü güncellendi",
    "Search By Location": "Konuma Göre Ara",
    "Search specific location": "Belirli konum ara",
    "Use current location": "Mevcut konumu kullan",
    "Current location": "Mevcut konum",
    "Enter location": "Konum girin",
    "Enter Location": "Konum girin",
    "Map": "Harita",
    "Google Map": "Google Harita",
    "Google Map API": "Google Harita API",
    # HOME PAGE
    "Home Page": "Ana Sayfa",
    "Hero Section": "Hero Bölümü",
    "Call To Action Section": "Harekete Geçirici Bölüm",
    "Call To Action Section Status": "CTA Bölüm Durumu",
    "Call to action section updated successfully": "CTA bölümü güncellendi",
    "Counter Section": "Sayaç Bölümü",
    "Counter Informations": "Sayaç Bilgileri",
    "Counter Section Status": "Sayaç Bölüm Durumu",
    "Add Counter Information": "Sayaç Bilgisi Ekle",
    "Edit Counter Information": "Sayaç Bilgisini Düzenle",
    "Testimonials": "Referanslar",
    "Testimonial": "Referans",
    "Add Testimonial": "Referans Ekle",
    "Edit Testimonial": "Referansı Düzenle",
    "New testimonial added successfully": "Referans eklendi",
    "Client Name": "Müşteri Adı",
    "Client Image": "Müşteri Resmi",
    "Client Comment": "Müşteri Yorumu",
    "Client Occupation": "Müşteri Mesleği",
    "No Testimonial Found": "Referans Bulunamadı",
    "Work Process": "Çalışma Süreci",
    "Add Work Process": "Süreç Ekle",
    "Edit Work Process": "Süreci Düzenle",
    "New work process added successfully": "Süreç eklendi",
    "How It Works": "Nasıl Çalışır",
    "No Work Process Found": "Süreç Bulunamadı",
    "Information": "Bilgi",
    "Information deleted successfully": "Bilgi silindi",
    "Information stored successfully": "Bilgi kaydedildi",
    "Information updated successfully": "Bilgi güncellendi",
    "No Information Found": "Bilgi Bulunamadı",
    "What's Included": "Neler Dahil",
    "Services": "Hizmetler",
    # FOOTER
    "Footer": "Alt Bilgi",
    "Footer logo updated successfully": "Alt bilgi logosu güncellendi",
    "Quick Links": "Hızlı Bağlantılar",
    "Add Quick Link": "Hızlı Bağlantı Ekle",
    "Edit Quick Link": "Hızlı Bağlantıyı Düzenle",
    "New quick link added successfully": "Hızlı bağlantı eklendi",
    "Copyright Text": "Telif Hakkı Metni",
    "Useful Links": "Faydalı Bağlantılar",
    "Follow Us": "Bizi Takip Edin",
    "Our Address": "Adresimiz",
    # CUSTOM PAGES
    "Custom Pages": "Özel Sayfalar",
    "Custom Page": "Özel Sayfa",
    "Add Page": "Sayfa Ekle",
    "Edit Page": "Sayfayı Düzenle",
    "New page added successfully": "Sayfa eklendi",
    # CONTACT
    "Contact": "İletişim",
    "Contact Us": "Bize Ulaşın",
    "Contact Page": "İletişim Sayfası",
    "Contact Page Title": "İletişim Sayfası Başlığı",
    "Contact Information": "İletişim Bilgileri",
    "Contact Now": "Hemen İletişime Geç",
    "Contact Number": "İletişim Numarası",
    "contact_number": "iletişim numarası",
    "Enter Contact Number": "İletişim numarası girin",
    "email_address": "e-posta adresi",
    "A contact request was sent successfully": "İletişim talebi gönderildi",
    "Message": "Mesaj",
    "Message sent successfully": "Mesaj başarıyla gönderildi",
    "Message Sent Successfully": "Mesaj Başarıyla Gönderildi",
    "Message Information": "Mesaj Bilgisi",
    "Messages": "Mesajlar",
    "Message deleted successfully": "Mesaj silindi",
    "Message Submitted At": "Mesaj Gönderim Tarihi",
    "No Message Found": "Mesaj Bulunamadı",
    "Submit Message": "Mesaj Gönder",
    "Write Your Message": "Mesajınızı Yazın",
    "Subject": "Konu",
    "Enter Subject": "Konu girin",
    # FORMS
    "Forms": "Formlar",
    "Form Builder": "Form Oluşturucu",
    "Form Type": "Form Türü",
    "Form Types Guide": "Form Türleri Rehberi",
    "Form Guide": "Form Rehberi",
    "Form Inputs": "Form Girdileri",
    "Add Form": "Form Ekle",
    "Edit Form": "Formu Düzenle",
    "Form deleted successfully": "Form silindi",
    "Form updated successfully": "Form güncellendi",
    "Input Fields": "Girdi Alanları",
    "Input Type": "Girdi Türü",
    "Input Field Type": "Girdi Alan Türü",
    "Create Input Field": "Girdi Alanı Oluştur",
    "Edit Input Field": "Girdi Alanını Düzenle",
    "Label": "Etiket",
    "Placeholder": "Yer Tutucu",
    "Required": "Zorunlu",
    "Options": "Seçenekler",
    "Add Option": "Seçenek Ekle",
    "Enter Option": "Seçenek girin",
    "Checkbox": "Onay Kutusu",
    "Radio": "Radyo Düğmesi",
    "Textarea": "Metin Alanı",
    "Text": "Metin",
    "text": "metin",
    "Number": "Sayı",
    "Datepicker": "Tarih Seçici",
    "Table Reservation": "Masa Rezervasyonu",
    "Quote Request": "Teklif Talebi",
    "Claim Request": "Talep İsteği",
    "Enquiry Form": "Sorgu Formu",
    "Claim Request Form": "Talep Formu",
    "Each vendor can have only one quote request form per language": "Her satıcı dil başına bir teklif formuna sahip olabilir",
    "Each language should have only one claim request form": "Her dil için bir talep formu olmalıdır",
    "Leave it blank for admin's form": "Yönetici formu için boş bırakın",
    "Global": "Genel",
    "Local": "Yerel",
    "A form of this type already exists for this scope": "Bu türde bir form zaten mevcut",
    "Based on your selection, some input fields will be shown or hidden automatically": "Seçiminize göre bazı alanlar otomatik gösterilir/gizlenir",
    # SUPPORT TICKETS
    "Support Tickets": "Destek Talepleri",
    "Support Ticket Details": "Destek Talebi Detayları",
    "Ticket": "Talep",
    "Tickets": "Talepler",
    "All Tickets": "Tüm Talepler",
    "Closed Tickets": "Kapalı Talepler",
    "Total Tickets": "Toplam Talep",
    "Add a Ticket": "Talep Ekle",
    "Add a ticket": "Talep ekle",
    "Submit a Ticket": "Talep Gönder",
    "Create a Support Ticket": "Destek Talebi Oluştur",
    "Ticket ID": "Talep ID",
    "Ticket has been submitted successfully": "Talep başarıyla gönderildi",
    "Close Ticket": "Talebi Kapat",
    "Add Stuff to this support ticket successfully": "Personele başarıyla atandı",
    "Replies": "Yanıtlar",
    "Reply": "Yanıtla",
    # ADVERTISEMENTS
    "Advertisements": "Reklamlar",
    "Advertisement": "Reklam",
    "Add Advertisement": "Reklam Ekle",
    "Edit Advertisement": "Reklamı Düzenle",
    "Ad Type": "Reklam Türü",
    "Ad Slot": "Reklam Yuvası",
    "ad_type": "reklam türü",
    "Advertisement deleted successfully": "Reklam silindi",
    "Advertisement Resolution": "Reklam Çözünürlüğü",
    "Advertisements deleted successfully": "Reklamlar silindi",
    "Advertisement Type": "Reklam Türü",
    "Advertisement updated successfully": "Reklam güncellendi",
    "Advertise settings updated successfully": "Reklam ayarları güncellendi",
    "New advertisement added successfully": "Yeni reklam eklendi",
    "All Advertisements": "Tüm Reklamlar",
    # POPUPS
    "Announcement Popups": "Duyuru Popupları",
    "Popup": "Popup",
    "Add Popup": "Popup Ekle",
    "New popup added successfully": "Popup eklendi",
    "All activated popups will be appear in UI according to serial number.": "Aktif popuplar sıra numarasına göre görünür.",
    "If there are multiple active popups, then popups will be shown in UI according to serial number.": "Birden fazla popup sıra numarasına göre gösterilir.",
    # SOCIAL
    "Social Media": "Sosyal Medya",
    "Social Link": "Sosyal Bağlantı",
    "Social Links": "Sosyal Bağlantılar",
    "Add Social Media": "Sosyal Medya Ekle",
    "Edit Social Media": "Sosyal Medyayı Düzenle",
    "New social media added successfully": "Sosyal medya eklendi",
    "Social Links Per Listing": "İlan Başına Sosyal Bağlantı",
    "Social Links Per Listing(Unlimited)": "Sosyal Bağlantı (Sınırsız)",
    "Unlimited Social Links": "Sınırsız Sosyal Bağlantı",
    "Facebook": "Facebook",
    "Twitter": "Twitter",
    "Linkedin": "LinkedIn",
    "WhatsApp": "WhatsApp",
    "Telegram": "Telegram",
    "Messenger": "Messenger",
    "Tawk.To": "Tawk.To",
    # SETTINGS
    "Basic Settings": "Temel Ayarlar",
    "General Settings": "Genel Ayarlar",
    "General settings update Successfully": "Genel ayarlar güncellendi",
    "Email Settings": "E-posta Ayarları",
    "Email Status": "E-posta Durumu",
    "Email status updated successfully": "E-posta durumu güncellendi",
    "Mail": "Posta",
    "Mail From Admin": "Yöneticiden Posta",
    "Mail To Admin": "Yöneticiye Posta",
    "Mail Body": "Posta İçeriği",
    "Mail Subject": "Posta Konusu",
    "Mail Templates": "Posta Şablonları",
    "Mail template updated successfully": "Posta şablonu güncellendi",
    "Mail info updated successfully": "Posta bilgileri güncellendi",
    "Mail could not be sent": "Posta gönderilemedi",
    "Mail has been sent to all the subscribers": "Tüm abonelere posta gönderildi",
    "Mail Type": "Posta Türü",
    "A mail has been sent to your email address": "E-posta adresinize posta gönderildi",
    "A verification mail has been sent to your email address": "Doğrulama postası gönderildi",
    "Email Verificaiton": "E-posta Doğrulama",
    "Email Verification Link": "E-posta Doğrulama Bağlantısı",
    "From Email": "Gönderen E-posta",
    "From Name": "Gönderen Adı",
    "from_mail": "gönderen posta",
    "from_name": "gönderen adı",
    "Logo & Image": "Logo ve Resim",
    "Logo updated successfully": "Logo güncellendi",
    "Favicon updated successfully": "Favicon güncellendi",
    "Image updated successfully": "Resim güncellendi",
    "Appearance": "Görünüm",
    "Appearance updated successfully": "Görünüm güncellendi",
    "Theme": "Tema",
    "Breadcrumb": "İçerik Haritası",
    "Breadcrumb updated successfully": "İçerik haritası güncellendi",
    "Currency": "Para Birimi",
    "Currency updated successfully": "Para birimi güncellendi",
    "Base Currency Symbol": "Temel Para Birimi Sembolü",
    "Base Currency Symbol Position": "Sembol Konumu",
    "Base Currency Text": "Para Birimi Metni",
    "Base Currency Text Position": "Metin Konumu",
    "Base Currency Rate": "Para Birimi Kuru",
    "Language": "Dil",
    "Language Management": "Dil Yönetimi",
    "Language added successfully": "Dil başarıyla eklendi",
    "Language deleted successfully": "Dil başarıyla silindi",
    "Language updated successfully": "Dil başarıyla güncellendi",
    "Direction": "Yön",
    "direction": "yön",
    "Code": "Kod",
    "code": "kod",
    "Make Default": "Varsayılan Yap",
    "Default language cannot be delete": "Varsayılan dil silinemez",
    "Keywords": "Anahtar Kelimeler",
    "Keyword": "Anahtar Kelime",
    "keyword": "anahtar kelime",
    "Keywords of": "Anahtar Kelimeleri",
    "Keywords updated successfully": "Anahtar kelimeler güncellendi",
    "Edit Keyword": "Anahtar Kelimeyi Düzenle",
    "Edit Dashboard Keyword": "Panel Kelimesini Düzenle",
    "Edit Front Keyword": "Ön Yüz Kelimesini Düzenle",
    "Add Keyword for admin": "Yönetici için kelime ekle",
    "Add Keyword for front": "Ön yüz için kelime ekle",
    "Add New Keyword for dashboard": "Panel için yeni kelime",
    "Add New Keyword for front": "Ön yüz için yeni kelime",
    "A new keyword successfully": "Yeni kelime başarıyla",
    "Enter Keyword": "Kelime girin",
    "language": "dil",
    "language_id": "dil",
    "Meaning": "Anlam",
    "Translation": "Çeviri",
    "SEO": "SEO",
    "Meta Description": "Meta Açıklama",
    "Meta Keywords": "Meta Anahtar Kelimeler",
    "Meta Description For Home Page": "Ana Sayfa Meta Açıklama",
    "Meta Description For About Us Page": "Hakkımızda Meta Açıklama",
    "Meta Description For Blog Page": "Blog Meta Açıklama",
    "Meta Description For Contact Page": "İletişim Meta Açıklama",
    "Meta Description For FAQ Page": "SSS Meta Açıklama",
    "Meta Description For Listings Page": "İlanlar Meta Açıklama",
    "Meta Description For Pricing Page": "Fiyatlandırma Meta Açıklama",
    "Meta Description For Products Page": "Ürünler Meta Açıklama",
    "Meta Description For Vendors Page": "Satıcılar Meta Açıklama",
    "Meta Keywords For Home Page": "Ana Sayfa Meta Kelimeler",
    "Meta Keywords For About Us Page": "Hakkımızda Meta Kelimeler",
    "Meta Keywords For Blog Page": "Blog Meta Kelimeler",
    "Meta Keywords For Contact Page": "İletişim Meta Kelimeler",
    "Meta Keywords For FAQ Page": "SSS Meta Kelimeler",
    "Meta Keywords For Listings Page": "İlanlar Meta Kelimeler",
    "Meta Keywords For Pricing Page": "Fiyatlandırma Meta Kelimeler",
    "Meta Keywords For Products Page": "Ürünler Meta Kelimeler",
    "Meta Keywords For Vendors Page": "Satıcılar Meta Kelimeler",
    "Meta Description For Customer Login Page": "Müşteri Girişi Meta",
    "Meta Description For Customer Signup Page": "Müşteri Kayıt Meta",
    "Meta Description For Customer Forget Password Page": "Şifre Unuttum Meta",
    "Meta Description For Vendor Login Page": "Satıcı Girişi Meta",
    "Meta Description For Vendor Signup Page": "Satıcı Kayıt Meta",
    "Meta Description For Vendor Forget Password Page": "Satıcı Şifre Meta",
    "Meta Keywords For Customer Login Page": "Müşteri Girişi Kelimeler",
    "Meta Keywords For Customer Signup Page": "Müşteri Kayıt Kelimeler",
    "Meta Keywords For Customer Forget Password Page": "Şifre Unuttum Kelimeler",
    "Meta Keywords For Vendor Login Page": "Satıcı Girişi Kelimeler",
    "Meta Keywords For Vendor Signup Page": "Satıcı Kayıt Kelimeler",
    "Meta Keywords For Vendor Forget Password Page": "Satıcı Şifre Kelimeler",
    "Page Headings": "Sayfa Başlıkları",
    "Plugins": "Eklentiler",
    "Manage Plugins": "Eklentileri Yönet",
    "Update necessary plugins": "Gerekli eklentileri güncelle",
    "Google Recaptcha": "Google Recaptcha",
    "Maintenance Mode": "Bakım Modu",
    "Maintenance Status": "Bakım Durumu",
    "Maintenance Message": "Bakım Mesajı",
    "Maintenance Info updated successfully": "Bakım bilgisi güncellendi",
    "maintenance_msg": "bakım mesajı",
    "Cookie Alert": "Çerez Uyarısı",
    "Cookie Alert Status": "Çerez Uyarı Durumu",
    "Cookie Alert Text": "Çerez Uyarı Metni",
    "Cookie Alert Button Text": "Çerez Buton Metni",
    "Cookie alert info updated successfully": "Çerez uyarısı güncellendi",
    "cookie_alert_text": "çerez uyarı metni",
    "Push Notification": "Anlık Bildirim",
    "Firebase": "Firebase",
    "Upload Firebase Admin JSON": "Firebase Admin JSON Yükle",
    "Mobile Interface": "Mobil Arayüz",
    "Mobile App Settings": "Mobil Uygulama Ayarları",
    "Cron Job Command": "Cron Job Komutu",
    # CLAIM
    "Claim": "Talep Et",
    "Claimed": "Talep Edildi",
    "Claim Listing": "İlanı Talep Et",
    "Claim Request": "Talep İsteği",
    "Claim Requests": "Talep İstekleri",
    "Claim Request Information": "Talep Bilgisi",
    "Claim Request Details": "Talep Detayları",
    "Claim Request Workflow": "Talep İş Akışı",
    "Claim Status": "Talep Durumu",
    "Claim Link": "Talep Bağlantısı",
    "A unique claim link is automatically generated": "Benzersiz talep bağlantısı otomatik oluşturulur",
    "Link has a configurable expiration time": "Bağlantının yapılandırılabilir süresi var",
    "Click the claim link": "Talep bağlantısına tıklayın",
    "Approve Claim": "Talebi Onayla",
    "Needs Admin Approval": "Yönetici Onayı Gerekli",
    "Claim status will automatically update to Fulfilled": "Talep durumu otomatik Tamamlandı olur",
    "New claim requests start with pending status": "Yeni talepler beklemede başlar",
    "Already claimed, awaiting fulfillment": "Zaten talep edildi, tamamlanmayı bekliyor",
    "Fulfilled Status": "Tamamlanma Durumu",
    "Decision Pending": "Karar Bekleniyor",
    # WITHDRAW
    "Withdraw": "Para Çekme",
    "Withdrawals": "Para Çekme İşlemleri",
    "Withdraw Request": "Para Çekme Talebi",
    "Withdraw Requests": "Para Çekme Talepleri",
    "Add Payment Method": "Ödeme Yöntemi Ekle",
    "Edit Payment Method": "Ödeme Yöntemini Düzenle",
    "Method": "Yöntem",
    "Method Name": "Yöntem Adı",
    "Minimum Limit": "Minimum Limit",
    "Maximum Limit": "Maksimum Limit",
    "Minimum Spend": "Minimum Harcama",
    "Min Limit": "Min Limit",
    "Max Limit": "Maks Limit",
    "min_limit": "min limit",
    "max_limit": "maks limit",
    # PAYMENT GATEWAYS
    "PayPal": "PayPal",
    "Stripe": "Citibank",
    "Paystack": "Paystack",
    "Paytm": "Paytm",
    "Instamojo": "Instamojo",
    "Flutterwave": "Flutterwave",
    "Mollie": "Mollie",
    "Razorpay": "Razorpay",
    "MercadoPago": "MercadoPago",
    "Authorize.Net": "Authorize.Net",
    "Authorize.net": "Authorize.net",
    "Iyzico": "Iyzico",
    "Midtrans": "Midtrans",
    "MyFatoorah": "MyFatoorah",
    "Myfatoorah": "Myfatoorah",
    "Offline Payment": "Çevrimdışı Ödeme",
    "New offline payment gateway added successfully": "Çevrimdışı ödeme ağ geçidi eklendi",
    "Test Mode": "Test Modu",
    "Sandbox": "Sandbox",
    "API Key": "API Anahtarı",
    "Api Key": "API Anahtarı",
    "Secret Key": "Gizli Anahtar",
    "Public Key": "Açık Anahtar",
    "Client ID": "Client ID",
    "Client Secret": "Client Secret",
    "Merchant Id": "Merchant ID",
    "App ID": "App ID",
    "App Secret": "App Secret",
    "Token": "Token",
    "Encryption": "Şifreleme",
    "encryption": "şifreleme",
    "Server Key": "Sunucu Anahtarı",
    "Auth Token": "Auth Token",
    "API Login ID": "API Login ID",
    "API Endpoint": "API Endpoint",
    "Transaction Key": "İşlem Anahtarı",
    "Bypass Token": "Bypass Token",
    "Cancel URL": "İptal URL",
    "Redirect URL": "Yönlendirme URL",
    "Instructions": "Talimatlar",
    "Gateway Instructions": "Ağ Geçidi Talimatları",
    "For offline payments, you must manually verify and approve the payment from Subscription Log": "Çevrimdışı ödemeler Abonelik Kaydından manuel onaylanmalıdır",
    # SUBSCRIPTION
    "Subscription": "Abonelik",
    "Subscription Log": "Abonelik Kaydı",
    "Change payment status to Success": "Ödeme durumunu Başarılı yap",
    "Find the payment record": "Ödeme kaydını bul",
    # MENU BUILDER
    "Menu Builder": "Menü Oluşturucu",
    "Menu": "Menü",
    "Menus": "Menüler",
    "Edit Menu": "Menüyü Düzenle",
    "Add To Menus": "Menülere Ekle",
    "Built-In Menus": "Yerleşik Menüler",
    "Custom Menus": "Özel Menüler",
    "Menu Name": "Menü Adı",
    "Menu URL": "Menü URL",
    # ERROR & VALIDATION
    "Error": "Hata",
    "Warning": "Uyarı",
    "Alert": "Uyarı",
    "Success": "Başarılı",
    "Info": "Bilgi",
    "Notice": "Bildirim",
    "404 Error Page Title": "404 Hata Sayfası Başlığı",
    "404 not found": "404 bulunamadı",
    "The page you are looking for might have been moved, renamed, or might never existed.": "Aradığınız sayfa taşınmış veya silinmiş olabilir.",
    "Validation": "Doğrulama",
    "Please fill all fields": "Lütfen tüm alanları doldurun",
    "Please enter a valid email": "Geçerli bir e-posta girin",
    "Please enter a valid email address.": "Geçerli bir e-posta adresi girin.",
    "Passwords do not match": "Şifreler eşleşmiyor",
    "Please enter your name": "Adınızı girin",
    "Please enter your email": "E-postanızı girin",
    "Please enter your phone": "Telefonunuzu girin",
    "Please enter your message": "Mesajınızı girin",
    "Please fill all billing details": "Fatura bilgilerini doldurun",
    "Please select a payment method": "Ödeme yöntemi seçin",
    "Please select a rating": "Puan seçin",
    "Please write your review": "Yorumunuzu yazın",
    "Review must be at least 10 characters": "Yorum en az 10 karakter olmalı",
    "Review submitted successfully!": "Yorum başarıyla gönderildi!",
    "Failed to submit review": "Yorum gönderilemedi",
    "Please login first": "Önce giriş yapın",
    "Please login to continue": "Devam etmek için giriş yapın",
    "Please login": "Lütfen giriş yapın",
    "Please login first to claim this listing": "Talep için önce giriş yapın",
    "An error occurred": "Bir hata oluştu",
    "Sorry, an error has occured!": "Üzgünüz, bir hata oluştu!",
    "Something went wrong!": "Bir şeyler yanlış gitti!",
    "Invalid request!": "Geçersiz istek!",
    "Unauthorized": "Yetkisiz",
    "Forbidden": "Yasak",
    "Not found": "Bulunamadı",
    "Server Error": "Sunucu Hatası",
    # NOTIFICATIONS
    "Notifications": "Bildirimler",
    "Notification": "Bildirim",
    "New Notification": "Yeni Bildirim",
    # ABOUT
    "About": "Hakkımızda",
    "About Us": "Hakkımızda",
    "About Us Page Title": "Hakkımızda Sayfa Başlığı",
    "About section updated successfully": "Hakkımızda bölümü güncellendi",
    "About Company": "Şirket Hakkında",
    "about_company": "şirket hakkında",
    # LOGIN / REGISTER
    "Login with Facebook": "Facebook ile Giriş",
    "Login with Google": "Google ile Giriş",
    "Login via Facebook": "Facebook ile Giriş",
    "Login via Google": "Google ile Giriş",
    "Login Status": "Giriş Durumu",
    "Login Url": "Giriş URL",
    "Register": "Kayıt Ol",
    "forgot password": "şifremi unuttum",
    "Forgot Password": "Şifremi Unuttum",
    "Reset Password": "Şifreyi Sıfırla",
    "Send me a recovery link": "Kurtarma bağlantısı gönder",
    "Logged out successfully": "Başarıyla çıkış yapıldı",
    "Login successful!": "Giriş başarılı!",
    "Incorrect username or password": "Geçersiz kullanıcı adı veya şifre",
    "Sorry, your account has been deactivated": "Hesabınız devre dışı bırakıldı",
    "This email is already registered.": "Bu e-posta zaten kayıtlı.",
    "This username is already taken.": "Bu kullanıcı adı alınmış.",
    "This username is not allowed.": "Bu kullanıcı adına izin verilmiyor.",
    "Already have an account": "Zaten hesabınız var mı",
    "don't have an account": "hesabınız yok mu",
    "to Login": "Giriş Yap",
    "to Signup": "Kayıt Ol",
    "Sign up successfully completed.Please Login Now": "Kayıt tamamlandı. Lütfen giriş yapın.",
    "Please verify your email address": "E-posta adresinizi doğrulayın",
    "Password updated successfully": "Şifre başarıyla güncellendi",
    # GENERAL STRINGS
    "Search by Title": "Başlığa Göre Ara",
    "Search By Title": "Başlığa Göre Ara",
    "Find Now": "Şimdi Bul",
    "Apply Filters": "Filtreleri Uygula",
    "Apply": "Uygula",
    "Results": "Sonuçlar",
    "Showing": "Gösteriliyor",
    "Found": "Bulundu",
    "Unknown": "Bilinmiyor",
    "Unlimited": "Sınırsız",
    "Details": "Detaylar",
    "Detail": "Detay",
    "Description": "Açıklama",
    "description": "açıklama",
    "Content": "İçerik",
    "content": "içerik",
    "Configuration Rules": "Yapılandırma Kuralları",
    "Configure Expiration": "Süre Sonunu Yapılandır",
    "Title": "Başlık",
    "title": "başlık",
    "Subtitle": "Alt Başlık",
    "subtitle": "alt başlık",
    "Summary": "Özet",
    "Type": "Tür",
    "type": "tür",
    "Value": "Değer",
    "value": "değer",
    "Serial Number": "Sıra Numarası",
    "serial_number": "sıra numarası",
    "Order Number": "Sipariş Numarası",
    "order_number": "sipariş numarası",
    "Order": "Sıra",
    "order": "sıra",
    "Rating": "Puan",
    "rating": "puan",
    "Ratings": "Puanlar",
    "Reviews": "Yorumlar",
    "Review": "Yorum",
    "Write a Review": "Yorum Yaz",
    "Your Review": "Yorumunuz",
    "Your Rating": "Puanınız",
    "Submit Review": "Yorumu Gönder",
    "Customer Review": "Müşteri Yorumu",
    "Read More": "Devamını Oku",
    "Read more": "Devamını oku",
    "Read Less": "Daralt",
    "Show More": "Daha Fazla Göster",
    "Show more": "Daha fazla göster",
    "Show Less": "Daha Az Göster",
    "Show less": "Daha az göster",
    "More Details": "Daha Fazla Detay",
    "Click Here": "Buraya Tıklayın",
    "Go Here": "Buraya Git",
    "Search Wishlist": "İstek Listesinde Ara",
    "Search orders": "Siparişlerde Ara",
    "Filter Price": "Fiyat Filtrele",
    "Price : High to Low": "Fiyat: Yüksekten Düşüğe",
    "Price : Low to High": "Fiyat: Düşükten Yükseğe",
    "Date : Newest on top": "Tarih: En Yeni Üstte",
    "Date : Oldest on top": "Tarih: En Eski Üstte",
    "High to Low": "Yüksekten Düşüğe",
    "Low to High": "Düşükten Yükseğe",
    "Newest": "En Yeni",
    "Oldest": "En Eski",
    "Sort By": "Sırala",
    "Grid View": "Izgara Görünümü",
    "List View": "Liste Görünümü",
    "Gird": "Izgara",
    # CHARGES
    "Add Charge": "Ücret Ekle",
    "Edit Charge": "Ücreti Düzenle",
    "Charge deleted successfully": "Ücret silindi",
    "Charge stored successfully": "Ücret kaydedildi",
    "Charge updated successfully": "Ücret güncellendi",
    # FEATURE LISTING
    "Feature It": "Öne Çıkar",
    "Feature Active Date": "Öne Çıkma Başlangıç",
    "Feature Expiry Date": "Öne Çıkma Bitiş",
    "How Many Days Active": "Kaç Gün Aktif",
    # WISHLIST
    "Wishlist": "İstek Listesi",
    "Wishlists": "İstek Listeleri",
    "My Wishlist": "İstek Listem",
    "My Wishlists": "İstek Listelerim",
    "Wishlist Items": "İstek Listesi Öğeleri",
    "Save to Wishlist": "İstek Listesine Kaydet",
    "Added to your wishlist successfully": "İstek listesine eklendi",
    "Removed From wishlist successfully": "İstek listesinden kaldırıldı",
    "NO WISHLIST FOUND": "İSTEK LİSTESİ BULUNAMADI",
    "NO WISHLIST ITEM FOUND": "İSTEK LİSTESİ ÖĞESİ BULUNAMADI",
    "Your wishlist is empty": "İstek listeniz boş",
    "Listing Wishlists": "İlan İstek Listeleri",
    "Promos": "Promosyonlar",
    "Available": "Mevcut",
    "Available Now": "Şimdi Mevcut",
    "Avilable Now": "Şimdi Mevcut",
    "Thank you": "Teşekkürler",
    "I'm Looking for": "Arıyorum",
    "Share your experience...": "Deneyiminizi paylaşın...",
    "Enter name": "Ad girin",
    "Enter Name": "Ad girin",
    "Enter phone number": "Telefon girin",
    "Enter city": "Şehir girin",
    "Enter state": "Eyalet girin",
    "Enter zip code": "Posta kodu girin",
    "Enter country": "Ülke girin",
    "Enter address": "Adres girin",
    "Enter your name": "Adınızı girin",
    "Enter your phone": "Telefonunuzu girin",
    "Enter your state": "Eyaletinizi girin",
    "Enter your address": "Adresinizi girin",
    "Enter postcode": "Posta kodu girin",
    "Enter email": "E-posta girin",
    "Enter Email": "E-posta girin",
    "Enter password": "Şifre girin",
    "Enter username": "Kullanıcı adı girin",
    "Enter Full Name": "Ad soyad girin",
    "Enter Your Full Name": "Ad soyadınızı girin",
    "Enter Your Email": "E-postanızı girin",
    "Enter Your Email Address": "E-posta adresinizi girin",
    "Enter Title": "Başlık girin",
    "Enter Text": "Metin girin",
    "Enter Short Text": "Kısa metin girin",
    "Enter Summary": "Özet girin",
    "Enter Subtitle": "Alt başlık girin",
    "Enter Price": "Fiyat girin",
    "Enter Product Name": "Ürün adı girin",
    "Enter Shop Location": "Mağaza konumu girin",
    "Enter vendor name": "Satıcı adı girin",
    "Enter Amount": "Tutar girin",
    "Enter Details": "Detay girin",
    "Enter Phone": "Telefon girin",
    "Enter Subject": "Konu girin",
    "Enter URL": "URL girin",
    "Enter Location": "Konum girin",
    "Enter location": "Konum girin",
    "Enter Coupon Code": "Kupon kodu girin",
    "Enter Rating": "Puan girin",
    "Enter Min Price": "Min fiyat girin",
    "Enter Max Price": "Maks fiyat girin",
    "Enter Website Title": "Site başlığı girin",
    "Enter Start Date": "Başlangıç tarihi girin",
    "Enter End Date": "Bitiş tarihi girin",
    "Enter Days": "Gün sayısı girin",
    "Enter number of days": "Gün sayısı girin",
    "Enter Video URL": "Video URL girin",
    "Enter Your video url": "Video URL girin",
    "Enter Contact Number": "İletişim numarası girin",
    "Enter Contact Mail": "İletişim e-postası girin",
    "Enter Address": "Adres girin",
    "Enter City": "Şehir girin",
    "Enter City Name": "Şehir adı girin",
    "Enter State": "Eyalet girin",
    "Enter State Name": "Eyalet adı girin",
    "Enter Country": "Ülke girin",
    "Enter Country Name": "Ülke adı girin",
    "Enter Zip Code": "Posta kodu girin",
    "Enter Latitude": "Enlem girin",
    "Enter Longitude": "Boylam girin",
    "Enter Serial Number": "Sıra numarası girin",
    "Enter Category Serial Number": "Kategori sıra no girin",
    "Category Serial Number": "Kategori Sıra No",
    "Enter Author Name": "Yazar adı girin",
    "Enter Client Name": "Müşteri adı girin",
    "Enter Client Occupation": "Müşteri mesleği girin",
    "Enter Client Comment": "Müşteri yorumu girin",
    "Enter FAQ Serial Number": "SSS sıra no girin",
    "Enter Work Process Serial Number": "Süreç sıra no girin",
    "Enter Work Process Title": "Süreç başlığı girin",
    "Image Size 80x80": "Resim Boyutu 80x80",
    "Image Size 600x400": "Resim Boyutu 600x400",
    "JPG, PNG, JPEG, GIF, SVG images are allowed": "JPG, PNG, JPEG, GIF, SVG izin verilir",
    "only .zip file is allowed.": "sadece .zip dosyası izin verilir.",
    "Only .zip file is allowed.": "Sadece .zip dosyası izin verilir.",
    "Only .zip file is allowed": "Sadece .zip dosyası",
    "Max upload size 5 MB": "Maks yükleme 5 MB",
    "Max upload size is 20 MB": "Maks yükleme 20 MB",
    "Maximum Size": "Maksimum Boyut",
    "Maximum Size of Uploaded File": "Maks Yüklenen Dosya Boyutu",
    "File Size": "Dosya Boyutu",
    "Enter File Size": "Dosya boyutu girin",
    "Download Link": "İndirme Bağlantısı",
    "Enter Download Link": "İndirme bağlantısı girin",
    "Additional Reference": "Ek Referans",
    "Additional Reference(Optional)": "Ek Referans (İsteğe Bağlı)",
    "Link to View Order Details": "Sipariş Detaylarını Gör",
    "Modified by Admin": "Yönetici Tarafından Değiştirildi",
    "modified by Admin": "yönetici tarafından değiştirildi",
    "Guest User": "Misafir Kullanıcı",
    "Select date": "Tarih seç",
    "Select time": "Saat seç",
    "Crop Image": "Resmi Kırp",
    "Industry Type": "Sektör Türü",
    "Name of The Customer": "Müşteri Adı",
    "Name of Listing": "İlan Adı",
    "Name of Product": "Ürün Adı",
    "Name of enquirer": "Sorgulayan Adı",
    "Email address of enquirer": "Sorgulayan E-postası",
    "Message of enquirer": "Sorgulayan Mesajı",
    "Digital Product": "Dijital Ürün",
    "digital": "dijital",
    "Both (Marketplace & Listing)": "Her İkisi (Pazaryeri ve İlan)",
    "Marketplace": "Pazaryeri",
    "gender": "cinsiyet",
    "age": "yaş",
    "occupation": "meslek",
    "Save Place": "Yeri Kaydet",
    "Please verify that you are not a robot.": "Robot olmadığınızı doğrulayın.",
    "Captcha error! Try again later or contact site admin.": "Captcha hatası! Daha sonra tekrar deneyin.",
    "Expiration Reminder": "Süre Sonu Hatırlatıcı",
    "expiration_reminder": "süre sonu hatırlatıcı",
    "Terms": "Şartlar",
    "terms": "şartlar",
    # AI
    "AI Image Limit": "AI Resim Limiti",
    "AI Token Limit": "AI Token Limiti",
    "AI Content & Image Generator": "AI İçerik ve Resim Üretici",
    "AI Engine": "AI Motoru",
    "OpenAI": "OpenAI",
    "Gemini": "Gemini",
    # MOBILE APP
    "Mobile App Settings": "Mobil Uygulama Ayarları",
    "For mobile app display": "Mobil uygulama gösterimi için",
    "This image will be used in the mobile app interface.": "Bu resim mobil arayüzde kullanılacak.",
    "The category icon will not appear in the app, so please upload an image for app display.": "Kategori simgesi uygulamada görünmez, resim yükleyin.",
    "Banner Section": "Banner Bölümü",
    "Banner Title": "Banner Başlığı",
    "Enter banner title": "Banner başlığı girin",
    "Banner Button Text": "Banner Buton Metni",
    "Enter banner button text": "Banner buton metni girin",
    "Banner Button Url": "Banner Buton URL",
    "Enter banner button url": "Banner buton URL girin",
    "Banner Image": "Banner Resmi",
    "Section Titles": "Bölüm Başlıkları",
    "Enter Featured Listing Section Title": "Öne çıkan ilan başlığı girin",
    "Enter category title": "Kategori başlığı girin",
    "Update texts": "Metinleri güncelle",
    "Update general settings": "Genel ayarları güncelle",
    "Update payment gateways settings": "Ödeme ağ geçidi ayarlarını güncelle",
    "Update necessary plugins": "Gerekli eklentileri güncelle",
    "Upload the Firebase Admin SDK JSON file from your Firebase project.": "Firebase projenizden Admin SDK JSON yükleyin.",
    "You have a file, and you can change it by re-uploading it.": "Dosya var, yeniden yükleyerek değiştirebilirsiniz.",
    "Google Map Status": "Google Harita Durumu",
    "When plugins have Google Map credentials, they can be used.": "Eklentilerde Google Harita bilgileri varsa kullanılabilir.",
    "Go Here": "Buraya Git",
    "AZIM": "AZIM",
    "Note": "Not",
    "Important": "Önemli",
    "Publishable": "Yayınlanabilir",
    "The gallery images field is required.": "Galeri resimleri zorunludur.",
    "Google Map API Status": "Google Harita API Durumu",
    "Google map api updated successfully": "Google Harita API güncellendi",
    "If the Google Maps API is disabled:": "Google Maps API devre dışıysa:",
    "Google will not suggest locations under address inputs.": "Google adres girişlerinde konum önermez.",
    "After a location is seached, all the available listings which are located within this radius will be displayed.": "Konum arandıktan sonra yarıçap içindeki ilanlar gösterilir.",
    "Google AdSense": "Google AdSense",
    "Google Adsense Publisher ID": "Google Adsense Publisher ID",
    "google_adsense_publisher_id": "google adsense publisher id",
    "Facebook info updated successfully": "Facebook bilgisi güncellendi",
    "facebook_app_id": "facebook app id",
    "Google info updated successfully": "Google bilgisi güncellendi",
    "google_client_id": "google client id",
    "google_client_secret": "google client secret",
    "google_login_status": "google giriş durumu",
    "google_recaptcha_secret_key": "recaptcha gizli anahtar",
    "google_recaptcha_site_key": "recaptcha site anahtarı",
    "google_recaptcha_status": "recaptcha durumu",
    "google_map_api_key": "google harita api anahtarı",
    "google_map_api_key_status": "google harita api durumu",
    "Disqus": "Disqus",
    "Disqus Status": "Disqus Durumu",
    "Disqus Short Name": "Disqus Kısa Adı",
    "Disqus info updated successfully": "Disqus güncellendi",
    "disqus_short_name": "disqus kısa adı",
    "Messenger Status": "Messenger Durumu",
    "Messenger Direct Chat Link": "Messenger Sohbet Bağlantısı",
    "Messanger info updated successfully": "Messenger güncellendi",
    "If you enable Tawk.To, then you must disable WhatsApp": "Tawk.To etkinse WhatsApp devre dışı olmalı",
    "If you enable WhatsApp, then you must disable Tawk.To": "WhatsApp etkinse Tawk.To devre dışı olmalı",
    "whatsapp_number": "whatsapp numarası",
    "whatsapp_header_title": "whatsapp başlığı",
    "whatsapp_popup_message": "whatsapp popup mesajı",
    "tawkto_status": "tawkto durumu",
    "tawkto_direct_chat_link": "tawkto sohbet bağlantısı",
    "VAPID Public Key": "VAPID Açık Anahtar",
    "VAPID Private Key": "VAPID Gizli Anahtar",
    "Enter VAPID Public Key": "VAPID açık anahtar girin",
    "Enter VAPID Private Key": "VAPID gizli anahtar girin",
    "vapid_public_key": "vapid açık anahtar",
    "vapid_private_key": "vapid gizli anahtar",
    "Delay": "Gecikme",
    "delay": "gecikme",
    "milliseconds": "milisaniye",
    "Verifying payment...": "Ödeme doğrulanıyor...",
    "Pay with PayTabs": "PayTabs ile Öde",
    "No payment URL received": "Ödeme URL alınamadı",
    "Payment cancelled": "Ödeme iptal edildi",
    "Payment successful!": "Ödeme başarılı!",
    "Payment verification failed": "Ödeme doğrulama başarısız",
    "Payment page not available": "Ödeme sayfası mevcut değil",
    "Payment URL not available": "Ödeme URL mevcut değil",
    "Order completion failed": "Sipariş tamamlama başarısız",
    "Invalid payment data received": "Geçersiz ödeme verisi",
    "Invalid invoice data received": "Geçersiz fatura verisi",
    "Cannot open invoice URL": "Fatura URL açılamıyor",
    "External wallet payment initiated": "Harici cüzdan ödemesi başlatıldı",
    "Razorpay configuration is missing": "Razorpay yapılandırması eksik",
    "Complete Payment": "Ödemeyi Tamamla",
    "Failed to load products": "Ürünler yüklenemedi",
    "Failed to load product details": "Ürün detayı yüklenemedi",
    "Failed to load listing details": "İlan detayı yüklenemedi",
    "Failed to load categories": "Kategoriler yüklenemedi",
    "Failed to load checkout data": "Ödeme verisi yüklenemedi",
    "Failed to load payment page": "Ödeme sayfası yüklenemedi",
    "Failed to pick file": "Dosya seçilemedi",
    "Your cart is empty": "Sepetiniz boş",
    "No product data available": "Ürün verisi yok",
    "Product details not available": "Ürün detayı yok",
    "No listings match your filters": "Filtrelere uygun ilan yok",
    "No categories available": "Kategori yok",
    "Order not found": "Sipariş bulunamadı",
    "Total Listings": "Toplam İlan",
    "Total Orders": "Toplam Sipariş",
    "All Requests": "Tüm Talepler",
    "Aproved Requests": "Onaylanan Talepler",
    "Approved At": "Onaylanma Tarihi",
    "Approve Status": "Onay Durumu",
    # MESSAGES
    "Chat": "Sohbet",
    "Conversations": "Konuşmalar",
    "Send Message": "Mesaj Gönder",
    # STATS
    "Statistics": "İstatistikler",
    "Reports": "Raporlar",
    "Analytics": "Analitik",
    "Overview": "Genel Bakış",
    # MISC MESSAGES
    "Your transaction was successful": "İşleminiz başarılı",
    "Your transaction request was received and sent for review": "İşlem talebiniz incelenmeye alındı",
    "We have sent you a mail with an invoice": "Faturalı posta gönderdik",
    "We answer every request as quickly as we can": "Her talebe en kısa sürede yanıt veriyoruz",
    "usually within 24–48 hours": "genellikle 24–48 saat içinde",
    "Keep it blank, if you do not want to keep any minimum spend limit.": "Minimum harcama limiti istemiyorsanız boş bırakın.",
    "Background Color Code": "Arka Plan Renk Kodu",
    "Background Color Opacity": "Arka Plan Opaklığı",
    "background_color_opacity": "arka plan opaklığı",
    "background_image": "arka plan resmi",
    "benifit_section_title": "fayda bölüm başlığı",
    "blog_section_button_text": "blog buton metni",
    "blog_section_title": "blog bölüm başlığı",
    "city_section_title": "şehir bölüm başlığı",
    "feature_image": "özellik resmi",
    "featured_image": "öne çıkan resim",
    "featured_section_text": "öne çıkan bölüm metni",
    "featured_section_title": "öne çıkan bölüm başlığı",
    "gallery images": "galeri resimleri",
    "icon": "simge",
    "image": "resim",
    "logo": "logo",
    "favicon": "favicon",
    "mail_address": "posta adresi",
    "mail_body": "posta içeriği",
    "mail_subject": "posta konusu",
    "mobile": "mobil",
    "photo": "fotoğraf",
    "slider_images": "slider resimleri",
    "secondary_color": "ikincil renk",
    "primary_color": "birincil renk",
    "preloader": "ön yükleyici",
    "radius": "yarıçap",
    "role_id": "rol",
    "smtp_host": "smtp sunucu",
    "smtp_port": "smtp port",
    "smtp_username": "smtp kullanıcı",
    "smtp_password": "smtp şifre",
    "sandbox_check": "sandbox kontrol",
    "test_mode": "test modu",
    "transaction_key": "işlem anahtarı",
    "public_key": "açık anahtar",
    "short_text": "kısa metin",
    "website_title": "site başlığı",
    "testimonial_section_title": "referans bölüm başlığı",
    "number_of_images_per_listing": "ilan başına resim",
    "number_of_listing": "ilan sayısı",
    "number_of_amenities_per_listing": "ilan başına olanak",
    "number_of_social_links": "sosyal bağlantı sayısı",
    "number_of_faq": "sss sayısı",
    "number_of_products": "ürün sayısı",
    "number_of_images_per_products": "ürün başına resim",
    "payment_method": "ödeme yöntemi",
    "payment_status": "ödeme durumu",
    "Enter new line to seperate features": "Özellikleri ayırmak için yeni satır",
    "Enter Package title": "Paket başlığı girin",
    "Enter Package price": "Paket fiyatı girin",
    "Enter Short Description": "Kısa açıklama girin",
    "Enter Short Text": "Kısa metin girin",
    "Enter Summary": "Özet girin",
    "Enter Text": "Metin girin",
    "Enter Title": "Başlık girin",
    "Enter Mail Subject": "Posta konusu girin",
    "Enter Mail Body Format": "Posta içerik formatı girin",
    "Enter Username": "Kullanıcı adı girin",
    "Enter Password": "Şifre girin",
    "Enter Phone": "Telefon girin",
    "Enter Phone Number": "Telefon numarası girin",
    "Enter Email": "E-posta girin",
    "Enter Email Address": "E-posta adresi girin",
    "Enter Name": "Ad girin",
    "Enter First Name": "Ad girin",
    "Enter Last Name": "Soyad girin",
    "Enter Quick Link Title": "Hızlı bağlantı adı girin",
    "Enter Quick Link URL": "Hızlı bağlantı URL girin",
    "Enter Coupon Code": "Kupon kodu girin",
    "Enter Rating": "Puan girin",
    "Enter Withdraw Maximum Limit": "Maks çekme limiti girin",
    "Enter Withdraw Minimum Limit": "Min çekme limiti girin",
    "Enter URL of Social Media Account": "Sosyal medya URL girin",
    "Enter Button Name": "Buton adı girin",
    "Enter Button Text": "Buton metni girin",
    "Enter Button URL": "Buton URL girin",
    "Enter Button text": "Buton metni girin",
    "Enter Form Name": "Form adı girin",
    "Enter Input Label": "Girdi etiketi girin",
    "Enter Input Placeholder": "Yer tutucu girin",
    "Enter Menu Name": "Menü adı girin",
    "Enter Menu URL": "Menü URL girin",
    "Enter Meta Description": "Meta açıklama girin",
    "Enter Meta Keywords": "Meta kelimeler girin",
    "Enter Method Name": "Yöntem adı girin",
    "Enter Minimum Spend": "Min harcama girin",
    "Enter Payment Gateway Name": "Ağ geçidi adı girin",
    "Enter Percentage Charge": "Yüzdelik ücret girin",
    "Enter Product Current Price": "Güncel fiyat girin",
    "Enter Product Previous Price": "Önceki fiyat girin",
    "Enter Product Stock": "Stok girin",
    "Enter Push Notification Title": "Bildirim başlığı girin",
    "Enter Question": "Soru girin",
    "Enter Answer": "Cevap girin",
    "Enter Redirect URL": "Yönlendirme URL girin",
    "Enter Role Name": "Rol adı girin",
    "Enter Shipping Charge": "Kargo ücreti girin",
    "Enter Video URL": "Video URL girin",
    "Enter Your video url": "Video URL girin",
    "Enter Google Adsense Publisher ID": "Google Adsense ID girin",
    "Enter Ad Slot": "Reklam yuvası girin",
    "Enter Gateway Instructions": "Ağ geçidi talimatı girin",
    "Enter Amenity Title": "Olanak adı girin",
    "Enter Coupon Name": "Kupon adı girin",
    "Enter Coupon Value": "Kupon değeri girin",
    "Enter Fixed Charge": "Sabit ücret girin",
    "Enter Website Title": "Site başlığı girin",
    "Enter Number of Listings": "İlan sayısı girin",
    "Enter Number of Products": "Ürün sayısı girin",
    "Enter Number of image per Listing": "İlan başına resim girin",
    "Enter Number of Images per Product": "Ürün başına resim girin",
    "Enter Number of Amenities per Listing": "İlan başına olanak girin",
    "Enter Number of Features per Listing": "İlan başına özellik girin",
    "Enter Number of FAQs per Listing": "İlan başına SSS girin",
    "Enter Number of Social Links per Listing": "İlan başına sosyal bağlantı girin",
    "Enter Number of Products per Listing": "İlan başına ürün girin",
    "Enter 999999 , then it will appear as unlimited": "Sınırsız için 999999 girin",
    "Egypt": "Mısır",
    "Iraq": "Irak",
    "Jordan": "Ürdün",
    "hero_section_title": "hero bölüm başlığı",
    "hero_section_subtitle": "hero bölüm alt başlığı",
    "counter_section_video_link": "sayaç bölüm video bağlantısı",
    "call_to_action_section_title": "cta bölüm başlığı",
    "call_to_action_button_url": "cta buton url",
    "call_to_action_section_btn": "cta bölüm butonu",
    "Citibank": "PayPal",
    "CVC Number": "CVC Numarası",
    "Card Number": "Kart Numarası",
    "Expiry Month": "Son Kullanma Ayı",
    "Expiry Year": "Son Kullanma Yılı",
    "Card Code": "Kart Kodu",
    "open": "açık",
    "Open": "Açık",
    "off": "indirim",
    "royal": "royal",
    "author": "yazar",
    "No Link Found": "Bağlantı Bulunamadı",
    "No Partner Found": "Ortak Bulunamadı",
    "No Partner Information Found": "Ortak Bilgisi Bulunamadı",
    "Sorry, you are offline": "Çevrimdışısınız",
    "Specifications": "Özellikler",
    "Search by name": "İsme göre ara",
    "Search Here": "Burada ara...",
    "Search Menu Here": "Menüde ara...",
    "Search by title": "Başlığa göre ara",
    "Search by name...": "İsme göre ara...",
    "Search by Category": "Kategoriye göre ara",
    "Search By Email ID": "E-postaya göre ara",
    "Search By Username": "Kullanıcı adına göre ara",
    "Search By Username or Email ID": "Kullanıcı adı veya e-postaya göre ara",
    "Search by Username": "Kullanıcı adına göre ara",
    "Search by Transaction ID": "İşlem ID'ye göre ara",
    "Search by transaction id...": "İşlem ID'ye göre ara...",
    "Search by subject or email": "Konu veya e-postaya göre ara",
    "Search by order number...": "Sipariş no'ya göre ara...",
    "Search products": "Ürünlerde ara",
    "Search messages...": "Mesajlarda ara...",
    "Search withdraws": "Para çekmede ara",
    "Search withdraw id or method name": "Çekme ID veya yöntem ara",
    "Search by Approve Status": "Onay durumuna göre ara",
    "Try changing the search or filter, or create a new ticket.": "Aramayı değiştirin veya yeni talep oluşturun.",
    "Radius-base searchings will be disabled.": "Yarıçap tabanlı arama devre dışı.",
    "Drag & drop to sort the input fields of this form": "Sıralamak için sürükleyip bırakın",
    "Drag & Drop the input fields to change the order number": "Sıra numarası için sürükleyip bırakın",
    "Click on the dropdown icon to select a icon.": "Simge seçmek için açılır menüye tıklayın.",
    "Click on the dropdown icon to select an icon": "Simge seçmek için açılır menüye tıklayın",
    "Exclusive": "Hariç",
    "Inclusive": "Dahil",
    "product_tax_amount": "ürün vergisi",
    "Button Name": "Buton Adı",
    "current_price": "güncel fiyat",
    "Remove": "Kaldır",
    "feature": "özellik",
    "NO VENDOR FOUND": "SATICI BULUNAMADI",
    "NO LISTING FOUND": "İLAN BULUNAMADI",
    "NO PRODUCT FOUND": "ÜRÜN BULUNAMADI",
    "NO POST FOUND": "YAZI BULUNAMADI",
    "NO REVIEW FOUND": "YORUM BULUNAMADI",
    "NO PACKAGE FOUND": "PAKET BULUNAMADI",
    "1 stars and above": "1 yıldız ve üzeri",
    "2 stars and above": "2 yıldız ve üzeri",
    "3 stars and above": "3 yıldız ve üzeri",
    "4 stars and above": "4 yıldız ve üzeri",
    "1 star and higher": "1 yıldız ve üzeri",
    "2 stars and higher": "2 yıldız ve üzeri",
    "3 stars and higher": "3 yıldız ve üzeri",
    "4 stars and higher": "4 yıldız ve üzeri",
    "5 stars": "5 yıldız",
    "Star": "Yıldız",
    "star": "yıldız",
    "Price Not Mentioned": "Fiyat Belirtilmemiş",
    "Enter Name": "Ad girin",
    "Only .zip file is allowed": "Sadece .zip dosyası",
    "The email field is required.": "E-posta zorunludur.",
    "The password field is required.": "Şifre zorunludur.",
    "The password confirmation does not match.": "Şifre onayı eşleşmiyor.",
    "The password must be at least 6 characters.": "Şifre en az 6 karakter olmalı.",
    "The username field is required.": "Kullanıcı adı zorunludur.",
    "This email is already registered.": "Bu e-posta zaten kayıtlı.",
    "This product has no review yet": "Henüz yorum yok",
    "This username is already taken.": "Bu kullanıcı adı alınmış.",
    "This username is not allowed.": "Bu kullanıcı adına izin verilmiyor.",
    "feature image": "özellik resmi",
    "feature_image": "özellik resmi",
    "about_company": "şirket hakkında",
    "Order": "Sipariş",
    "current_password": "mevcut şifre",
    "Edit Profile": "Profili Düzenle",
    "Manage Specifications": "Özellikleri Yönet",
    "Add Specification": "Özellik Ekle",
    "Edit Specification": "Özelliği Düzenle",
    "Specification": "Özellik",
    "Equipments": "Ekipmanlar",
    "Equipment": "Ekipman",
    "Equipment Bookings": "Ekipman Rezervasyonu",
    "No Equipment Found": "Ekipman Bulunamadı",
    "Transmission Types": "Şanzıman Türleri",
    "new_password": "yeni şifre",
    "new_password_confirmation": "yeni şifre onayı",
}

for fname in ["admin_tr.json", "tr.json"]:
    path = f"resources/lang/{fname}"
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    count = 0
    for key in data:
        if key in translations and data[key] != translations[key]:
            data[key] = translations[key]
            count += 1
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Translated {count} keys in {fname}")
