#!/usr/bin/env python3
"""Translate es.json and admin_es.json to Spanish"""

import json
import re

translations = {
    # COMMON UI
    "Dashboard": "Panel de Control",
    "Home": "Inicio",
    "Save": "Guardar",
    "Saved": "Guardado",
    "Cancel": "Cancelar",
    "cancel": "cancelar",
    "Close": "Cerrar",
    "Closed": "Cerrado",
    "closed": "cerrado",
    "Delete": "Eliminar",
    "Deleted successfully": "Eliminado correctamente",
    "Edit": "Editar",
    "Update": "Actualizar",
    "Create": "Crear",
    "Add": "Añadir",
    "Add New": "Añadir Nuevo",
    "View": "Ver",
    "View All": "Ver Todo",
    "View Details": "Ver Detalles",
    "View More": "Ver Más",
    "View Profile": "Ver Perfil",
    "Visit Profile": "Visitar Perfil",
    "View payment details": "Ver detalles de pago",
    "Back": "Volver",
    "Back to Lists": "Volver a la Lista",
    "Back to Home": "Volver al Inicio",
    "Back to Login": "Volver al Inicio de Sesión",
    "Submit": "Enviar",
    "Search": "Buscar",
    "Search...": "Buscar...",
    "Filter": "Filtrar",
    "Filters": "Filtros",
    "Reset": "Restablecer",
    "Reset All": "Restablecer Todo",
    "Clear": "Limpiar",
    "Import": "Importar",
    "Export": "Exportar",
    "Download": "Descargar",
    "Download File": "Descargar Archivo",
    "Upload": "Subir",
    "Choose": "Elegir",
    "Choose file": "Elegir archivo",
    "Choose Image": "Elegir Imagen",
    "Choose Photo": "Elegir Foto",
    "Browse": "Examinar",
    "File": "Archivo",
    "File not found": "Archivo no encontrado",
    "File Upload": "Subir Archivo",
    "File Download Link": "Enlace de Descarga",
    "Print": "Imprimir",
    "print": "imprimir",
    "Preview": "Vista Previa",
    "Publish": "Publicar",
    "Unpublish": "Despublicar",
    "Draft": "Borrador",
    "Archived": "Archivado",
    "Trash": "Papelera",
    "Restore": "Restaurar",
    "Copy": "Copiar",
    "Copy Link": "Copiar Enlace",
    "Move": "Mover",
    "Rename": "Renombrar",
    "Refresh": "Actualizar",
    "Reload": "Recargar",
    "Loading...": "Cargando...",
    "Loading": "Cargando",
    "Processing...": "Procesando...",
    "Please wait...": "Por favor espere...",
    "No data available": "No hay datos disponibles",
    "No results found": "No se encontraron resultados",
    "No items found": "No se encontraron elementos",
    "No records found": "No se encontraron registros",
    "Empty": "Vacío",
    "None": "Ninguno",
    "All": "Todos",
    "Select": "Seleccionar",
    "Select All": "Seleccionar Todo",
    "Deselect All": "Deseleccionar Todo",
    "Are you sure": "¿Está seguro",
    "Are you sure you want to logout?": "¿Está seguro de que desea cerrar sesión?",
    "Confirm": "Confirmar",
    "Confirm Delete": "Confirmar Eliminación",
    "Confirm Password": "Confirmar Contraseña",
    "Confirm New Password": "Confirmar Nueva Contraseña",
    "Confirm New Password*": "Confirmar Nueva Contraseña*",
    "Confirm your new password": "Confirme su nueva contraseña",
    "Yes": "Sí",
    "No": "No",
    "Next": "Siguiente",
    "Previous": "Anterior",
    "Finish": "Finalizar",
    "Skip": "Saltar",
    "Continue": "Continuar",
    "Proceed": "Continuar",
    "Go Back": "Volver",
    "Go to Login": "Ir a Inicio de Sesión",
    "Login": "Iniciar Sesión",
    "Logout": "Cerrar Sesión",
    "Register": "Registrarse",
    "Signup": "Registrarse",
    "Sign In": "Iniciar Sesión",
    "Sign Out": "Cerrar Sesión",
    "Sign Up": "Registrarse",
    "Forgot Password?": "¿Olvidó su Contraseña?",
    "Forgot password": "Olvidó su contraseña",
    "Forget Password": "Olvidar Contraseña",
    "Reset Password": "Restablecer Contraseña",
    "Change Password": "Cambiar Contraseña",
    "Change Password Page Title": "Título de Cambiar Contraseña",
    "Current Password": "Contraseña Actual",
    "New Password": "Nueva Contraseña",
    "Password": "Contraseña",
    "Remember Me": "Recordarme",
    "Email": "Correo Electrónico",
    "Email Address": "Dirección de Correo",
    "Email ID": "ID de Correo",
    "Username": "Nombre de Usuario",
    "Username/Email*": "Usuario/Correo*",
    "Password*": "Contraseña*",
    "Email*": "Correo*",
    "Confirm Password*": "Confirmar Contraseña*",
    "New Password*": "Nueva Contraseña*",
    "Current Password*": "Contraseña Actual*",
    "Lost your password": "¿Perdió su contraseña?",
    "Name": "Nombre",
    "First Name": "Nombre",
    "Last Name": "Apellido",
    "Full Name": "Nombre Completo",
    "Phone": "Teléfono",
    "Phone Number": "Número de Teléfono",
    "Mobile": "Móvil",
    "Address": "Dirección",
    "City": "Ciudad",
    "Enter city": "Ingresar ciudad",
    "Enter state": "Ingresar estado",
    "Enter zip code": "Ingresar código postal",
    "Enter country": "Ingresar país",
    "Enter address": "Ingresar dirección",
    "Enter your address": "Ingrese su dirección",
    "Enter postcode": "Ingrese código postal",
    "Enter shipping name": "Ingrese nombre de envío",
    "Enter shipping email": "Ingrese correo de envío",
    "Enter shipping phone": "Ingrese teléfono de envío",
    "Enter shipping state": "Ingrese estado de envío",
    "Enter shipping address": "Ingrese dirección de envío",
    "State": "Estado/Provincia",
    "Country": "País",
    "Zip Code": "Código Postal",
    "Postcode/Zip": "Código Postal",
    "Location": "Ubicación",
    "Latitude": "Latitud",
    "Longitude": "Longitud",
    "Website": "Sitio Web",
    "URL": "URL",
    "Link": "Enlace",
    "Image": "Imagen",
    "Images": "Imágenes",
    "Photo": "Foto",
    "Icon": "Icono",
    "Logo": "Logotipo",
    "Favicon": "Favicon",
    "Avatar": "Avatar",
    "Banner": "Banner",
    "Banner Image": "Imagen del Banner",
    "Background Image": "Imagen de Fondo",
    "Gallery": "Galería",
    "Gallery Images": "Imágenes de Galería",
    "Slider": "Slider",
    "Video": "Video",
    "Audio": "Audio",
    "Document": "Documento",
    "Attachment": "Adjunto",
    "Featured Image": "Imagen Destacada",
    "Thumbnail": "Miniatura",
    "Preview Image": "Imagen de Vista Previa",
    "Cover Image": "Imagen de Portada",
    "Image Size": "Tamaño de Imagen",
    "Max upload size 5 MB": "Tamaño máximo 5 MB",
    "Max upload size is 20 MB": "El tamaño máximo es 20 MB",

    # STATUSES
    "Status": "Estado",
    "Active": "Activo",
    "Inactive": "Inactivo",
    "Deactive": "Desactivar",
    "Enable": "Habilitar",
    "Disable": "Deshabilitar",
    "Enabled": "Habilitado",
    "Disabled": "Deshabilitado",
    "Show": "Mostrar",
    "Hide": "Ocultar",
    "Hide/Show": "Ocultar/Mostrar",
    "Show less": "Mostrar menos",
    "Show more": "Mostrar más",
    "Show Less": "Mostrar Menos",
    "Show More": "Mostrar Más",
    "On": "Activado",
    "Off": "Desactivado",
    "off": "desactivado",
    "Pending": "Pendiente",
    "pending": "pendiente",
    "Approved": "Aprobado",
    "approved": "aprobado",
    "Rejected": "Rechazado",
    "rejected": "rechazado",
    "Completed": "Completado",
    "completed": "completado",
    "processing": "procesando",
    "Published": "Publicado",
    "Unpublished": "No publicado",
    "Locked": "Bloqueado",
    "Unlocked": "Desbloqueado",
    "Verified": "Verificado",
    "Unverified": "No verificado",
    "Suspended": "Suspendido",
    "Banned": "Bloqueado",
    "Expired": "Expirado",
    "Fulfilled": "Cumplido",
    "Default": "Por Defecto",
    "(Default)": "(Por Defecto)",
    "Blank": "Vacío",
    "Never Activated": "Nunca Activado",
    "Open": "Abierto",
    "Available": "Disponible",
    "Available Now": "Disponible Ahora",
    "Avilable Now": "Disponible Ahora",
    "Delivered": "Entregado",
    "Cancelled": "Cancelado",
    "Decline": "Rechazar",
    "Declined": "Rechazado",
    "Failed": "Falló",
    "Approved At": "Aprobado el",
    "Featured": "Destacado",
    "Approve Status": "Estado de Aprobación",
    "Aproved Requests": "Solicitudes Aprobadas",
    "All Requests": "Todas las Solicitudes",

    # ACTIONS
    "Action": "Acción",
    "Actions": "Acciones",
    "Manage": "Gestionar",
    "Manage Form": "Gestionar Formulario",
    "Manage Listings": "Gestionar Anuncios",
    "Manage Plugins": "Gestionar Plugins",
    "Manage Products": "Gestionar Productos",
    "Manage Social Link": "Gestionar Enlace Social",
    "Clone": "Clonar",
    "Clone for": "Clonar para",
    "Duplicate": "Duplicar",
    "Assign": "Asignar",
    "Assigned Staff": "Personal Asignado",
    "Assigned to": "Asignado a",
    "Assign Staff": "Asignar Personal",
    "Assing To": "Asignar a",
    "Send": "Enviar",
    "Send message": "Enviar mensaje",
    "Send Email": "Enviar Correo",
    "Send SMS": "Enviar SMS",
    "Send Notification": "Enviar Notificación",
    "Reply": "Responder",
    "Report": "Informe",
    "Download Report": "Descargar Informe",
    "Generate Report": "Generar Informe",
    "Bulk Action": "Acción Masiva",
    "Bulk Delete": "Eliminación Masiva",
    "Bulk Update": "Actualización Masiva",
    "Import Data": "Importar Datos",
    "Export Data": "Exportar Datos",
    "Export CSV": "Exportar CSV",
    "Export Excel": "Exportar Excel",
    "Export PDF": "Exportar PDF",
    "Print Invoice": "Imprimir Factura",
    "Share": "Compartir",
    "Share Now": "Compartir Ahora",
    "Share on": "Compartir en",
    "Share_On": "Compartir_En",
    "Remove": "Eliminar",
    "Calculate": "Calcular",
    "Generate": "Generar",
    "Generate All": "Generar Todo",
    "Generate All Content": "Generar Todo el Contenido",
    "Generate All Contents": "Generar Todos los Contenidos",
    "Generate Image": "Generar Imagen",
    "Generate Images": "Generar Imágenes",
    "Generate Slider Images": "Generar Imágenes del Slider",
    "Generate Gallery Images": "Generar Imágenes de Galería",
    "Generate With AI": "Generar con IA",
    "Generating": "Generando",
    "Generating...": "Generando...",
    "Creating…": "Creando…",

    # DATE & TIME
    "Date": "Fecha",
    "date": "fecha",
    "Time": "Hora",
    "Day": "Día",
    "day": "día",
    "Days": "Días",
    "Days For": "Días Para",
    "Month": "Mes",
    "month": "mes",
    "Year": "Año",
    "year": "año",
    "Hour": "Hora",
    "hour": "hora",
    "Minute": "Minuto",
    "minute": "minuto",
    "Second": "Segundo",
    "second": "segundo",
    "Today": "Hoy",
    "Yesterday": "Ayer",
    "Tomorrow": "Mañana",
    "This Week": "Esta Semana",
    "Last Week": "Semana Pasada",
    "This Month": "Este Mes",
    "Last Month": "Mes Pasado",
    "This Year": "Este Año",
    "Last Year": "Año Pasado",
    "Start Date": "Fecha de Inicio",
    "End Date": "Fecha de Fin",
    "Start Time": "Hora de Inicio",
    "End Time": "Hora de Fin",
    "Expire Date": "Fecha de Vencimiento",
    "Expire Month": "Mes de Vencimiento",
    "Expire Year": "Año de Vencimiento",
    "Expiry Month": "Mes de Vencimiento",
    "Expiry Year": "Año de Vencimiento",
    "Expires": "Vence",
    "Created": "Creado",
    "Created At": "Fecha de Creación",
    "Updated At": "Fecha de Actualización",
    "Deleted At": "Fecha de Eliminación",
    "Calendar": "Calendario",
    "Schedule": "Programar",
    "Duration": "Duración",
    "12 Hour": "12 Horas",
    "24 Hour": "24 Horas",
    "Monday": "Lunes",
    "Tuesday": "Martes",
    "Wednesday": "Miércoles",
    "Thursday": "Jueves",
    "Friday": "Viernes",
    "Saturday": "Sábado",
    "Sunday": "Domingo",
    "From": "De",
    "In": "En",

    # USERS & ADMIN
    "User": "Usuario",
    "Users": "Usuarios",
    "Add User": "Añadir Usuario",
    "Edit User": "Editar Usuario",
    "User Management": "Gestión de Usuarios",
    "Registered Users": "Usuarios Registrados",
    "User List": "Lista de Usuarios",
    "User Details": "Detalles del Usuario",
    "User Profile": "Perfil de Usuario",
    "User Role": "Rol de Usuario",
    "User Status": "Estado del Usuario",
    "Account": "Cuenta",
    "Account Information": "Información de la Cuenta",
    "Account Status": "Estado de la Cuenta",
    "Account status updated successfully": "Estado de la cuenta actualizado correctamente",
    "Account Settings": "Configuración de la Cuenta",
    "Profile": "Perfil",
    "Edit Profile": "Editar Perfil",
    "Edit Your Profile": "Editar tu Perfil",
    "Edit Profile Page Title": "Título de Editar Perfil",
    "Update Profile": "Actualizar Perfil",
    "Customer": "Cliente",
    "Customer Email": "Correo del Cliente",
    "Customer Info": "Información del Cliente",
    "Customer Information": "Información del Cliente",
    "Customer Review": "Opinión del Cliente",
    "Customers can submit queries through this form": "Los clientes pueden enviar consultas a través de este formulario",
    "customer_email": "correo del cliente",
    "customer_name": "nombre del cliente",
    "customer_phone": "teléfono del cliente",
    "Subscribers": "Suscriptores",
    "Subscribe": "Suscribirse",
    "Subscribe Us": "Suscríbete",
    "Subscribe to Our Newsletter": "Suscríbete a nuestro Boletín",
    "Stay update with us and get offer": "Manténgase actualizado y reciba ofertas",
    "Member since": "Miembro desde",
    "Member details": "Detalles del miembro",
    "Membership": "Membresía",
    "Membership Request Sent.": "Solicitud de Membresía Enviada.",
    "Monthly Package Purchase": "Compra de Paquete Mensual",
    "Month wise registered users": "Usuarios registrados por mes",
    "Month wise visitors": "Visitantes por mes",
    "Monthly Listing Posts": "Anuncios Mensuales",
    "Identity Number": "Número de Identidad",
    "Guest User": "Usuario Invitado",

    # ADMIN
    "Admin": "Administrador",
    "Admins": "Administradores",
    "Super Admin": "Super Administrador",
    "Add Admin": "Añadir Administrador",
    "Edit Admin": "Editar Administrador",
    "Admin Management": "Gestión de Administradores",
    "Admin deleted successfully": "Administrador eliminado correctamente",
    "Admin updated successfully": "Administrador actualizado correctamente",
    "New admin added successfully": "Nuevo administrador añadido correctamente",
    "Admin action required": "Se requiere acción del administrador",
    "Admin Approval Notice": "Aviso de Aprobación del Administrador",
    "Admin Earnings": "Ganancias del Administrador",
    "Admin Forms": "Formularios de Administrador",
    "Admin can also create quote request forms for each language": "El administrador puede crear formularios de solicitud para cada idioma",
    "Role": "Rol",
    "Roles": "Roles",
    "Add Role": "Añadir Rol",
    "Edit Role": "Editar Rol",
    "Role Management": "Gestión de Roles",
    "New role added successfully": "Nuevo rol añadido correctamente",
    "Permissions": "Permisos",
    "Permission": "Permiso",
    "First delete all the admins of this role": "Primero elimine todos los administradores de este rol",

    # VENDOR
    "Vendor": "Proveedor",
    "Vendors": "Proveedores",
    "Add vendor": "Añadir Proveedor",
    "Add Vendor Successfully": "Proveedor Añadido Correctamente",
    "Edit Vendor": "Editar Proveedor",
    "Vendor Management": "Gestión de Proveedores",
    "Registered Vendors": "Proveedores Registrados",
    "Vendor Details": "Detalles del Proveedor",
    "Vendor Profile Available": "Perfil de Proveedor Disponible",
    "Vendor username": "Usuario del proveedor",
    "Vendor Info": "Información del Proveedor",
    "Select Vendor": "Seleccionar Proveedor",
    "Contact Vendor": "Contactar Proveedor",
    "if you do not select any vendor, then this Listing will be listed for Admin": "si no selecciona un proveedor, el anuncio será del Administrador",
    "If no vendor is selected, this will be considered as Admin": "Si no se selecciona proveedor, se considerará del Administrador",
    "Enter vendor name": "Ingrese nombre del proveedor",
    "Vendor name/username": "Nombre/usuario del proveedor",
    "Create your vendor account": "Cree su cuenta de proveedor",

    # LISTING
    "Listing": "Anuncio",
    "Listings": "Anuncios",
    "listings": "anuncios",
    "Add Listing": "Añadir Anuncio",
    "Edit Listing": "Editar Anuncio",
    "All Listings": "Todos los Anuncios",
    "Listings Management": "Gestión de Anuncios",
    "Listing Specifications": "Especificaciones del Anuncio",
    "Listing Title": "Título del Anuncio",
    "Listing Messages": "Mensajes del Anuncio",
    "Listing View": "Vista del Anuncio",
    "Listing Enquiry Form": "Formulario de Consulta",
    "Listing Images (Per Listing)": "Imágenes del Anuncio (por Anuncio)",
    "New Listing category added successfully": "Categoría de anuncio añadida correctamente",
    "Listing deleted successfully": "Anuncio eliminado correctamente",
    "Listing Updated successfully": "Anuncio actualizado correctamente",
    "Listing Approved successfully": "Anuncio aprobado correctamente",
    "Listing Rejected successfully": "Anuncio rechazado correctamente",
    "Listing Show successfully": "Anuncio mostrado correctamente",
    "Listing Hide successfully": "Anuncio ocultado correctamente",
    "Listing Featured successfully": "Anuncio destacado correctamente",
    "Listing Pending successfully": "Anuncio pendiente correctamente",
    "New Listing added successfully": "Nuevo anuncio añadido correctamente",
    "Listing Auto Approval": "Aprobación Automática de Anuncios",
    "Featured Listing Section": "Sección de Anuncios Destacados",
    "Featured Listings": "Anuncios Destacados",
    "Featured Listing Section Status": "Estado de Anuncios Destacados",
    "Featured Listing Section Title": "Título de Anuncios Destacados",
    "Featured Status": "Estado Destacado",
    "Latest Listing Section": "Últimos Anuncios",
    "Latest Listing Section Status": "Estado de Últimos Anuncios",
    "Listings limit reached or exceeded": "Límite de anuncios alcanzado o superado",
    "Listings Left": "Anuncios Restantes",
    "Listing (Unlimited)": "Anuncios (Ilimitados)",
    "Unlimited Listing": "Anuncios Ilimitados",
    "Images Per Listing (Unlimited)": "Imágenes por Anuncio (Ilimitadas)",
    "Image Per Listing": "Imagen por Anuncio",
    "Image Per Listings": "Imagen por Anuncios",
    "Images Per Listing": "Imágenes por Anuncio",
    "Images Per Listings": "Imágenes por Anuncios",
    "Unlimited Listing Image": "Imagen de Anuncio Ilimitada",
    "Listing Page Title": "Título de Página de Anuncios",
    "Business Hours": "Horario Comercial",
    "Business Hours Updated successfully": "Horario comercial actualizado correctamente",
    "Business Days": "Días Laborables",
    "Holiday": "Festivo",
    "Holiday Updated successfully": "Festivo actualizado correctamente",
    "Images / Listing": "Imágenes / Anuncio",
    "Total Listings": "Total de Anuncios",
    "No listing information found for": "No se encontró información del anuncio para",
    "Delete this listing?": "¿Eliminar este anuncio?",
    "Enter Featured Listing Section Title": "Ingrese Título de Anuncios Destacados",
    "More Details": "Más Detalles",
    "Save Place": "Guardar Lugar",

    # CLAIM
    "Claim": "Reclamar",
    "Claimed": "Reclamado",
    "Claim Listing": "Reclamar Anuncio",
    "Claim Request": "Solicitud de Reclamación",
    "Claim Requests": "Solicitudes de Reclamación",
    "Claim Request Form": "Formulario de Reclamación",
    "Claim Request Information": "Información de Reclamación",
    "Claim Request Details": "Detalles de Reclamación",
    "Claim Request Workflow": "Flujo de Reclamación",
    "Claim Status": "Estado de Reclamación",
    "Claim Link": "Enlace de Reclamación",
    "Claim Link expires in (days)": "Enlace de reclamación expira en (días)",
    "A unique claim link is automatically generated": "Se genera automáticamente un enlace único",
    "Click the claim link": "Haga clic en el enlace de reclamación",
    "Approve Claim": "Aprobar Reclamación",
    "Needs Admin Approval": "Requiere Aprobación del Administrador",
    "Claim status will automatically update to Fulfilled": "El estado cambiará automáticamente a Cumplido",
    "New claim requests start with pending status": "Las nuevas reclamaciones comienzan como pendientes",
    "Already claimed, awaiting fulfillment": "Ya reclamado, esperando cumplimiento",
    "Fulfilled Status": "Estado Cumplido",
    "Decision Pending": "Decisión Pendiente",
    "You have already claimed this listing": "Ya ha reclamado este anuncio",
    "Your claim request has been successfully submitted": "Su solicitud de reclamación ha sido enviada correctamente",
    "Please login first to claim this listing": "Inicie sesión primero para reclamar este anuncio",

    # CATEGORIES
    "Categories": "Categorías",
    "Category": "Categoría",
    "Category Name": "Nombre de Categoría",
    "Category Code": "Código de Categoría",
    "Category Status": "Estado de Categoría",
    "Category Section": "Sección de Categorías",
    "Category Section Status": "Estado de Sección de Categorías",
    "Category Serial Number": "Número de Serie de Categoría",
    "Add Listing Category": "Añadir Categoría de Anuncio",
    "Edit Listing Category": "Editar Categoría de Anuncio",
    "Listing categories deleted successfully": "Categorías de anuncios eliminadas correctamente",
    "Listing category updated successfully": "Categoría de anuncio actualizada correctamente",
    "category_id": "categoría",
    "Category deleted successfully": "Categoría eliminada correctamente",
    "Select Category": "Seleccionar Categoría",
    "Category Listing Section Title": "Título de Sección de Categorías",
    "Search By Category": "Buscar por Categoría",
    "All Categories": "Todas las Categorías",
    "More Categories": "Más Categorías",
    "Explore Popular Categories": "Explorar Categorías Populares",
    "No categories available": "No hay categorías disponibles",
    "Show All Categories": "Mostrar Todas las Categorías",
    "Enter Category Name": "Ingrese Nombre de Categoría",
    "Enter Category Serial Number": "Ingrese Número de Serie",
    "category": "categoría",
    "Listing Category": "Categoría de Anuncio",
    "Search By Category": "Buscar por Categoría",

    # PRODUCTS / SHOP
    "Shop": "Tienda",
    "Product": "Producto",
    "Products": "Productos",
    "Add Product": "Añadir Producto",
    "Edit Product": "Editar Producto",
    "Product Categories": "Categorías de Productos",
    "Add Product Category": "Añadir Categoría de Producto",
    "Edit Product Category": "Editar Categoría de Producto",
    "Product Name": "Nombre del Producto",
    "Product Details": "Detalles del Producto",
    "Product Image": "Imagen del Producto",
    "Product Images": "Imágenes del Producto",
    "Product Image Per Product": "Imagen por Producto",
    "Product Image Per Product (Unlimited)": "Imágenes por Producto (Ilimitadas)",
    "Product Images Per Product": "Imágenes por Producto",
    "Product Per Listing": "Productos por Anuncio",
    "Product Per Listing (Unlimited)": "Productos por Anuncio (Ilimitados)",
    "Products Per Listing": "Productos por Anuncio",
    "Products (Unlimited)": "Productos (Ilimitados)",
    "Product Orders": "Pedidos de Productos",
    "Product Enquiry Form": "Formulario de Consulta de Producto",
    "Product added into the cart.": "Producto añadido al carrito.",
    "Product removed successfully": "Producto eliminado correctamente",
    "New Product added successfully": "Nuevo producto añadido correctamente",
    "New product category added successfully": "Nueva categoría de producto añadida correctamente",
    "Unlimited Product Image": "Imagen de Producto Ilimitada",
    "Unlimited Products": "Productos Ilimitados",
    "Stock": "Stock",
    "Stock Out": "Sin Stock",
    "Out Of Stock": "Agotado",
    "In Stock": "En Stock",
    "Price": "Precio",
    "Current Price": "Precio Actual",
    "Previous Price": "Precio Anterior",
    "Min Price": "Precio Mínimo",
    "Max Price": "Precio Máximo",
    "Discount": "Descuento",
    "Tax": "Impuesto",
    "Shipping Charge": "Gastos de Envío",
    "Add Shipping Charge": "Añadir Gastos de Envío",
    "Edit Shipping Charge": "Editar Gastos de Envío",
    "New shipping charge added successfully": "Gastos de envío añadidos correctamente",
    "Coupon": "Cupón",
    "Coupons": "Cupones",
    "Add Coupon": "Añadir Cupón",
    "Edit Coupon": "Editar Cupón",
    "Coupon Type": "Tipo de Cupón",
    "Coupon applied successfully!": "Cupón aplicado correctamente.",
    "Coupon applied successfully.": "Cupón aplicado correctamente.",
    "Coupon deleted successfully": "Cupón eliminado correctamente",
    "Coupon updated successfully": "Cupón actualizado correctamente",
    "New coupon added successfully": "Nuevo cupón añadido correctamente",
    "Cart": "Carrito",
    "Cart is Empty": "El Carrito está Vacío",
    "Cart Total": "Total del Carrito",
    "Cart Page Title": "Título de Página del Carrito",
    "Cart updated successfully": "Carrito actualizado correctamente",
    "Your cart is empty": "Tu carrito está vacío",
    "Checkout": "Pagar",
    "Checkout Now": "Pagar Ahora",
    "Checkout Page Title": "Título de Página de Pago",
    "Order": "Pedido",
    "Orders": "Pedidos",
    "Order Details": "Detalles del Pedido",
    "Order Date": "Fecha del Pedido",
    "Order No.": "Nº de Pedido",
    "Order Number": "Número de Pedido",
    "Order Status": "Estado del Pedido",
    "Order Summary": "Resumen del Pedido",
    "Order Now": "Pedir Ahora",
    "Ordered Product": "Producto Pedido",
    "Total": "Total",
    "Total Orders": "Total de Pedidos",
    "Total Price": "Precio Total",
    "Total Quantity": "Cantidad Total",
    "Subtotal": "Subtotal",
    "Grand Total": "Total General",
    "Paid amount": "Cantidad Pagada",
    "Paid Amount": "Cantidad Pagada",
    "Invoice": "Factura",
    "Billing Details": "Detalles de Facturación",
    "Billing Address": "Dirección de Facturación",
    "Shipping Address": "Dirección de Envío",
    "Shipping Details": "Detalles de Envío",
    "Shipping Cost": "Costo de Envío",
    "Shipping Method": "Método de Envío",
    "Ship to a different address": "Enviar a una dirección diferente",
    "Same as billing address": "Igual que la dirección de facturación",
    "Quantity": "Cantidad",
    "Items": "Artículos",
    "Item": "Artículo",
    "Amount": "Cantidad",
    "amount": "cantidad",
    "Cost": "Costo",
    "Charge": "Cargo",
    "Charges": "Cargos",
    "Fixed Charge": "Cargo Fijo",
    "Fixed": "Fijo",
    "Free": "Gratis",
    "Percentage Charge": "Cargo Porcentual",
    "Commission": "Comisión",
    "Commission Amount": "Monto de Comisión",
    "Payment Method": "Método de Pago",
    "Payment Status": "Estado del Pago",
    "Payment Information": "Información del Pago",
    "Payment Instructions": "Instrucciones de Pago",
    "Payment Proof/Receipt": "Comprobante de Pago",
    "Payment Gateways": "Pasarelas de Pago",
    "Gateway Name": "Nombre de la Pasarela",
    "Add Gateway": "Añadir Pasarela",
    "Edit Gateway": "Editar Pasarela",
    "Online Gateways": "Pasarelas en Línea",
    "Offline Gateways": "Pasarelas Fuera de Línea",
    "Place Order": "Realizar Pedido",
    "Purchase": "Comprar",
    "Buy Now": "Comprar Ahora",
    "Buy Plan": "Comprar Plan",
    "Proceed to Checkout": "Proceder al Pago",
    "Choose a Payment Method": "Elija un Método de Pago",
    "My Orders": "Mis Pedidos",
    "My order details": "Detalles de mi pedido",
    "Order not found": "Pedido no encontrado",
    "Related Product": "Producto Relacionado",
    "Related Products": "Productos Relacionados",
    "Add to Cart": "Añadir al Carrito",
    "Added to cart successfully!": "¡Añadido al carrito correctamente!",
    "Failed to add to cart": "Error al añadir al carrito",
    "Update Cart": "Actualizar Carrito",
    "Enter Coupon Code": "Ingrese Código de Cupón",
    "Card Number": "Número de Tarjeta",
    "CVC Number": "Código CVC",
    "Expiry Month": "Mes de Vencimiento",
    "Expiry Year": "Año de Vencimiento",
    "Enter Product Name": "Ingrese Nombre del Producto",
    "Price Not Mentioned": "Precio No Indicado",
    "Product details not available": "Detalles del producto no disponibles",
    "This product has no review yet": "Este producto aún no tiene opiniones",
    "Digital Product": "Producto Digital",
    "Digital File": "Archivo Digital",
    "Delete product": "Eliminar producto",
    "Delete order": "Eliminar pedido",
    "Delete this product?": "¿Eliminar este producto?",
    "Enter Product Current Price": "Ingrese Precio Actual",
    "Enter Product Previous Price": "Ingrese Precio Anterior",
    "Enter Product Stock": "Ingrese Stock del Producto",

    # BLOG
    "Blog": "Blog",
    "Blogs": "Blogs",
    "Blog Management": "Gestión del Blog",
    "Add Post": "Añadir Artículo",
    "Edit Post": "Editar Artículo",
    "Posts": "Artículos",
    "All Posts": "Todos los Artículos",
    "Recent Posts": "Artículos Recientes",
    "Blog Category": "Categoría del Blog",
    "Add Blog Category": "Añadir Categoría del Blog",
    "Edit Blog Category": "Editar Categoría del Blog",
    "Blog categories deleted successfully": "Categorías del blog eliminadas correctamente",
    "Blog category deleted successfully": "Categoría del blog eliminada correctamente",
    "Blog category updated successfully": "Categoría del blog actualizada correctamente",
    "Blog deleted successfully": "Blog eliminado correctamente",
    "Blog updated successfully": "Blog actualizado correctamente",
    "New blog added successfully": "Nuevo artículo añadido correctamente",
    "New blog category added successfully": "Nueva categoría del blog añadida correctamente",
    "Blog section updated successfully": "Sección del blog actualizada correctamente",
    "Blog Page Title": "Título de Página del Blog",
    "Blog Section": "Sección del Blog",
    "Blog Section Status": "Estado de la Sección del Blog",
    "Blogs deleted successfully": "Blogs eliminados correctamente",
    "All Blog Post": "Todos los Artículos del Blog",
    "Search Blog": "Buscar en el Blog",
    "Search Posts": "Buscar Artículos",
    "Author": "Autor",
    "By": "Por",
    "By Admin": "Por Administrador",
    "Comments": "Comentarios",
    "Comment": "Comentario",
    "comment": "comentario",
    "Read Less": "Leer Menos",
    "Read More": "Leer Más",
    "Read more": "Leer más",
    "Enter Author Name": "Ingrese Nombre del Autor",
    "Content": "Contenido",
    "content": "contenido",

    # FAQ
    "FAQ": "FAQ",
    "FAQs": "FAQs",
    "FAQ Management": "Gestión de FAQ",
    "Add FAQ": "Añadir FAQ",
    "Edit FAQ": "Editar FAQ",
    "FAQ deleted successfully": "FAQ eliminado correctamente",
    "FAQ updated successfully": "FAQ actualizado correctamente",
    "New faq added successfully": "Nuevo FAQ añadido correctamente",
    "FAQ Page Title": "Título de Página de FAQ",
    "FAQ Per Listing": "FAQ por Anuncio",
    "FAQs Per Listing": "FAQs por Anuncio",
    "Faqs (Per Listing)": "FAQs (por Anuncio)",
    "FAQs Per Listing(Unlimited)": "FAQs por Anuncio (Ilimitados)",
    "FAQ limit reached or exceeded": "Límite de FAQ alcanzado o superado",
    "FAQs deleted successfully": "FAQs eliminados correctamente",
    "Unlimited FAQ": "FAQs Ilimitados",
    "Question": "Pregunta",
    "question": "pregunta",
    "Answer": "Respuesta",
    "answer": "respuesta",
    "Frequently Asked Questions": "Preguntas Frecuentes",
    "NO FAQ FOUND": "NO SE ENCONTRARON FAQS",
    "No Faq Found": "No se encontraron FAQs",
    "Enter Question": "Ingrese Pregunta",
    "Enter Answer": "Ingrese Respuesta",
    "Enter FAQ Serial Number": "Ingrese Número de Serie",

    # FEATURES
    "Features": "Características",
    "Feature": "Característica",
    "Add Feature": "Añadir Característica",
    "Feature section updated successfully": "Sección de características actualizada correctamente",
    "Feature deleted successfully": "Característica eliminada correctamente",
    "Feature Updated successfully": "Característica actualizada correctamente",
    "Feature Per Listing": "Característica por Anuncio",
    "Features Per Listing": "Características por Anuncio",
    "Features  (Per Listing)": "Características (por Anuncio)",
    "Features (Per Listing)": "Características (por Anuncio)",
    "Feature Per Listing (Unlimited)": "Características por Anuncio (Ilimitadas)",
    "Unlimited Feature": "Características Ilimitadas",
    "Custom Features": "Características Personalizadas",
    "More Features": "Más Características",
    "NO FEATURE FOUND": "NO SE ENCONTRARON CARACTERÍSTICAS",
    "No Feature Found": "No se encontraron características",
    "Feature Active Date": "Fecha de Activación",
    "Feature Expiry Date": "Fecha de Vencimiento",
    "Feature It": "Destacarlo",
    "Enter Custom Features": "Ingrese Características Personalizadas",
    "Enter Short Description": "Ingrese Descripción Corta",

    # AMENITIES
    "Amenities": "Servicios",
    "Amenitie Per Listing": "Servicios por Anuncio",
    "Amenities Per Listing": "Servicios por Anuncio",
    "Amenities (Per Listing)": "Servicios (por Anuncio)",
    "Amenities Per Listing(Unlimited)": "Servicios por Anuncio (Ilimitados)",
    "Add Amenitie": "Añadir Servicio",
    "Edit Amenitie": "Editar Servicio",
    "Aminite deleted successfully": "Servicio eliminado correctamente",
    "Aminite stored successfully": "Servicio guardado correctamente",
    "Aminite updated successfully": "Servicio actualizado correctamente",
    "Aminities updated successfully": "Servicios actualizados correctamente",
    "Unlimited Amenities": "Servicios Ilimitados",
    "Enter Amenity Title": "Ingrese Título del Servicio",
    "Enter Number of Amenities per Listing": "Ingrese Número de Servicios por Anuncio",

    # PACKAGES
    "Packages": "Paquetes",
    "Package": "Paquete",
    "Add Package": "Añadir Paquete",
    "Edit package": "Editar Paquete",
    "Current Package": "Paquete Actual",
    "Next Package": "Siguiente Paquete",
    "Add Current Package": "Añadir Paquete Actual",
    "Add Next Package": "Añadir Siguiente Paquete",
    "Change Current Package": "Cambiar Paquete Actual",
    "Change Next Package": "Cambiar Siguiente Paquete",
    "Current Package changed successfully": "Paquete actual cambiado correctamente",
    "Next Package changed successfully": "Siguiente paquete cambiado correctamente",
    "Current Package has been added successfully": "Paquete actual añadido correctamente",
    "Next Package has been added successfully": "Siguiente paquete añadido correctamente",
    "Current Package removed successfully": "Paquete actual eliminado correctamente",
    "Next Package removed successfully": "Siguiente paquete eliminado correctamente",
    "Term": "Plazo",
    "term": "plazo",
    "Lifetime": "De por Vida",
    "lifetime": "de por vida",
    "Monthly": "Mensual",
    "monthly": "mensual",
    "Yearly": "Anual",
    "Trial": "Prueba",
    "Test Package": "Paquete de Prueba",
    "Pricing": "Precios",
    "Pricing Filter": "Filtro de Precios",
    "Choose a Package term": "Elija un plazo de paquete",
    "If you purchase this package": "Si compra este paquete",
    "If price is 0 , than it will appear as free": "Si el precio es 0, aparecerá como gratuito",
    "NO PACKAGE FOUND": "NO SE ENCONTRARON PAQUETES",
    "Details & Package": "Detalles y Paquete",
    "Extend": "Extender",
    "If you delete this package, all memberships under this package will be deleted": "Si elimina este paquete, todas las membresías se eliminarán",
    "Enter Package price": "Ingrese Precio del Paquete",
    "Enter Package title": "Ingrese Título del Paquete",
    "Current Plan": "Plan Actual",

    # LOCATIONS
    "Countries": "Países",
    "Country": "País",
    "country": "país",
    "Country Name": "Nombre del País",
    "Add Country": "Añadir País",
    "Edit Country": "Editar País",
    "Country deleted successfully": "País eliminado correctamente",
    "Country stored successfully": "País guardado correctamente",
    "Country updated successfully": "País actualizado correctamente",
    "Enter Country": "Ingrese País",
    "Enter Country Name": "Ingrese Nombre del País",
    "Select Country": "Seleccionar País",
    "State": "Estado/Provincia",
    "States": "Estados/Provincias",
    "Add State": "Añadir Estado",
    "Edit State": "Editar Estado",
    "Enter State": "Ingrese Estado",
    "Enter State Name": "Ingrese Nombre del Estado",
    "Select State": "Seleccionar Estado",
    "City": "Ciudad",
    "Cities": "Ciudades",
    "city": "ciudad",
    "Add City": "Añadir Ciudad",
    "Edit City": "Editar Ciudad",
    "City deleted successfully": "Ciudad eliminada correctamente",
    "City updated successfully": "Ciudad actualizada correctamente",
    "Enter City": "Ingrese Ciudad",
    "Enter City Name": "Ingrese Nombre de la Ciudad",
    "Select City": "Seleccionar Ciudad",
    "Select State/City": "Seleccionar Estado/Ciudad",
    "Location Section": "Sección de Ubicación",
    "Location Section Status": "Estado de Sección de Ubicación",
    "Location section updated successfully": "Sección de ubicación actualizada correctamente",
    "Search By Location": "Buscar por Ubicación",
    "Search specific location": "Buscar ubicación específica",
    "Use current location": "Usar ubicación actual",
    "Current location": "Ubicación actual",
    "Enter location": "Ingrese ubicación",
    "Enter Location": "Ingrese Ubicación",
    "Map": "Mapa",
    "Google Map": "Google Maps",
    "Google Map API": "API de Google Maps",
    "Google Map API Status": "Estado de API de Google Maps",
    "Google Map Status": "Estado de Google Maps",
    "Enter Latitude": "Ingrese Latitud",
    "Enter Longitude": "Ingrese Longitud",
    "Enter Shop Location": "Ingrese Ubicación de la Tienda",

    # HOME PAGE
    "Home Page": "Página de Inicio",
    "Hero Section": "Sección Principal",
    "Call To Action Section": "Sección de Llamada a la Acción",
    "Call To Action Section Status": "Estado de Llamada a la Acción",
    "Call to action section updated successfully": "Sección de llamada a la acción actualizada correctamente",
    "Counter Section": "Sección de Contadores",
    "Counter Informations": "Información de Contadores",
    "Counter Section Status": "Estado de Sección de Contadores",
    "Add Counter Information": "Añadir Información de Contador",
    "Edit Counter Information": "Editar Información de Contador",
    "Testimonials": "Testimonios",
    "Testimonial": "Testimonio",
    "Add Testimonial": "Añadir Testimonio",
    "Edit Testimonial": "Editar Testimonio",
    "New testimonial added successfully": "Nuevo testimonio añadido correctamente",
    "Client Name": "Nombre del Cliente",
    "Client Image": "Imagen del Cliente",
    "Client Comment": "Comentario del Cliente",
    "Client Occupation": "Ocupación del Cliente",
    "No Testimonial Found": "No se encontraron testimonios",
    "Work Process": "Proceso de Trabajo",
    "Add Work Process": "Añadir Proceso de Trabajo",
    "Edit Work Process": "Editar Proceso de Trabajo",
    "New work process added successfully": "Nuevo proceso de trabajo añadido correctamente",
    "How It Works": "Cómo Funciona",
    "No Work Process Found": "No se encontraron procesos de trabajo",
    "Information": "Información",
    "Information deleted successfully": "Información eliminada correctamente",
    "Information stored successfully": "Información guardada correctamente",
    "Information updated successfully": "Información actualizada correctamente",
    "No Information Found": "No se encontró información",
    "What's Included": "Qué está Incluido",
    "Services": "Servicios",
    "Enter Client Name": "Ingrese Nombre del Cliente",
    "Enter Client Comment": "Ingrese Comentario del Cliente",
    "Enter Client Occupation": "Ingrese Ocupación del Cliente",
    "Enter Work Process Serial Number": "Ingrese Número de Serie",
    "Enter Work Process Title": "Ingrese Título del Proceso",

    # FOOTER
    "Footer": "Pie de Página",
    "Footer logo updated successfully": "Logotipo del pie de página actualizado correctamente",
    "Quick Links": "Enlaces Rápidos",
    "Add Quick Link": "Añadir Enlace Rápido",
    "Edit Quick Link": "Editar Enlace Rápido",
    "New quick link added successfully": "Nuevo enlace rápido añadido correctamente",
    "Copyright Text": "Texto de Copyright",
    "Useful Links": "Enlaces Útiles",
    "Follow Us": "Síguenos",
    "Our Address": "Nuestra Dirección",
    "Enter Quick Link Title": "Ingrese Título del Enlace Rápido",
    "Enter Quick Link URL": "Ingrese URL del Enlace Rápido",
    "Delete this message?": "¿Eliminar este mensaje?",

    # CUSTOM PAGES
    "Custom Pages": "Páginas Personalizadas",
    "Custom Page": "Página Personalizada",
    "Add Page": "Añadir Página",
    "Edit Page": "Editar Página",
    "New page added successfully": "Nueva página añadida correctamente",
    "Page Headings": "Encabezados de Página",

    # CONTACT
    "Contact": "Contacto",
    "Contact Us": "Contáctenos",
    "Contact Page": "Página de Contacto",
    "Contact Page Title": "Título de Página de Contacto",
    "Contact Information": "Información de Contacto",
    "Contact Now": "Contactar Ahora",
    "Contact Number": "Número de Contacto",
    "contact_number": "número de contacto",
    "Enter Contact Number": "Ingrese Número de Contacto",
    "email_address": "dirección de correo",
    "A contact request was sent successfully": "Solicitud de contacto enviada correctamente",
    "Message": "Mensaje",
    "Message sent successfully": "Mensaje enviado correctamente",
    "Message Sent Successfully": "Mensaje Enviado Correctamente",
    "Message Information": "Información del Mensaje",
    "Messages": "Mensajes",
    "Message deleted successfully": "Mensaje eliminado correctamente",
    "Message Submitted At": "Enviado el",
    "No Message Found": "No se encontraron mensajes",
    "Submit Message": "Enviar Mensaje",
    "Write Your Message": "Escriba su Mensaje",
    "Subject": "Asunto",
    "Enter Subject": "Ingrese Asunto",
    "Enter Email Subject": "Ingrese Asunto del Correo",
    "Write a Review": "Escribir una Opinión",
    "Write your review": "Escriba su opinión",
    "Enter Your Email": "Ingrese su Correo",
    "Enter Your Email Address": "Ingrese su Dirección de Correo",
    "Enter Your Full Name": "Ingrese su Nombre Completo",
    "Enter your name": "Ingrese su nombre",
    "Enter your email": "Ingrese su correo",
    "Enter your phone": "Ingrese su teléfono",
    "Enter your password": "Ingrese su contraseña",
    "Enter your username": "Ingrese su usuario",
    "Enter your username or email": "Ingrese su usuario o correo",
    "Enter name": "Ingrese nombre",
    "Enter email": "Ingrese correo",
    "Enter phone number": "Ingrese número de teléfono",
    "Enter Your Name": "Ingrese su Nombre",
    "Go to Messages": "Ir a Mensajes",

    # FORMS
    "Forms": "Formularios",
    "Form Builder": "Constructor de Formularios",
    "Form Type": "Tipo de Formulario",
    "Form Types Guide": "Guía de Tipos de Formulario",
    "Form Guide": "Guía de Formularios",
    "Form Inputs": "Campos del Formulario",
    "Add Form": "Añadir Formulario",
    "Edit Form": "Editar Formulario",
    "Form deleted successfully": "Formulario eliminado correctamente",
    "Form updated successfully": "Formulario actualizado correctamente",
    "Form created successfully.": "Formulario creado correctamente.",
    "Form deleted successfully.": "Formulario eliminado correctamente.",
    "Form updated successfully.": "Formulario actualizado correctamente.",
    "Input Fields": "Campos de Entrada",
    "Input Type": "Tipo de Entrada",
    "Input Field Type": "Tipo de Campo",
    "Create Input Field": "Crear Campo de Entrada",
    "Edit Input Field": "Editar Campo de Entrada",
    "Edit Input": "Editar Campo",
    "Label": "Etiqueta",
    "Placeholder": "Marcador de Posición",
    "Required": "Obligatorio",
    "Options": "Opciones",
    "Add Option": "Añadir Opción",
    "Enter Option": "Ingrese Opción",
    "Checkbox": "Casilla de Verificación",
    "Radio": "Botón de Opción",
    "Textarea": "Área de Texto",
    "Text": "Texto",
    "text": "texto",
    "Number": "Número",
    "Datepicker": "Selector de Fecha",
    "Table Reservation": "Reserva de Mesa",
    "Quote Request": "Solicitud de Presupuesto",
    "Claim Request": "Solicitud de Reclamación",
    "Enquiry Form": "Formulario de Consulta",
    "Claim Request Form": "Formulario de Reclamación",
    "Each vendor can have only one quote request form per language": "Cada proveedor puede tener solo un formulario por idioma",
    "Each language should have only one claim request form": "Cada idioma debe tener solo un formulario de reclamación",
    "Leave it blank for admin's form": "Déjelo en blanco para el formulario del administrador",
    "Global": "Global",
    "Local": "Local",
    "A form of this type already exists for this scope": "Ya existe un formulario de este tipo para este ámbito",
    "Based on your selection, some input fields will be shown or hidden automatically": "Según su selección, algunos campos se mostrarán u ocultarán automáticamente",
    "Form Name": "Nombre del Formulario",
    "Enter Form Name": "Ingrese Nombre del Formulario",
    "Delete Form": "Eliminar Formulario",
    "Delete this Form?": "¿Eliminar este formulario?",
    "Drag & Drop the input fields to change the order number": "Arrastre los campos para cambiar el orden",
    "All Forms": "Todos los Formularios",
    "Form": "Formulario",

    # SUPPORT TICKETS
    "Support Tickets": "Tickets de Soporte",
    "Support Ticket Details": "Detalles del Ticket de Soporte",
    "Ticket": "Ticket",
    "Tickets": "Tickets",
    "All Tickets": "Todos los Tickets",
    "Closed Tickets": "Tickets Cerrados",
    "Total Tickets": "Total de Tickets",
    "Add a Ticket": "Añadir un Ticket",
    "Add a ticket": "Añadir un ticket",
    "Submit a Ticket": "Enviar un Ticket",
    "Create a Support Ticket": "Crear un Ticket de Soporte",
    "Ticket ID": "ID del Ticket",
    "Ticket has been submitted successfully": "Ticket enviado correctamente",
    "Close Ticket": "Cerrar Ticket",
    "Add Stuff to this support ticket successfully": "Personal añadido al ticket correctamente",
    "Replies": "Respuestas",
    "Reply": "Responder",
    "Create Ticket": "Crear Ticket",
    "Delete this ticket?": "¿Eliminar este ticket?",
    "Delete ticket": "Eliminar ticket",

    # ADVERTISEMENTS
    "Advertisements": "Anuncios Publicitarios",
    "Advertisement": "Anuncio Publicitario",
    "Add Advertisement": "Añadir Anuncio",
    "Edit Advertisement": "Editar Anuncio",
    "Ad Type": "Tipo de Anuncio",
    "Ad Slot": "Espacio del Anuncio",
    "ad_type": "tipo de anuncio",
    "Advertisement deleted successfully": "Anuncio eliminado correctamente",
    "Advertisement Resolution": "Resolución del Anuncio",
    "Advertisements deleted successfully": "Anuncios eliminados correctamente",
    "Advertisement Type": "Tipo de Anuncio",
    "Advertisement updated successfully": "Anuncio actualizado correctamente",
    "Advertise settings updated successfully": "Configuración de anuncios actualizada correctamente",
    "New advertisement added successfully": "Nuevo anuncio añadido correctamente",
    "All Advertisements": "Todos los Anuncios",
    "Enter Ad Slot": "Ingrese Espacio del Anuncio",

    # POPUPS
    "Announcement Popups": "Ventanas Emergentes",
    "Popup": "Ventana Emergente",
    "Add Popup": "Añadir Ventana Emergente",
    "New popup added successfully": "Ventana emergente añadida correctamente",
    "All activated popups will be appear in UI according to serial number.": "Las ventanas activas aparecerán según el número de serie.",
    "If there are multiple active popups, then popups will be shown in UI according to serial number.": "Si hay varias ventanas activas, se mostrarán según el número de serie.",
    "Enter Popup Name": "Ingrese Nombre de la Ventana",
    "Enter Popup Text": "Ingrese Texto de la Ventana",
    "Enter Popup Title": "Ingrese Título de la Ventana",
    "Enter Popup Delay": "Ingrese Retraso de la Ventana",
    "Delay": "Retraso",

    # SOCIAL
    "Social Media": "Redes Sociales",
    "Social Link": "Enlace Social",
    "Social Links": "Enlaces Sociales",
    "Add Social Media": "Añadir Red Social",
    "Edit Social Media": "Editar Red Social",
    "New social media added successfully": "Nueva red social añadida correctamente",
    "Social Link Per Listing": "Enlaces Sociales por Anuncio",
    "Social Links Per Listing": "Enlaces Sociales por Anuncio",
    "Social Links Per Listing(Unlimited)": "Enlaces Sociales por Anuncio (Ilimitados)",
    "Unlimited Social Links": "Enlaces Sociales Ilimitados",
    "Facebook": "Facebook",
    "Twitter": "Twitter",
    "Linkedin": "LinkedIn",
    "WhatsApp": "WhatsApp",
    "Telegram": "Telegram",
    "Messenger": "Messenger",
    "Tawk.To": "Tawk.To",
    "Tweet": "Tweet",
    "Enter URL of Social Media Account": "Ingrese URL de la Red Social",
    "Add Socail Link": "Añadir Enlace Social",

    # SETTINGS
    "Basic Settings": "Configuración Básica",
    "General Settings": "Configuración General",
    "General settings update Successfully": "Configuración general actualizada correctamente",
    "Email Settings": "Configuración de Correo",
    "Email Status": "Estado del Correo",
    "Email status updated successfully": "Estado del correo actualizado correctamente",
    "Mail": "Correo",
    "Mail From Admin": "Correo del Administrador",
    "Mail To Admin": "Correo para el Administrador",
    "Mail Body": "Cuerpo del Correo",
    "Mail Subject": "Asunto del Correo",
    "Mail Templates": "Plantillas de Correo",
    "Mail template updated successfully": "Plantilla de correo actualizada correctamente",
    "Mail info updated successfully": "Información de correo actualizada correctamente",
    "Mail could not be sent": "No se pudo enviar el correo",
    "Mail has been sent to all the subscribers": "Correo enviado a todos los suscriptores",
    "Mail Type": "Tipo de Correo",
    "A mail has been sent to your email address": "Se ha enviado un correo a su dirección",
    "A verification mail has been sent to your email address": "Se ha enviado un correo de verificación",
    "Email Verificaiton": "Verificación de Correo",
    "Email Verification Link": "Enlace de Verificación de Correo",
    "From Email": "Correo Remitente",
    "From Name": "Nombre Remitente",
    "from_mail": "correo remitente",
    "from_name": "nombre remitente",
    "Logo & Image": "Logotipo e Imagen",
    "Logo updated successfully": "Logotipo actualizado correctamente",
    "Favicon updated successfully": "Favicon actualizado correctamente",
    "Image updated successfully": "Imagen actualizada correctamente",
    "Appearance": "Apariencia",
    "Appearance updated successfully": "Apariencia actualizada correctamente",
    "Theme": "Tema",
    "Breadcrumb": "Migas de Pan",
    "Breadcrumb updated successfully": "Migas de pan actualizadas correctamente",
    "Currency": "Moneda",
    "Currency updated successfully": "Moneda actualizada correctamente",
    "Base Currency Symbol": "Símbolo de Moneda Base",
    "Base Currency Symbol Position": "Posición del Símbolo",
    "Base Currency Text": "Texto de Moneda Base",
    "Base Currency Text Position": "Posición del Texto",
    "Base Currency Rate": "Tasa de Moneda Base",
    "Language": "Idioma",
    "Language Management": "Gestión de Idiomas",
    "Language added successfully": "Idioma añadido correctamente",
    "Language deleted successfully": "Idioma eliminado correctamente",
    "Language updated successfully": "Idioma actualizado correctamente",
    "Direction": "Dirección",
    "direction": "dirección",
    "Code": "Código",
    "code": "código",
    "Make Default": "Establecer por Defecto",
    "Default language cannot be delete": "El idioma por defecto no se puede eliminar",
    "Keywords": "Palabras Clave",
    "Keyword": "Palabra Clave",
    "keyword": "palabra clave",
    "Keywords of": "Palabras clave de",
    "Keywords updated successfully": "Palabras clave actualizadas correctamente",
    "Edit Keyword": "Editar Palabra Clave",
    "Edit Dashboard Keyword": "Editar Palabra Clave del Panel",
    "Edit Front Keyword": "Editar Palabra Clave del Sitio",
    "Edit Mail Template": "Editar Plantilla de Correo",
    "Add Keyword for admin": "Añadir palabra clave para administrador",
    "Add Keyword for front": "Añadir palabra clave para el sitio",
    "Add New Keyword for dashboard": "Añadir nueva palabra clave para el panel",
    "Add New Keyword for front": "Añadir nueva palabra clave para el sitio",
    "A new keyword successfully": "Nueva palabra clave añadida correctamente",
    "Enter Keyword": "Ingrese Palabra Clave",
    "language": "idioma",
    "language_id": "idioma",
    "Meaning": "Significado",
    "Translation": "Traducción",
    "SEO": "SEO",
    "Meta Description": "Meta Descripción",
    "Meta Keywords": "Meta Palabras Clave",
    "Meta Description For Home Page": "Meta Descripción para Inicio",
    "Meta Description For About Us Page": "Meta Descripción para Nosotros",
    "Meta Description For Blog Page": "Meta Descripción para Blog",
    "Meta Description For Contact Page": "Meta Descripción para Contacto",
    "Meta Description For FAQ Page": "Meta Descripción para FAQ",
    "Meta Description For Listings Page": "Meta Descripción para Anuncios",
    "Meta Description For Pricing Page": "Meta Descripción para Precios",
    "Meta Description For Products Page": "Meta Descripción para Productos",
    "Meta Description For Vendors Page": "Meta Descripción para Proveedores",
    "Meta Keywords For Home Page": "Meta Palabras Clave para Inicio",
    "Meta Keywords For About Us Page": "Meta Palabras Clave para Nosotros",
    "Meta Keywords For Blog Page": "Meta Palabras Clave para Blog",
    "Meta Keywords For Contact Page": "Meta Palabras Clave para Contacto",
    "Meta Keywords For FAQ Page": "Meta Palabras Clave para FAQ",
    "Meta Keywords For Listings Page": "Meta Palabras Clave para Anuncios",
    "Meta Keywords For Pricing Page": "Meta Palabras Clave para Precios",
    "Meta Keywords For Products Page": "Meta Palabras Clave para Productos",
    "Meta Keywords For Vendors Page": "Meta Palabras Clave para Proveedores",
    "Meta Description For Customer Login Page": "Meta Descripción para Inicio de Sesión",
    "Meta Description For Customer Signup Page": "Meta Descripción para Registro",
    "Meta Description For Customer Forget Password Page": "Meta Descripción para Olvidar Contraseña",
    "Meta Description For Vendor Login Page": "Meta Descripción para Inicio de Proveedor",
    "Meta Description For Vendor Signup Page": "Meta Descripción para Registro de Proveedor",
    "Meta Description For Vendor Forget Password Page": "Meta Descripción para Olvidar Contraseña de Proveedor",
    "Meta Keywords For Customer Login Page": "Meta Palabras Clave para Inicio de Sesión",
    "Meta Keywords For Customer Signup Page": "Meta Palabras Clave para Registro",
    "Meta Keywords For Customer Forget Password Page": "Meta Palabras Clave para Olvidar Contraseña",
    "Meta Keywords For Vendor Login Page": "Meta Palabras Clave para Inicio de Proveedor",
    "Meta Keywords For Vendor Signup Page": "Meta Palabras Clave para Registro de Proveedor",
    "Meta Keywords For Vendor Forget Password Page": "Meta Palabras Clave para Olvidar Contraseña de Proveedor",
    "Enter Meta Description": "Ingrese Meta Descripción",
    "Enter Meta Keywords": "Ingrese Meta Palabras Clave",
    "Title": "Título",
    "title": "título",
    "Subtitle": "Subtítulo",
    "subtitle": "subtítulo",
    "Enter Title": "Ingrese Título",
    "Enter Subtitle": "Ingrese Subtítulo",
    "Summary": "Resumen",
    "Enter Summary": "Ingrese Resumen",

    # PLUGINS
    "Plugins": "Plugins",
    "Manage Plugins": "Gestionar Plugins",
    "Update necessary plugins": "Actualizar plugins necesarios",
    "Google Recaptcha": "Google Recaptcha",
    "Maintenance Mode": "Modo de Mantenimiento",
    "Maintenance Status": "Estado de Mantenimiento",
    "Maintenance Message": "Mensaje de Mantenimiento",
    "Maintenance Info updated successfully": "Información de mantenimiento actualizada correctamente",
    "maintenance_msg": "mensaje de mantenimiento",
    "Cookie Alert": "Aviso de Cookies",
    "Cookie Alert Status": "Estado de Aviso de Cookies",
    "Cookie Alert Text": "Texto de Aviso de Cookies",
    "Cookie Alert Button Text": "Texto del Botón de Cookies",
    "Cookie alert info updated successfully": "Aviso de cookies actualizado correctamente",
    "cookie_alert_text": "texto de aviso de cookies",
    "Push Notification": "Notificación Push",
    "Firebase": "Firebase",
    "Upload Firebase Admin JSON": "Subir JSON de Firebase Admin",
    "Mobile Interface": "Interfaz Móvil",
    "Mobile App Settings": "Configuración de App Móvil",
    "Cron Job Command": "Comando de Cron Job",
    "Disqus": "Disqus",
    "Disqus Short Name": "Nombre Corto de Disqus",
    "Disqus Status": "Estado de Disqus",
    "Disqus info updated successfully": "Información de Disqus actualizada correctamente",
    "Google AdSense": "Google AdSense",
    "Google Adsense Publisher ID": "ID de Editor de Google AdSense",

    # WITHDRAW
    "Withdraw": "Retirar",
    "Withdrawals": "Retiros",
    "Withdraw Request": "Solicitud de Retiro",
    "Withdraw Requests": "Solicitudes de Retiro",
    "Add Payment Method": "Añadir Método de Pago",
    "Edit Payment Method": "Editar Método de Pago",
    "Method": "Método",
    "Method Name": "Nombre del Método",
    "Minimum Limit": "Límite Mínimo",
    "Maximum Limit": "Límite Máximo",
    "Minimum Spend": "Gasto Mínimo",
    "Min Limit": "Límite Mín",
    "Max Limit": "Límite Máx",
    "min_limit": "límite mínimo",
    "max_limit": "límite máximo",
    "Available Balance": "Saldo Disponible",
    "Enter Method Name": "Ingrese Nombre del Método",
    "Enter Withdraw Amount": "Ingrese Monto a Retirar",
    "Enter Withdraw Maximum Limit": "Ingrese Límite Máximo",
    "Enter Withdraw Minimum Limit": "Ingrese Límite Mínimo",
    "Amount is required": "El monto es obligatorio",

    # SUBSCRIPTION
    "Subscription": "Suscripción",
    "Subscription Log": "Registro de Suscripciones",
    "Change payment status to Success": "Cambiar estado de pago a Exitoso",
    "Find the payment record": "Encontrar el registro de pago",
    "For offline payments, you must manually verify and approve the payment from Subscription Log": "Para pagos offline, debe verificar manualmente desde el Registro",
    "Your transaction request was received and sent for review": "Su solicitud de transacción fue recibida y enviada para revisión",
    "Your transaction was successful": "Su transacción fue exitosa",

    # PAYMENT GATEWAYS
    "PayPal": "PayPal",
    "Stripe": "Stripe",
    "Paystack": "Paystack",
    "Paytm": "Paytm",
    "Instamojo": "Instamojo",
    "Flutterwave": "Flutterwave",
    "Mollie": "Mollie",
    "Razorpay": "Razorpay",
    "MercadoPago": "MercadoPago",
    "Authorize.Net": "Authorize.Net",
    "Authorize.net": "Authorize.net",
    "Authorize.Net Status": "Estado de Authorize.Net",
    "Authorize.Net Test Mode": "Modo de Prueba de Authorize.Net",
    "Authorize.net informations updated successfully": "Información de Authorize.net actualizada",
    "Iyzico": "Iyzico",
    "Midtrans": "Midtrans",
    "MyFatoorah": "MyFatoorah",
    "Myfatoorah": "Myfatoorah",
    "Citibank": "PayPal",
    "Offline Payment": "Pago Offline",
    "New offline payment gateway added successfully": "Nueva pasarela de pago offline añadida",
    "Test Mode": "Modo de Prueba",
    "Sandbox": "Sandbox",
    "API Key": "Clave API",
    "Api Key": "Clave API",
    "Secret Key": "Clave Secreta",
    "Public Key": "Clave Pública",
    "Client ID": "ID de Cliente",
    "Client Secret": "Secreto de Cliente",
    "Merchant Id": "ID de Comercio",
    "App ID": "ID de App",
    "App Secret": "Secreto de App",
    "Token": "Token",
    "Encryption": "Encriptación",
    "encryption": "encriptación",
    "Server Key": "Clave de Servidor",
    "Auth Token": "Token de Autenticación",
    "API Login ID": "ID de Inicio de API",
    "API Endpoint": "Endpoint de API",
    "Transaction Key": "Clave de Transacción",
    "Bypass Token": "Token de Bypass",
    "Cancel URL": "URL de Cancelación",
    "Redirect URL": "URL de Redirección",
    "Instructions": "Instrucciones",
    "Gateway Instructions": "Instrucciones de la Pasarela",
    "Enter Gateway Instructions": "Ingrese Instrucciones",
    "Enter Payment Gateway Name": "Ingrese Nombre de la Pasarela",
    "Flutterwave Public Key": "Clave Pública de Flutterwave",
    "Flutterwave Secret Key": "Clave Secreta de Flutterwave",
    "Flutterwave Status": "Estado de Flutterwave",
    "Flutterwave's information updated successfully": "Información de Flutterwave actualizada",
    "Instamojo API Key": "Clave API de Instamojo",
    "Instamojo Auth Token": "Token de Autenticación de Instamojo",
    "Instamojo Status": "Estado de Instamojo",
    "Instamojo Test Mode": "Modo de Prueba de Instamojo",
    "Instamojo's information updated successfully": "Información de Instamojo actualizada",
    "Iyzico Api Key": "Clave API de Iyzico",
    "Iyzico Secret Key": "Clave Secreta de Iyzico",
    "Iyzico Status": "Estado de Iyzico",

    # MENU BUILDER
    "Menu Builder": "Constructor de Menús",
    "Menu": "Menú",
    "Menus": "Menús",
    "Edit Menu": "Editar Menú",
    "Add To Menus": "Añadir a Menús",
    "Built-In Menus": "Menús Incorporados",
    "Custom Menus": "Menús Personalizados",
    "Menu Name": "Nombre del Menú",
    "Menu URL": "URL del Menú",
    "Enter Menu Name": "Ingrese Nombre del Menú",
    "Enter Menu URL": "Ingrese URL del Menú",

    # ERROR & VALIDATION
    "Error": "Error",
    "Warning": "Advertencia",
    "Alert": "Alerta",
    "Success": "Éxito",
    "Info": "Información",
    "Notice": "Aviso",
    "404 Error Page Title": "Título de Página de Error 404",
    "404 not found": "404 no encontrado",
    "The page you are looking for might have been moved, renamed, or might never existed.": "La página que busca podría haber sido movida, renombrada o no existir.",
    "Validation": "Validación",
    "Please fill all fields": "Por favor complete todos los campos",
    "Please enter a valid email": "Por favor ingrese un correo válido",
    "Please enter a valid email address.": "Por favor ingrese una dirección de correo válida.",
    "Passwords do not match": "Las contraseñas no coinciden",
    "Please enter your name": "Por favor ingrese su nombre",
    "Please enter your email": "Por favor ingrese su correo",
    "Please enter your phone": "Por favor ingrese su teléfono",
    "Please enter your message": "Por favor ingrese su mensaje",
    "Please fill all billing details": "Por favor complete todos los datos de facturación",
    "Please select a payment method": "Por favor seleccione un método de pago",
    "Please select a rating": "Por favor seleccione una puntuación",
    "Please write your review": "Por favor escriba su opinión",
    "Review must be at least 10 characters": "La opinión debe tener al menos 10 caracteres",
    "Review submitted successfully!": "¡Opinión enviada correctamente!",
    "Failed to submit review": "Error al enviar la opinión",
    "Please login first": "Por favor inicie sesión primero",
    "Please login to continue": "Por favor inicie sesión para continuar",
    "Please login": "Por favor inicie sesión",
    "An error occurred": "Ocurrió un error",
    "Something went wrong.": "Algo salió mal.",
    "Sending email failed.": "Error al enviar el correo.",
    "Something went wrong!": "¡Algo salió mal!",
    "Invalid request!": "¡Solicitud inválida!",
    "Unauthorized": "No autorizado",
    "Forbidden": "Prohibido",
    "Not found": "No encontrado",
    "Server Error": "Error del Servidor",
    "Captcha error! Try again later or contact site admin.": "Error de Captcha. Intente de nuevo o contacte al administrador.",
    "Failed to load products": "Error al cargar productos",
    "Failed to load product details": "Error al cargar detalles del producto",
    "No product data available": "No hay datos del producto disponibles",
    "Failed to load listing details": "Error al cargar detalles del anuncio",
    "No listings match your filters": "Ningún anuncio coincide con sus filtros",
    "Failed to load categories": "Error al cargar categorías",
    "Failed to load checkout data": "Error al cargar datos de pago",
    "Failed to proceed to checkout": "Error al proceder al pago",
    "Failed to load payment page": "Error al cargar la página de pago",
    "Failed to pick file": "Error al seleccionar el archivo",
    "Item removed from cart": "Artículo eliminado del carrito",
    "Removed from wishlist": "Eliminado de la lista de deseos",
    "Failed to remove from wishlist": "Error al eliminar de la lista de deseos",
    "Added to wishlist": "Añadido a la lista de deseos",
    "Failed to add to wishlist": "Error al añadir a la lista de deseos",
    "Query submitted successfully!": "¡Consulta enviada correctamente!",
    "Failed to submit query": "Error al enviar la consulta",
    "Logged out successfully": "Sesión cerrada correctamente",
    "Login successful!": "¡Inicio de sesión exitoso!",
    "Please upload payment proof": "Por favor suba el comprobante de pago",
    "No payment URL received": "No se recibió URL de pago",
    "Payment cancelled": "Pago cancelado",
    "Payment successful!": "¡Pago exitoso!",
    "Payment verification failed": "Verificación de pago fallida",
    "Payment page not available": "Página de pago no disponible",
    "Order completion failed": "Error al completar el pedido",
    "Invalid payment data received": "Datos de pago inválidos recibidos",
    "Payment URL not available": "URL de pago no disponible",
    "Razorpay configuration is missing": "Falta la configuración de Razorpay",
    "External wallet payment initiated": "Pago con billetera externa iniciado",
    "Invalid invoice data received": "Datos de factura inválidos recibidos",
    "Cannot open invoice URL": "No se puede abrir la URL de la factura",
    "Your wishlist is empty": "Su lista de deseos está vacía",
    "Loading payment page...": "Cargando página de pago...",
    "Incorrect username or password": "Usuario o contraseña incorrectos",
    "Sorry, your account has been deactivated": "Lo sentimos, su cuenta ha sido desactivada",
    "This email is already registered.": "Este correo ya está registrado.",
    "This username is already taken.": "Este nombre de usuario ya está en uso.",
    "This username is not allowed.": "Este nombre de usuario no está permitido.",
    "Already have an account": "¿Ya tiene una cuenta?",
    "don't have an account": "¿no tiene una cuenta?",
    "to Login": "para Iniciar Sesión",
    "to Signup": "para Registrarse",
    "Sign up successfully completed.Please Login Now": "Registro completado. Por favor inicie sesión.",
    "Please verify your email address": "Por favor verifique su dirección de correo",
    "Password updated successfully": "Contraseña actualizada correctamente",
    "Please verify that you are not a robot.": "Por favor verifique que no es un robot.",
    "Delete failed": "Error al eliminar",
    "Failed to create form.": "Error al crear el formulario.",
    "Failed to delete form.": "Error al eliminar el formulario.",
    "Failed to delete message": "Error al eliminar el mensaje.",
    "Failed to delete product.": "Error al eliminar el producto.",
    "Failed to send request": "Error al enviar la solicitud",
    "Failed to send reset email": "Error al enviar el correo de restablecimiento",
    "Failed to resend OTP": "Error al reenviar OTP",
    "Failed to reset password": "Error al restablecer la contraseña",
    "Failed to update form.": "Error al actualizar el formulario.",
    "Failed to verify OTP": "Error al verificar OTP",

    # NOTIFICATIONS
    "Notifications": "Notificaciones",
    "Notification": "Notificación",
    "New Notification": "Nueva Notificación",
    "Important push notifications appear here.": "Las notificaciones push importantes aparecen aquí.",

    # ABOUT
    "About": "Acerca de",
    "About Us": "Acerca de Nosotros",
    "About Us Page Title": "Título de Acerca de Nosotros",
    "About section updated successfully": "Sección Acerca de actualizada correctamente",
    "About Company": "Acerca de la Empresa",
    "about_company": "acerca de la empresa",

    # LOGIN / REGISTER
    "Login with Facebook": "Iniciar Sesión con Facebook",
    "Login with Google": "Iniciar Sesión con Google",
    "Login Status": "Estado de Inicio de Sesión",
    "Login Url": "URL de Inicio de Sesión",
    "forgot password": "olvidó su contraseña",
    "Send me a recovery link": "Envíeme un enlace de recuperación",
    "Find Now": "Buscar Ahora",
    "Search Now": "Buscar Ahora",

    # GENERAL STRINGS
    "Search by Title": "Buscar por Título",
    "Search By Title": "Buscar por Título",
    "Apply": "Aplicar",
    "Apply Filters": "Aplicar Filtros",
    "Results": "Resultados",
    "Showing": "Mostrando",
    "Found": "Encontrados",
    "Unknown": "Desconocido",
    "Unlimited": "Ilimitado",
    "Details": "Detalles",
    "Detail": "Detalle",
    "Description": "Descripción",
    "description": "descripción",
    "Configuration Rules": "Reglas de Configuración",
    "Configure Expiration": "Configurar Vencimiento",
    "Type": "Tipo",
    "type": "tipo",
    "Value": "Valor",
    "value": "valor",
    "Serial Number": "Número de Serie",
    "serial_number": "número de serie",
    "More": "Más",
    "Overview Of": "Resumen de",
    "Sort By": "Ordenar por",
    "Popular": "Popular",
    "Newest": "Más Reciente",
    "Oldest": "Más Antiguo",
    "High to Low": "De Mayor a Menor",
    "Low to High": "De Menor a Mayor",
    "Price : High to Low": "Precio: Mayor a Menor",
    "Price : Low to High": "Precio: Menor a Mayor",
    "Date : Newest on top": "Fecha: Más reciente primero",
    "Date : Oldest on top": "Fecha: Más antiguo primero",
    "Grid View": "Vista de Cuadrícula",
    "List View": "Vista de Lista",
    "Enter Details": "Ingrese Detalles",
    "Enter Text": "Ingrese Texto",
    "Enter Short Text": "Ingrese Texto Corto",
    "Enter button text": "Ingrese texto del botón",
    "Enter Button text": "Ingrese texto del botón",
    "Enter Button Name": "Ingrese Nombre del Botón",
    "Enter Button Text": "Ingrese Texto del Botón",
    "Enter Button URL": "Ingrese URL del Botón",
    "Card Code": "Código de Tarjeta",
    "Write Your Message": "Escriba su Mensaje",
    "Specifications": "Especificaciones",
    "Star": "Estrella",
    "star": "estrella",
    "Rating": "Puntuación",
    "Ratings": "Puntuaciones",
    "Your Rating": "Tu Puntuación",
    "Your Review": "Tu Opinión",
    "Reviews": "Opiniones",
    "To Give Your Review": "Para dar tu opinión",
    "Serial": "Serie",
    "Equipment Bookings": "Reservas de Equipos",
    "Transmission Types": "Tipos de Transmisión",
    "Wishlist": "Lista de Deseos",
    "Wishlists": "Listas de Deseos",
    "Wishlist Items": "Artículos de la Lista de Deseos",
    "My Wishlist": "Mi Lista de Deseos",
    "My Wishlists": "Mis Listas de Deseos",
    "Listing Wishlists": "Listas de Deseos de Anuncios",
    "No Link Found": "No se encontró enlace",
    "NO LISTING FOUND": "NO SE ENCONTRARON ANUNCIOS",
    "NO POST FOUND": "NO SE ENCONTRARON ARTÍCULOS",
    "NO PRODUCT FOUND": "NO SE ENCONTRARON PRODUCTOS",
    "NO REVIEW FOUND": "NO SE ENCONTRARON OPINIONES",
    "NO VENDOR FOUND": "NO SE ENCONTRARON PROVEEDORES",
    "NO WISHLIST FOUND": "NO SE ENCONTRARON LISTAS DE DESEOS",
    "NO WISHLIST ITEM FOUND": "NO SE ENCONTRARON ARTÍCULOS EN LISTA",
    "Search Wishlist": "Buscar en Lista de Deseos",
    "Search orders": "Buscar pedidos",
    "Save to Wishlist": "Guardar en Lista de Deseos",
    "Removed From wishlist successfully": "Eliminado de la lista de deseos correctamente",
    "Added to your wishlist successfully": "Añadido a tu lista de deseos correctamente",
    "Added to your wishlist successfully.": "Añadido a tu lista de deseos correctamente.",
    "We have sent you a mail with an invoice": "Le hemos enviado un correo con una factura",
    "We answer every request as quickly as we can": "Respondemos a cada solicitud lo antes posible",
    "Your profile has been updated successfully": "Su perfil ha sido actualizado correctamente",
    "Your review submitted successfully": "Su opinión fue enviada correctamente",
    "Thank you": "Gracias",
    "Example": "Ejemplo",
    "Save to Wishlist": "Guardar en Lista de Deseos",
    "New listing review": "Nueva opinión de anuncio",
    "You received a new review on one of your listings.": "Recibió una nueva opinión en uno de sus anuncios.",
    "New product review": "Nueva opinión de producto",
    "You received a new review on one of your products.": "Recibió una nueva opinión en uno de sus productos.",
    "You have not bought this product yet!": "¡Aún no has comprado este producto!",
    "You have not bought anything yet!": "¡Aún no has comprado nada!",
    "You have to Login First!": "¡Debe iniciar sesión primero!",
    "Your account is ready to use!": "¡Su cuenta está lista para usar!",
    "Password Reset Successful": "Restablecimiento de contraseña exitoso",
    "Verify & Continue": "Verificar y Continuar",
    "Resend code in": "Reenviar código en",
    "We have sent a 6 digit OTP to your registered email address": "Hemos enviado un OTP de 6 dígitos a su correo",
    "Enter Verification Code": "Ingrese el Código de Verificación",
    "Powered By KreativDev": "Desarrollado por KreativDev",
    "Retry": "Reintentar",
    "Confirm Logout": "Confirmar Cierre de Sesión",
    "Complete Payment": "Completar Pago",
    "Pay with PayTabs": "Pagar con PayTabs",
    "Crop Image": "Recortar Imagen",
    "Promos": "Promociones",
    "Show All Categories": "Mostrar Todas las Categorías",
    "LISTINGS": "Anuncios",
    "Please enter complete OTP": "Por favor ingrese el OTP completo",
    "OTP sent successfully": "OTP enviado correctamente",
    "Please": "Por favor",
    "Postcode/Zip": "Código Postal",
    "Tap to upload payment proof": "Toque para subir el comprobante de pago",
    "Verifying payment...": "Verificando pago...",
    "Share your experience...": "Comparte tu experiencia...",
    "Select date": "Seleccionar fecha",
    "Select time": "Seleccionar hora",
    "Enter shop location": "Ingrese ubicación de la tienda",
    "Make Query": "Hacer Consulta",
    "I'm Looking for": "Estoy Buscando",
    "Enter Current Password": "Ingrese Contraseña Actual",
    "Enter New Password": "Ingrese Nueva Contraseña",
    "Enter Password": "Ingrese Contraseña",
    "Confirm your new password": "Confirme su nueva contraseña",
    "Enter current password wrong!": "¡Contraseña actual incorrecta!",
    "Current password required": "Se requiere contraseña actual",
    "Confirm your new password": "Confirme su nueva contraseña",
    "Enter Full Name": "Ingrese Nombre Completo",
    "Enter Email": "Ingrese Correo",
    "Enter Phone": "Ingrese Teléfono",
    "Enter Address": "Ingrese Dirección",
    "Enter Phone Number": "Ingrese Número de Teléfono",
    "Enter Password": "Ingrese Contraseña",
    "Enter a valid amount": "Ingrese un monto válido",
    "Enter a valid email": "Ingrese un correo válido",
    "Username/Email*": "Usuario/Correo*",

    # ADDITIONAL STRINGS FROM admin_default.json
    "'Additional Reference (Optional)": "'Referencia Adicional (Opcional)",
    "Additional Reference": "Referencia Adicional",
    "Additional Reference (Optional)": "Referencia Adicional (Opcional)",
    "Additional Reference(Optional)": "Referencia Adicional (Opcional)",
    "Complete all mandatory setup steps": "Complete todos los pasos obligatorios",
    "Complete their profile setup": "Complete la configuración de su perfil",
    "After receiving the email, the user must": "Después de recibir el correo, el usuario debe",
    "After a location is seached, all the available listings which are located within this radius will be displayed.": "Después de buscar una ubicación, los anuncios dentro de este radio se mostrarán.",
    "A modern living room with a view of the city at sunset": "Una sala de estar moderna con vista a la ciudad al atardecer",
    "All Active Vendors": "Todos los Proveedores Activos",
    "All Limit": "Límite Total",
    "All Limits": "Todos los Límites",
    "Already a member?": "¿Ya eres miembro?",
    "Approve Claim": "Aprobar Reclamación",
    "Art Style": "Estilo Artístico",
    "Attach ZIP file (optional)": "Adjuntar archivo ZIP (opcional)",
    "Attachment Status": "Estado del Adjunto",
    "Auto-translate & clone to": "Traducir y clonar a",
    "BB Code": "Código BB",
    "Background Color Code": "Color de Fondo",
    "Background Color Opacity": "Opacidad de Fondo",
    "Banner Button Text": "Texto del Botón del Banner",
    "Banner Button Url": "URL del Botón del Banner",
    "Banner Section": "Sección del Banner",
    "Banner Title": "Título del Banner",
    "Both (Marketplace & Listing)": "Ambos (Marketplace y Anuncios)",
    "Both(Marketplace & Listing)": "Ambos (Marketplace y Anuncios)",
    "Button Color Code": "Color del Botón",
    "Button Name": "Nombre del Botón",
    "Button Text": "Texto del Botón",
    "Button URL": "URL del Botón",
    "By signing up, you agree to our terms and policies.": "Al registrarse, acepta nuestros términos y políticas.",
    "Camera Angle": "Ángulo de Cámara",
    "Close-up": "Primer Plano",
    "Eye-level": "A Nivel del Ojo",
    "Dramatic": "Dramático",
    "Flat Illustration": "Ilustración Plana",
    "3D Render": "Render 3D",
    "Change Password": "Cambiar Contraseña",
    "Check Limit": "Verificar Límite",
    "Choose AI Engine": "Elegir Motor de IA",
    "Click on the dropdown icon to select a icon.": "Haga clic en el icono desplegable para seleccionar un icono.",
    "Click on the dropdown icon to select an icon": "Haga clic en el icono desplegable para seleccionar un icono",
    "Configuration": "Configuración",
    "Conversations": "Conversaciones",
    "Create one quote request form for each language you support": "Cree un formulario de presupuesto por cada idioma",
    "Custom (600x400)": "Personalizado (600x400)",
    "Custom (800x800)": "Personalizado (800x800)",
    "Custom (900x600)": "Personalizado (900x600)",
    "Custom Fields": "Campos Personalizados",
    "Dashboard Page Title": "Título del Panel de Control",
    "Defines the total AI token usage allowed for this package for generating content": "Define el uso total de tokens de IA permitido para este paquete",
    "Describe Your Image Idea": "Describa su Idea de Imagen",
    "Do not create": "No crear",
    "Don't have an account?": "¿No tiene una cuenta?",
    "Download URL": "URL de Descarga",
    "Drag & drop to sort the input fields of this form": "Arrastre para ordenar los campos de este formulario",
    "Each AI image generation approximately costs USD 0.04 per image": "Cada imagen de IA cuesta aproximadamente USD 0.04",
    "Each language form will have its own fields": "Cada formulario de idioma tendrá sus propios campos",
    "Email address of enquirer": "Correo electrónico del consultante",
    "Email is missing. Please go back and enter email again.": "Falta el correo. Por favor vuelva e ingréselo de nuevo.",
    "Email is required": "El correo es obligatorio",
    "English content is usually cheaper, while other languages may consume more tokens and cost higher": "El contenido en inglés suele ser más barato",
    "Enter 999999 , then it will appear as unlimited": "Ingrese 999999, aparecerá como ilimitado",
    "Enter Additional Reference": "Ingrese Referencia Adicional",
    "Enter Amount": "Ingrese Monto",
    "Enter button text": "Ingrese texto del botón",
    "Enter Banner Title": "Ingrese Título del Banner",
    "Enter banner title": "Ingrese título del banner",
    "Enter banner button text": "Ingrese texto del botón del banner",
    "Enter banner button url": "Ingrese URL del botón del banner",
    "Enter category title": "Ingrese título de la categoría",
    "Enter Commission Amount": "Ingrese Monto de Comisión",
    "Enter Contact Mail": "Ingrese Correo de Contacto",
    "Enter Coupon Name": "Ingrese Nombre del Cupón",
    "Enter Coupon Value": "Ingrese Valor del Cupón",
    "Enter Current Price": "Ingrese Precio Actual",
    "Enter Current Pricet": "Ingrese Precio Actual",
    "Enter Days": "Ingrese Días",
    "Enter Download Link": "Ingrese Enlace de Descarga",
    "Enter Download URL": "Ingrese URL de Descarga",
    "Enter Email Address": "Ingrese Dirección de Correo",
    "Enter End Date": "Ingrese Fecha de Fin",
    "Enter End Time": "Ingrese Hora de Fin",
    "Enter File Size": "Ingrese Tamaño de Archivo",
    "Enter First Name": "Ingrese Nombre",
    "Enter Fixed Charge": "Ingrese Cargo Fijo",
    "Enter Google Adsense Publisher ID": "Ingrese ID de Editor de AdSense",
    "Enter Input Label": "Ingrese Etiqueta del Campo",
    "Enter Input Placeholder": "Ingrese Marcador del Campo",
    "Enter Last Name": "Ingrese Apellido",
    "Enter Mail Body Format": "Ingrese Formato del Cuerpo",
    "Enter Minimum Spend": "Ingrese Gasto Mínimo",
    "Enter new line to seperate features": "Ingrese nueva línea para separar características",
    "Enter number of days": "Ingrese número de días",
    "Enter Number of Listings": "Ingrese Número de Anuncios",
    "Enter Number of Products": "Ingrese Número de Productos",
    "Enter Number of Products per Listing": "Ingrese Número de Productos por Anuncio",
    "Enter Number of Images per Product": "Ingrese Número de Imágenes por Producto",
    "Enter Number of image per Listing": "Ingrese Número de Imágenes por Anuncio",
    "Enter Number of FAQs per Listing": "Ingrese Número de FAQs por Anuncio",
    "Enter Number of Features per Listing": "Ingrese Número de Características por Anuncio",
    "Enter Number of Social Links per Listing": "Ingrese Número de Enlaces Sociales por Anuncio",
    "Enter Number of Amenities per Listing": "Ingrese Número de Servicios por Anuncio",
    "Enter package price": "Ingrese precio del paquete",
    "Enter package title": "Ingrese título del paquete",
    "Enter Percentage Charge": "Ingrese Cargo Porcentual",
    "Enter Previous Price": "Ingrese Precio Anterior",
    "Enter Price": "Ingrese Precio",
    "Enter Push Notification Title": "Ingrese Título de Notificación Push",
    "Enter Rating": "Ingrese Puntuación",
    "Enter Redirect URL": "Ingrese URL de Redirección",
    "Enter Role Name": "Ingrese Nombre del Rol",
    "Enter Serial Number": "Ingrese Número de Serie",
    "Enter Shipping Charge": "Ingrese Costo de Envío",
    "Enter Start Date": "Ingrese Fecha de Inicio",
    "Enter the 6-digit OTP sent to": "Ingrese el OTP de 6 dígitos enviado a",
    "Enter the 6-digit OTP sent to your email.": "Ingrese el OTP de 6 dígitos enviado a su correo.",
    "Enter Total AI Image Limit": "Ingrese Límite Total de Imágenes IA",
    "Enter Total AI Token Limit": "Ingrese Límite Total de Tokens IA",
    "Enter Username": "Ingrese Nombre de Usuario",
    "Enter VAPID Private Key": "Ingrese Clave Privada VAPID",
    "Enter VAPID Public Key": "Ingrese Clave Pública VAPID",
    "Enter Video URL": "Ingrese URL del Video",
    "Enter Website Title": "Ingrese Título del Sitio Web",
    "Enter your new password and confirm it to complete reset.": "Ingrese su nueva contraseña y confírmela para completar el restablecimiento.",
    "Enter your vendor email. We will send a 6-digit OTP to your email.": "Ingrese su correo de proveedor. Enviaremos un OTP de 6 dígitos.",
    "Enter Zip Code": "Ingrese Código Postal",
    "Example: Premium product on a clean background": "Ejemplo: Producto premium sobre fondo limpio",
    "Example: Premium wireless earbuds with deep bass": "Ejemplo: Auriculares inalámbricos premium con graves profundos",
    "Example: Red SUV on a clean studio background": "Ejemplo: SUV rojo sobre fondo de estudio limpio",
    "Exit": "Salir",
    "Exit App?": "¿Salir de la App?",
    "Facebook info updated successfully": "Información de Facebook actualizada correctamente",
    "Fill in the details below to get started.": "Complete los detalles a continuación para comenzar.",
    "First delete all the State of these Country": "Primero elimine todos los estados de este país",
    "First delete all the State of this Country": "Primero elimine todos los estados de este país",
    "First delete all the city of these Country": "Primero elimine todas las ciudades de este país",
    "First delete all the city of these State": "Primero elimine todas las ciudades de este estado",
    "First delete all the city of this Country": "Primero elimine todas las ciudades de este país",
    "First delete all the city of this State": "Primero elimine todas las ciudades de este estado",
    "First delete all the listing of these Amenities": "Primero elimine los anuncios de estos servicios",
    "First delete all the listing of these City": "Primero elimine los anuncios de esta ciudad",
    "First delete all the listing of these Country": "Primero elimine los anuncios de este país",
    "First delete all the listing of these State": "Primero elimine los anuncios de este estado",
    "First delete all the listing of these categories": "Primero elimine los anuncios de estas categorías",
    "First delete all the listing of this Amenitie": "Primero elimine los anuncios de este servicio",
    "First delete all the listing of this City": "Primero elimine los anuncios de esta ciudad",
    "First delete all the listing of this Country": "Primero elimine los anuncios de este país",
    "First delete all the listing of this State": "Primero elimine los anuncios de este estado",
    "First delete all the listing of this category": "Primero elimine los anuncios de esta categoría",
    "First delete all the blog of these categories": "Primero elimine los blogs de estas categorías",
    "First delete all the blog of this category": "Primero elimine los blogs de esta categoría",
    "First delete all the product of these categories": "Primero elimine los productos de estas categorías",
    "First delete all the products of this category": "Primero elimine los productos de esta categoría",
    "For mobile app display": "Para visualización en la app móvil",
    "For reference, 1K token approximately equal to USD 0.0015": "Como referencia, 1K tokens equivalen aproximadamente a USD 0.0015",
    "Form metadata could not be loaded.": "No se pudo cargar la metadata del formulario.",
    "Gemini": "Gemini",
    "Gemini API Key": "Clave API de Gemini",
    "Gemini Image Model": "Modelo de Imagen de Gemini",
    "Gemini Image models must include the version suffix (-001)": "Los modelos de imagen deben incluir el sufijo de versión (-001)",
    "Gemini Text Model": "Modelo de Texto de Gemini",
    "Generate password": "Generar contraseña",
    "Generates all SEO fields for the current language tab at once.": "Genera todos los campos SEO para la pestaña de idioma actual de una vez.",
    "Gird": "Cuadrícula",
    "Go Here": "Ir Aquí",
    "Gold": "Oro",
    "GOLD": "ORO",
    "Google Gemini": "Google Gemini",
    "Google info updated successfully": "Información de Google actualizada correctamente",
    "Google map api updated successfully": "API de Google Maps actualizada correctamente",
    "Google will not suggest locations under address inputs.": "Google no sugerirá ubicaciones debajo de las direcciones.",
    "Hide password": "Ocultar contraseña",
    "How Many Days Active": "Cuántos Días Activo",
    "If any feature has crossed its current subscription package's limit, then you won't be able to add/edit any other feature": "Si una característica superó el límite, no podrá añadir/editar otras",
    "If any feature has crossed its current subscription package/'s limit, you won/'t be able to add/edit any other feature.": "Si una característica superó el límite, no podrá añadir/editar otras.",
    "If any feature is downgraded , you can't create or edit any feature.": "Si una característica se reduce, no podrá crear ni editar ninguna.",
    "If the Google Maps API is disabled:": "Si la API de Google Maps está deshabilitada:",
    "If you enable Tawk.To, then you must disable WhatsApp": "Si habilita Tawk.To, debe deshabilitar WhatsApp",
    "If you enable WhatsApp, then you must disable Tawk.To": "Si habilita WhatsApp, debe deshabilitar Tawk.To",
    "If your current package is lifetime package, then you have to change / remove the current package first": "Si su paquete actual es vitalicio, debe cambiarlo/eliminarlo primero",
    "If your current package is trial package, then you have to change / remove the current package first": "Si su paquete actual es de prueba, debe cambiarlo/eliminarlo primero",
    "Image Count": "Número de Imágenes",
    "Image Size 600x400": "Tamaño 600x400",
    "Image Size 80x80": "Tamaño 80x80",
    "Image Usage": "Uso de Imágenes",
    "Important": "Importante",
    "Industry Type": "Tipo de Industria",
    "Iraq": "Irak",
    "Egypt": "Egipto",
    "Gold": "Oro",
    "Silver": "Plata",
    "Diamond": "Diamante",
    "Platinum": "Platino",
    "Enter a new password": "Ingrese una nueva contraseña",
    "Enter amount": "Ingrese monto",
    "Enter additional reference": "Ingrese referencia adicional",
    "Enter current password": "Ingrese contraseña actual",
    "Enter new password": "Ingrese nueva contraseña",
    "Enter password again": "Ingrese contraseña nuevamente",
    "Create password": "Crear contraseña",
    "Generate password": "Generar contraseña",
    "Your Rating": "Tu Puntuación",
    "Your Review": "Tu Opinión",
    "Please select a rating": "Por favor seleccione una puntuación",
    "Please write your review": "Por favor escriba su opinión",
    "Review must be at least 10 characters": "La opinión debe tener al menos 10 caracteres",
    "Review submitted successfully!": "¡Opinión enviada correctamente!",
    "Failed to submit review": "Error al enviar la opinión",
    "Please login first": "Por favor inicie sesión primero",
    "Please login to continue": "Por favor inicie sesión para continuar",
    "Please login": "Por favor inicie sesión",
    "already have an account": "ya tiene una cuenta",
    "don't have an account": "no tiene una cuenta",
    "to Login": "para Iniciar Sesión",
    "to Signup": "para Registrarse",
    "Already have an account": "¿Ya tiene una cuenta?",
    "I'm Looking for": "Estoy Buscando",
    "Make Query": "Hacer Consulta",
    "No Equipment Found": "No se encontraron equipos",
    "No Partner Found": "No se encontraron socios",
    "No Partner Information Found": "No se encontró información de socios",
    "Please enter complete OTP": "Por favor ingrese el OTP completo",
    "OTP sent successfully": "OTP enviado correctamente",
    "Promos": "Promociones",
    "Signed up successfully": "Registrado correctamente",
    "Sorry, you are offline": "Lo sentimos, está desconectado",
    "We have sent you a mail with an invoice": "Le hemos enviado un correo con una factura",
    "We answer every request as quickly as we can": "Respondemos a cada solicitud lo antes posible",
    "Upgrade": "Actualizar",
    "Downgrade": "Degradar",
    "Renew": "Renovar",
    "Cancel Subscription": "Cancelar Suscripción",
    "Resume Subscription": "Reanudar Suscripción",
    "Change Plan": "Cambiar Plan",
    "Plan": "Plan",
    "Plans": "Planes",
    "Trial Plan": "Plan de Prueba",
    "Free Plan": "Plan Gratuito",
    "Premium Plan": "Plan Premium",
    "Enterprise Plan": "Plan Empresarial",
    "Upload new image": "Subir nueva imagen",
    "or drag and drop": "o arrastrar y soltar",
    "Click to upload": "Haga clic para subir",
    "SVG files only": "Solo archivos SVG",
    "Supported formats": "Formatos compatibles",
    "Enter the title": "Ingrese el título",
    "Enter the subtitle": "Ingrese el subtítulo",
    "Enter the description": "Ingrese la descripción",
    "Enter the content": "Ingrese el contenido",
    "Settings": "Configuración",
    "Notifications": "Notificaciones",
    "Notification": "Notificación",
    "New Notification": "Nueva Notificación",
    "Mark all as read": "Marcar todas como leídas",
    "Mark as read": "Marcar como leída",
    "No notifications found": "No se encontraron notificaciones",
    "View all notifications": "Ver todas las notificaciones",
    "Send notification": "Enviar notificación",
    "Notification type": "Tipo de notificación",
    "Notification title": "Título de la notificación",
    "Notification message": "Mensaje de notificación",
    "Notification sent successfully": "Notificación enviada correctamente",
    "Add at least 1 lowercase letter": "Añada al menos 1 letra minúscula",
    "Add at least 1 number": "Añada al menos 1 número",
    "Add at least 1 symbol": "Añada al menos 1 símbolo",
    "Add at least 1 uppercase letter": "Añada al menos 1 letra mayúscula",
    "Add more": "Añadir más",
    "Add your own fields after creating the form using the Manage button": "Añada sus propios campos después de crear el formulario usando el botón Gestionar",
    "A new user has been added successfully": "Un nuevo usuario ha sido añadido correctamente",
}

def apply_translations(filepath, translations):
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    translated = 0
    for key in data:
        if key in translations:
            data[key] = translations[key]
            translated += 1

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write('\n')

    print(f"✓ {filepath}: {translated} keys translated")

if __name__ == '__main__':
    base = '/Users/admin/Documents/dev/profiexp.com/app/resources/lang'
    apply_translations(f'{base}/es.json', translations)
    apply_translations(f'{base}/admin_es.json', translations)
    print("Done!")
